import type { TestConfig } from "./types";

/**
 * Big Five / OCEAN personality test (BFAS — Big Five Aspect Scales)
 * TODO: Replace placeholder questions with validated Big Five question bank (e.g., IPIP-NEO)
 */
export const big5Config: TestConfig = {
  type: "BIG_FIVE",
  name: "Big Five",
  description: "Az öt nagy személyiségvonás (OCEAN) mérése.",
  format: "likert",
  dimensions: [
    {
      code: "O",
      label: "Nyitottság",
      labelByLocale: {
        en: "Openness",
        de: "Offenheit",
      },
      color: "#38BDF8",
      description: "A szellemi kíváncsiságot, kreativitást és az új élmények iránti nyitottságot méri. Magas értéknél vonzódás az absztrakt gondolkodáshoz, míg alacsonyabb értéknél a gyakorlatias, hagyományos megoldások preferálása.",
      descriptionByLocale: {
        en: "Measures intellectual curiosity, creativity, and openness to new experiences. High scores are drawn to abstract thinking; lower scores prefer practical, traditional approaches.",
        de: "Misst intellektuelle Neugier, Kreativität und Offenheit für neue Erfahrungen. Hohe Werte neigen zu abstraktem Denken, niedrigere bevorzugen praktische, traditionelle Ansätze.",
      },
      insights: {
        low: "Gyakorlatias, hagyományos megközelítés, bevált módszereket preferálsz.",
        mid: "Nyitott az új ötletekre, de a realitás talaján maradsz.",
        high: "Kíváncsi, kreatív gondolkodás, vonzzák az újító megoldások.",
      },
      insightsByLocale: {
        en: {
          low: "Practical and traditional; you prefer proven methods.",
          mid: "Open to new ideas while staying grounded.",
          high: "Curious and creative; drawn to novel solutions.",
        },
        de: {
          low: "Praktisch und traditionell; du bevorzugst bewährte Methoden.",
          mid: "Offen für neue Ideen, bleibst aber realitätsnah.",
          high: "Neugierig und kreativ; angezogen von neuen Lösungen.",
        },
      },
      aspects: [
        { code: "intellect", label: "Intellektus", labelByLocale: { en: "Intellect", de: "Intellekt" } },
        { code: "openness", label: "Nyitottság", labelByLocale: { en: "Openness", de: "Offenheit" } },
      ],
    },
    {
      code: "C",
      label: "Lelkiismeretesség",
      labelByLocale: {
        en: "Conscientiousness",
        de: "Gewissenhaftigkeit",
      },
      color: "#A78BFA",
      description: "A szervezettséget, kitartást és fegyelmet méri. Magas értéknél gondos, tervszerű munkavégzés jellemző, míg alacsonyabb értéknél rugalmasabb, spontánabb hozzáállás.",
      descriptionByLocale: {
        en: "Measures organization, persistence, and discipline. High scores indicate careful, structured work; lower scores reflect a more flexible, spontaneous style.",
        de: "Misst Organisation, Ausdauer und Disziplin. Hohe Werte stehen für sorgfältiges, planvolles Arbeiten, niedrigere für einen flexibleren, spontanen Stil.",
      },
      insights: {
        low: "Spontán, rugalmas megközelítés, kevésbé kötött tervekhez.",
        mid: "Megbízható végrehajtás, de tudsz alkalmazkodni a változásokhoz.",
        high: "Rendszerezett, következetes munkastílus, magas felelősségtudat.",
      },
      insightsByLocale: {
        en: {
          low: "Spontaneous and flexible; you prefer fewer fixed plans.",
          mid: "Reliable execution with the ability to adapt.",
          high: "Structured and consistent with strong responsibility.",
        },
        de: {
          low: "Spontan und flexibel; du bevorzugst weniger feste Pläne.",
          mid: "Zuverlässige Umsetzung mit Anpassungsfähigkeit.",
          high: "Strukturiert und konsequent mit hohem Verantwortungsbewusstsein.",
        },
      },
      aspects: [
        { code: "industriousness", label: "Szorgalom", labelByLocale: { en: "Industriousness", de: "Fleiß" } },
        { code: "orderliness", label: "Rendszeresség", labelByLocale: { en: "Orderliness", de: "Ordentlichkeit" } },
      ],
    },
    {
      code: "E",
      label: "Extraverzió",
      labelByLocale: {
        en: "Extraversion",
        de: "Extraversion",
      },
      color: "#F59E0B",
      description: "A társas energia szintjét és a szociális magabiztosságot méri. Magas értéknél élénk, társaságkedvelő személyiség rajzolódik ki, míg alacsonyabb értéknél az egyéni tevékenységek és a visszahúzódás a jellemzőbb.",
      descriptionByLocale: {
        en: "Measures social energy and confidence. High scores indicate a lively, sociable personality; lower scores favor solitary activities and reservedness.",
        de: "Misst soziale Energie und Selbstsicherheit. Hohe Werte deuten auf eine lebhafte, gesellige Persönlichkeit hin, niedrigere auf zurückgezogene, individuelle Aktivitäten.",
      },
      insights: {
        low: "Inkább introvertált, a nyugodt, egyéni tevékenységeket preferálod.",
        mid: "Kiegyensúlyozott társas energia: tudsz vezetni, de szeretsz fókuszálni is.",
        high: "Energikus, társaságkedvelő, magabiztos közösségi helyzetekben.",
      },
      insightsByLocale: {
        en: {
          low: "More introverted; you prefer calm, individual activities.",
          mid: "Balanced social energy: you can lead and also focus independently.",
          high: "Energetic, outgoing, confident in social settings.",
        },
        de: {
          low: "Eher introvertiert; du bevorzugst ruhige, individuelle Aktivitäten.",
          mid: "Ausgewogene soziale Energie: du kannst führen und dich zugleich gut fokussieren.",
          high: "Energisch, gesellig, selbstbewusst in sozialen Situationen.",
        },
      },
      aspects: [
        { code: "enthusiasm", label: "Lelkesedés", labelByLocale: { en: "Enthusiasm", de: "Begeisterung" } },
        { code: "assertiveness", label: "Magabiztosság", labelByLocale: { en: "Assertiveness", de: "Durchsetzungsvermögen" } },
      ],
    },
    {
      code: "A",
      label: "Barátságosság",
      labelByLocale: {
        en: "Agreeableness",
        de: "Verträglichkeit",
      },
      color: "#34D399",
      description: "Az együttműködési hajlandóságot és a mások iránti türelmet méri. Magas értéknél megbocsátó, kompromisszumkész természet jellemző, míg alacsonyabb értéknél kritikusabb, konfrontatívabb stílus.",
      descriptionByLocale: {
        en: "Measures cooperation and tolerance toward others. High scores indicate a forgiving, compromise‑oriented nature; lower scores reflect a more critical, confrontational style.",
        de: "Misst Kooperationsbereitschaft und Geduld gegenüber anderen. Hohe Werte stehen für eine verzeihende, kompromissbereite Art, niedrigere für einen kritischeren, konfrontativeren Stil.",
      },
      insights: {
        low: "Határozott, kritikus gondolkodás, nem félsz a konfrontációtól.",
        mid: "Rugalmas együttműködés, de meg tudod védeni az álláspontodat.",
        high: "Erős együttműködési készség, konfliktushelyzetben is empatikus.",
      },
      insightsByLocale: {
        en: {
          low: "Decisive and critical; you are not afraid of confrontation.",
          mid: "Flexible cooperation while defending your position.",
          high: "Strong cooperative spirit; empathetic even in conflict.",
        },
        de: {
          low: "Entschlossen und kritisch; du scheust keine Konfrontation.",
          mid: "Flexibel kooperativ und dennoch standhaft.",
          high: "Hohe Kooperationsbereitschaft; empathisch auch in Konflikten.",
        },
      },
      aspects: [
        { code: "compassion", label: "Együttérzés", labelByLocale: { en: "Compassion", de: "Mitgefühl" } },
        { code: "politeness", label: "Udvariasság", labelByLocale: { en: "Politeness", de: "Höflichkeit" } },
      ],
    },
    {
      code: "N",
      label: "Neuroticizmus",
      labelByLocale: {
        en: "Neuroticism",
        de: "Neurotizismus",
      },
      color: "#FB7185",
      description: "Az érzelmi instabilitás és a stresszre való érzékenység mértékét méri. Magas értéknél intenzívebb a szorongás és a negatív érzelmek átélése, míg alacsonyabb értéknél érzelmi stabilitás és nyugodtság jellemző.",
      descriptionByLocale: {
        en: "Measures emotional instability and sensitivity to stress. High scores indicate stronger anxiety and negative affect; lower scores reflect emotional stability and calmness.",
        de: "Misst emotionale Instabilität und Stressanfälligkeit. Hohe Werte stehen für stärkere Ängstlichkeit und negative Affekte, niedrigere für emotionale Stabilität und Gelassenheit.",
      },
      insights: {
        low: "Érzelmileg stabil, ritkán aggódsz vagy idegeskedsz.",
        mid: "Általában kiegyensúlyozott, de stresszhelyzetben fokozott érzékenység.",
        high: "Intenzív érzelmi megélés, hajlamos a szorongásra és stresszre.",
      },
      insightsByLocale: {
        en: {
          low: "Emotionally stable; you rarely worry or feel anxious.",
          mid: "Generally balanced, but more sensitive under stress.",
          high: "Intense emotional experience; prone to anxiety and stress.",
        },
        de: {
          low: "Emotional stabil; du sorgst dich selten oder bist selten nervös.",
          mid: "Meist ausgeglichen, aber unter Stress sensibler.",
          high: "Intensives emotionales Erleben; anfälliger für Angst und Stress.",
        },
      },
      aspects: [
        { code: "withdrawal", label: "Visszahúzódás", labelByLocale: { en: "Withdrawal", de: "Rückzug" } },
        { code: "volatility", label: "Változékonyság", labelByLocale: { en: "Volatility", de: "Volatilität" } },
      ],
    },
  ],
  questions: [
    {
      id: 1,
      dimension: "C",
      aspect: "industriousness",
      text: "Halogatom a döntéseket.",
      textByLocale: { hu: "Halogatom a döntéseket.", en: "Postpone decisions.", de: "Ich schiebe Entscheidungen auf." },
      reversed: true,
    },
    {
      id: 2,
      dimension: "A",
      aspect: "compassion",
      text: "Nincs bennem gyengéd oldal.",
      textByLocale: { hu: "Nincs bennem gyengéd oldal.", en: "Don't have a soft side.", de: "Mir fehlt eine weiche Seite." },
      reversed: true,
    },
    {
      id: 3,
      dimension: "A",
      aspect: "politeness",
      text: "Szeretem a jó kis konfliktust.",
      textByLocale: { hu: "Szeretem a jó kis konfliktust.", en: "Love a good fight.", de: "Ich mag Diskussionen und ' Auseinandersetzungen." },
      reversed: true,
    },
    {
      id: 4,
      dimension: "O",
      aspect: "intellect",
      text: "Nehezen értem meg az elvont gondolatokat.",
      textByLocale: { hu: "Nehezen értem meg az elvont gondolatokat.", en: "Have difficulty understanding abstract ideas.", de: "Ich habe Schwierigkeiten, abstrakte ideen zu verstehen." },
      reversed: true,
    },
    {
      id: 5,
      dimension: "N",
      aspect: "withdrawal",
      text: "Könnyen fenyegetve érzem magam.",
      textByLocale: { hu: "Könnyen fenyegetve érzem magam.", en: "Feel threatened easily.", de: "Ich fühle mich schnell bedroht." },
    },
    {
      id: 6,
      dimension: "N",
      aspect: "withdrawal",
      text: "Ritkán vagyok szomorú.",
      textByLocale: { hu: "Ritkán vagyok szomorú.", en: "Seldom feel blue.", de: "Ich bin selten deprimiert." },
      reversed: true,
    }/*,
    {
      id: 7,
      dimension: "A",
      aspect: "compassion",
      text: "Nem érdekelnek mások problémái.",
      textByLocale: { hu: "Nem érdekelnek mások problémái.", en: "Am not interested in other people's problems.", de: "Ich interessiere mich nicht für Probleme anderer." },
      reversed: true,
    },
    {
      id: 8,
      dimension: "N",
      aspect: "withdrawal",
      text: "Ritkán érzem magam lehangoltnak.",
      textByLocale: { hu: "Ritkán érzem magam lehangoltnak.", en: "Rarely feel depressed.", de: "Es kommt selten vor, dass ich mich niedergeschlagen fühle." },
      reversed: true,
    },
    {
      id: 9,
      dimension: "N",
      aspect: "volatility",
      text: "Kontroll alatt tartom az érzelmeimet.",
      textByLocale: { hu: "Kontroll alatt tartom az érzelmeimet.", en: "Keep my emotions under control.", de: "h kann meine Gefühle gut de m kontrollieren." },
      reversed: true,
    },
    {
      id: 10,
      dimension: "E",
      aspect: "assertiveness",
      text: "Jó vezetőnek tartom magam.",
      textByLocale: { hu: "Jó vezetőnek tartom magam.", en: "See myself as a good leader.", de: "d Ich bin gut darin, Führung zu rnehmen." },
    },
    {
      id: 11,
      dimension: "E",
      aspect: "assertiveness",
      text: "Megvárom, hogy mások vezessenek.",
      textByLocale: { hu: "Megvárom, hogy mások vezessenek.", en: "Wait for others to lead the way.", de: "h überlasse es anderen, den Weg zu weisen." },
      reversed: true,
    },
    {
      id: 12,
      dimension: "N",
      aspect: "volatility",
      text: "Könnyen felzaklatódom.",
      textByLocale: { hu: "Könnyen felzaklatódom.", en: "Get upset easily.", de: "Ich gerate leicht aus der Fassung." },
    },
    {
      id: 13,
      dimension: "N",
      aspect: "withdrawal",
      text: "Tele vagyok kétségekkel a dolgokat illetően.",
      textByLocale: { hu: "Tele vagyok kétségekkel a dolgokat illetően.", en: "Am filled with doubts about things.", de: "Ich bin häufig beunruhigt." },
    },
    {
      id: 14,
      dimension: "A",
      aspect: "politeness",
      text: "Megsértem az embereket.",
      textByLocale: { hu: "Megsértem az embereket.", en: "Insult people.", de: "Manchmal beleidige ich ' andere Leute." },
      reversed: true,
    },
    {
      id: 15,
      dimension: "C",
      aspect: "orderliness",
      text: "Nem zavar, ha valaki rendetlen.",
      textByLocale: { hu: "Nem zavar, ha valaki rendetlen.", en: "Am not bothered by messy people.", de: "Es stört mich nicht, wenn andere Menschen unordentlich sind." },
      reversed: true,
    },
    {
      id: 16,
      dimension: "N",
      aspect: "volatility",
      text: "Könnyen felhergelhető vagyok.",
      textByLocale: { hu: "Könnyen felhergelhető vagyok.", en: "Can be stirred up easily.", de: "Ich bin schnell gerührt." },
    },
    {
      id: 17,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Sokszor nevetek.",
      textByLocale: { hu: "Sokszor nevetek.", en: "Laugh a lot.", de: "Ich lache viel." },
    },
    {
      id: 18,
      dimension: "C",
      aspect: "orderliness",
      text: "Ügyelek arra, hogy a szabályokat betartsák.",
      textByLocale: { hu: "Ügyelek arra, hogy a szabályokat betartsák.", en: "See that rules are observed.", de: "Ich achte darauf, dass Regeln eingehalten werden." },
    },
    {
      id: 19,
      dimension: "A",
      aspect: "politeness",
      text: "Ritkán helyezek nyomást másokra.",
      textByLocale: { hu: "Ritkán helyezek nyomást másokra.", en: "Rarely put people under pressure.", de: "Ich setze andere nur selten unter Druck." },
    },
    {
      id: 20,
      dimension: "C",
      aspect: "industriousness",
      text: "Mindig tudom, mit csinálok.",
      textByLocale: { hu: "Mindig tudom, mit csinálok.", en: "Always know what I am doing.", de: "Ich weiss immer, was ich tue." },
    },
    {
      id: 21,
      dimension: "N",
      aspect: "volatility",
      text: "Olyan ember vagyok, akinek a hangulata könnyen ingadozik.",
      textByLocale: { hu: "Olyan ember vagyok, akinek a hangulata könnyen ingadozik.", en: "Am a person whose moods go up and down easily.", de: "eine Stimmung verändert sich leicht." },
    },
    {
      id: 22,
      dimension: "A",
      aspect: "compassion",
      text: "Együtt érzek mások érzéseivel.",
      textByLocale: { hu: "Együtt érzek mások érzéseivel.", en: "Sympathize with others' feelings.", de: "Ich kann die Gefühle anderer nachempfinden." },
    },
    {
      id: 23,
      dimension: "C",
      aspect: "industriousness",
      text: "Gyorsan elvégzem a feladataimat.",
      textByLocale: { hu: "Gyorsan elvégzem a feladataimat.", en: "Get things done quickly.", de: "Ich erledige meine Aufgaben ch." },
    },
    {
      id: 24,
      dimension: "A",
      aspect: "politeness",
      text: "A saját hasznomat tartom szem előtt.",
      textByLocale: { hu: "A saját hasznomat tartom szem előtt.", en: "Am out for my own personal gain.", de: "schaue auf meinen sönlichen Vorteil." },
      reversed: true,
    },
    {
      id: 25,
      dimension: "N",
      aspect: "withdrawal",
      text: "Könnyen kedvemet vesztem.",
      textByLocale: { hu: "Könnyen kedvemet vesztem.", en: "Am easily discouraged.", de: "Ich lasse mich schnell entmutigen." },
    },
    {
      id: 26,
      dimension: "O",
      aspect: "intellect",
      text: "Világosan megfogalmazom az ötleteimet.",
      textByLocale: { hu: "Világosan megfogalmazom az ötleteimet.", en: "Formulate ideas clearly.", de: "Ich kann meine Gedanken klar formulieren." },
    },
    {
      id: 27,
      dimension: "E",
      aspect: "assertiveness",
      text: "Rá tudom beszélni másokat, hogy megtegyenek dolgokat.",
      textByLocale: { hu: "Rá tudom beszélni másokat, hogy megtegyenek dolgokat.", en: "Can talk others into doing things.", de: "Ich kann andere dazu bringen, ge zu tun, die ich will." },
    },
    {
      id: 28,
      dimension: "A",
      aspect: "compassion",
      text: "Közömbös vagyok mások érzései iránt.",
      textByLocale: { hu: "Közömbös vagyok mások érzései iránt.", en: "Am indifferent to the feelings of others.", de: "Ich stehe den Gefühlen Le . anderer gleichgültig gegenüber." },
      reversed: true,
    },
    {
      id: 29,
      dimension: "C",
      aspect: "orderliness",
      text: "Nem szeretem a rutint.",
      textByLocale: { hu: "Nem szeretem a rutint.", en: "Dislike routine.", de: "Routine mag ich nicht." },
      reversed: true,
    },
    {
      id: 30,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Nem vagyok túl lelkes ember.",
      textByLocale: { hu: "Nem vagyok túl lelkes ember.", en: "Am not a very enthusiastic person.", de: "Ich bin keine besonders enthusiastische Person." },
      reversed: true,
    },
    {
      id: 31,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Nehezen lehet megismerni.",
      textByLocale: { hu: "Nehezen lehet megismerni.", en: "Am hard to get to know.", de: "ich näher kennenzulernen s d fällt schwer." },
      reversed: true,
    },
    {
      id: 32,
      dimension: "C",
      aspect: "industriousness",
      text: "Könnyen elterelődik a figyelmem.",
      textByLocale: { hu: "Könnyen elterelődik a figyelmem.", en: "Am easily distracted.", de: "d. Ich lasse mich leicht ablenken." },
      reversed: true,
    },
    {
      id: 33,
      dimension: "O",
      aspect: "openness",
      text: "Hiszek a művészet fontosságában.",
      textByLocale: { hu: "Hiszek a művészet fontosságában.", en: "Believe in the importance of art.", de: "Kunst ist sehr wichtig für art. mich." },
    },
    {
      id: 34,
      dimension: "E",
      aspect: "assertiveness",
      text: "Nincs tehetségem mások befolyásolásához.",
      textByLocale: { hu: "Nincs tehetségem mások befolyásolásához.", en: "Lack the talent for influencing people.", de: "ch bin nicht gut darin, andere zu beeinflussen." },
      reversed: true,
    },
    {
      id: 35,
      dimension: "O",
      aspect: "openness",
      text: "Nem szeretem a költészetet.",
      textByLocale: { hu: "Nem szeretem a költészetet.", en: "Do not like poetry.", de: "try. Poesie beeindruckt mich wenig oder gar nicht." },
      reversed: true,
    },
    {
      id: 36,
      dimension: "O",
      aspect: "intellect",
      text: "Lassan tanulok.",
      textByLocale: { hu: "Lassan tanulok.", en: "Learn things slowly.", de: "y. Ich brauche manchmal länger, ' um etwas Neues zu lernen." },
      reversed: true,
    },
    {
      id: 37,
      dimension: "E",
      aspect: "assertiveness",
      text: "Nincs határozott személyiségem.",
      textByLocale: { hu: "Nincs határozott személyiségem.", en: "Do not have an assertive personality.", de: "Ich bin nicht durchsetzungsfähig." },
      reversed: true,
    },
    {
      id: 38,
      dimension: "C",
      aspect: "orderliness",
      text: "Széthagyom a holmimat.",
      textByLocale: { hu: "Széthagyom a holmimat.", en: "Leave my belongings around.", de: "Ich lasse meine Sachen herumliegen." },
      reversed: true,
    },
    {
      id: 39,
      dimension: "N",
      aspect: "withdrawal",
      text: "Nem jövök könnyen zavarba.",
      textByLocale: { hu: "Nem jövök könnyen zavarba.", en: "Am not embarrassed easily.", de: "Mir ist selten etwas peinlich." },
      reversed: true,
    },
    {
      id: 40,
      dimension: "C",
      aspect: "industriousness",
      text: "Nehezemre esik belefogni a munkába.",
      textByLocale: { hu: "Nehezemre esik belefogni a munkába.", en: "Find it difficult to get down to work.", de: "get Es fällt mir schwer, mich an die Arbeit zu machen." },
      reversed: true,
    },
    {
      id: 41,
      dimension: "A",
      aspect: "compassion",
      text: "Érdeklődöm mások élete iránt.",
      textByLocale: { hu: "Érdeklődöm mások élete iránt.", en: "Take an interest in other people's lives.", de: "ch interessiere mich für das 'i Leben anderer." },
    },
    {
      id: 42,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Gyorsan feloldódom másokkal.",
      textByLocale: { hu: "Gyorsan feloldódom másokkal.", en: "Warm up quickly to others.", de: "Ich lerne schnell neue Leute kennen." },
    },
    {
      id: 43,
      dimension: "O",
      aspect: "intellect",
      text: "Gyorsan gondolkodom.",
      textByLocale: { hu: "Gyorsan gondolkodom.", en: "Think quickly.", de: "Ich habe eine schnelle Auffassungsgabe." },
    },
    {
      id: 44,
      dimension: "N",
      aspect: "volatility",
      text: "Könnyen felhevülök.",
      textByLocale: { hu: "Könnyen felhevülök.", en: "Get easily agitated.", de: "d. Ich bin schnell aufgewühlt." },
    },
    {
      id: 45,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Keveset árulok el magamról.",
      textByLocale: { hu: "Keveset árulok el magamról.", en: "Reveal little about myself.", de: "Ich gebe wenig über mich preis." },
      reversed: true,
    },
    {
      id: 46,
      dimension: "A",
      aspect: "politeness",
      text: "Azt hiszem, jobb vagyok másoknál.",
      textByLocale: { hu: "Azt hiszem, jobb vagyok másoknál.", en: "Believe that I am better than others.", de: "Ich fühle mich anderen rlegen." },
      reversed: true,
    },
    {
      id: 47,
      dimension: "A",
      aspect: "politeness",
      text: "Nem szeretnék tolakodónak tűnni.",
      textByLocale: { hu: "Nem szeretnék tolakodónak tűnni.", en: "Hate to seem pushy.", de: "s ist mir unangenehm, dringlich zu erscheinen." },
    },
    {
      id: 48,
      dimension: "N",
      aspect: "withdrawal",
      text: "Jól érzem magam a bőrömben.",
      textByLocale: { hu: "Jól érzem magam a bőrömben.", en: "Feel comfortable with myself.", de: "Ich bin mit mir zufrieden." },
      reversed: true,
    },
    {
      id: 49,
      dimension: "C",
      aspect: "industriousness",
      text: "Vesztegetem az időmet.",
      textByLocale: { hu: "Vesztegetem az időmet.", en: "Waste my time.", de: "Ich verschwende meine Zeit." },
      reversed: true,
    },
    {
      id: 50,
      dimension: "O",
      aspect: "intellect",
      text: "Gazdag a szókincsem.",
      textByLocale: { hu: "Gazdag a szókincsem.", en: "Have a rich vocabulary.", de: "Ich habe einen reichen Wortschatz." },
    },
    {
      id: 51,
      dimension: "O",
      aspect: "openness",
      text: "Ritkán veszem észre a festmények és képek érzelmi vonatkozásait.",
      textByLocale: { hu: "Ritkán veszem észre a festmények és képek érzelmi vonatkozásait.", en: "Seldom notice the emotional aspects of paintings and pictures.", de: "he Gemälde oder Fotografien ects berühren mich nicht. and" },
      reversed: true,
    },
    {
      id: 52,
      dimension: "A",
      aspect: "compassion",
      text: "Szeretek másokért tenni.",
      textByLocale: { hu: "Szeretek másokért tenni.", en: "Like to do things for others.", de: "Es bereitet mir Freude, etwas für andere zu tun." },
    },
    {
      id: 53,
      dimension: "C",
      aspect: "industriousness",
      text: "Megvalósítom a terveimet.",
      textByLocale: { hu: "Megvalósítom a terveimet.", en: "Carry out my plans.", de: "Ich führe meine Vorhaben durch." },
    },
    {
      id: 54,
      dimension: "A",
      aspect: "politeness",
      text: "Tisztelem a tekintélyt.",
      textByLocale: { hu: "Tisztelem a tekintélyt.", en: "Respect authority.", de: "Ich respektiere Autoritäten." },
    },
    {
      id: 55,
      dimension: "A",
      aspect: "compassion",
      text: "Nem foglalkozom mások szükségleteivel.",
      textByLocale: { hu: "Nem foglalkozom mások szükségleteivel.", en: "Can't be bothered with other's needs.", de: "Die Belange anderer schen interessieren mich nicht." },
      reversed: true,
    },
    {
      id: 56,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Kimutatom az érzéseimet, amikor boldog vagyok.",
      textByLocale: { hu: "Kimutatom az érzéseimet, amikor boldog vagyok.", en: "Show my feelings when I'm happy.", de: "Wenn ich glücklich bin, dann ge ich das auch." },
    },
    {
      id: 57,
      dimension: "E",
      aspect: "assertiveness",
      text: "Erős egyéniség vagyok.",
      textByLocale: { hu: "Erős egyéniség vagyok.", en: "Have a strong personality.", de: "Ich habe eine starke Persönlichkeit." },
    },
    {
      id: 58,
      dimension: "E",
      aspect: "assertiveness",
      text: "Tudom, hogyan bűvöljem el az embereket.",
      textByLocale: { hu: "Tudom, hogyan bűvöljem el az embereket.", en: "Know how to captivate people.", de: "Ich kann andere faszinieren. ." },
    },
    {
      id: 59,
      dimension: "C",
      aspect: "industriousness",
      text: "Befejezem, amit elkezdek.",
      textByLocale: { hu: "Befejezem, amit elkezdek.", en: "Finish what I start.", de: ". Was ich beginne, bringe ich auch zu Ende." },
    },
    {
      id: 60,
      dimension: "C",
      aspect: "orderliness",
      text: "Rendben tartom a dolgaimat.",
      textByLocale: { hu: "Rendben tartom a dolgaimat.", en: "Keep things tidy.", de: "Ich räume meine Sachen stets auf." },
    },
    {
      id: 61,
      dimension: "O",
      aspect: "intellect",
      text: "Kerülöm a filozófiai beszélgetéseket.",
      textByLocale: { hu: "Kerülöm a filozófiai beszélgetéseket.", en: "Avoid philosophical discussions.", de: "l Ich vermeide philosophische Diskussionen." },
      reversed: true,
    },
    {
      id: 62,
      dimension: "N",
      aspect: "volatility",
      text: "Ritkán leszek ingerült.",
      textByLocale: { hu: "Ritkán leszek ingerült.", en: "Rarely get irritated.", de: "d. Ich bin selten irritiert." },
      reversed: true,
    },
    {
      id: 63,
      dimension: "A",
      aspect: "compassion",
      text: "Átélem mások érzelmeit.",
      textByLocale: { hu: "Átélem mások érzelmeit.", en: "Feel others' emotions.", de: "Ich habe ein Gespür für die Gefühle anderer." },
    },
    {
      id: 64,
      dimension: "C",
      aspect: "orderliness",
      text: "Tartom magam az időbeosztáshoz.",
      textByLocale: { hu: "Tartom magam az időbeosztáshoz.", en: "Follow a schedule.", de: "Ich halte mich an Zeitpläne." },
    },
    {
      id: 65,
      dimension: "C",
      aspect: "orderliness",
      text: "Nem zavar a rendetlenség.",
      textByLocale: { hu: "Nem zavar a rendetlenség.", en: "Am not bothered by disorder.", de: "Unordnung stört mich nicht. Le dé" },
      reversed: true,
    },
    {
      id: 66,
      dimension: "O",
      aspect: "intellect",
      text: "Szeretek összetett problémákat megoldani.",
      textByLocale: { hu: "Szeretek összetett problémákat megoldani.", en: "Like to solve complex problems.", de: "Es bereitet mir Freude, komplexe Probleme zu lösen." },
    },
    {
      id: 67,
      dimension: "O",
      aspect: "openness",
      text: "Olyan dolgokban is észreveszem a szépséget, amit mások talán nem.",
      textByLocale: { hu: "Olyan dolgokban is észreveszem a szépséget, amit mások talán nem.", en: "See beauty in things that others might not notice.", de: "hings In manchen Dingen sehe ich t etwas Schönes, das anderen verborgen bleibt." },
    },
    {
      id: 68,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Sokszor jól szórakozom.",
      textByLocale: { hu: "Sokszor jól szórakozom.", en: "Have a lot of fun.", de: "Ich habe viel Spass." },
    },
    {
      id: 69,
      dimension: "N",
      aspect: "withdrawal",
      text: "Könnyen elárasztanak az események.",
      textByLocale: { hu: "Könnyen elárasztanak az események.", en: "Become overwhelmed by events.", de: "Manchmal ist mir alles zu viel." },
    },
    {
      id: 70,
      dimension: "N",
      aspect: "volatility",
      text: "Gyakran változik a hangulatom.",
      textByLocale: { hu: "Gyakran változik a hangulatom.", en: "Change my mood a lot.", de: "ine Stimmung ändert sich nge häufig." },
    },
    {
      id: 71,
      dimension: "N",
      aspect: "volatility",
      text: "Könnyen dühbe gurulok.",
      textByLocale: { hu: "Könnyen dühbe gurulok.", en: "Get angry easily.", de: "Ich werde schnell ärgerlich." },
    },
    {
      id: 72,
      dimension: "N",
      aspect: "withdrawal",
      text: "Sok mindentől félek.",
      textByLocale: { hu: "Sok mindentől félek.", en: "Am afraid of many things.", de: "Ich sorge mich über viele Dinge." },
    },
    {
      id: 73,
      dimension: "C",
      aspect: "orderliness",
      text: "Szeretem a rendet.",
      textByLocale: { hu: "Szeretem a rendet.", en: "Like order.", de: "Ich mag Ordnung." },
    },
    {
      id: 74,
      dimension: "E",
      aspect: "assertiveness",
      text: "Én szoktam elsőként cselekedni.",
      textByLocale: { hu: "Én szoktam elsőként cselekedni.", en: "Am the first to act.", de: "Ich übernehme häufig die initiative." },
    },
    {
      id: 75,
      dimension: "E",
      aspect: "assertiveness",
      text: "Átveszem az irányítást.",
      textByLocale: { hu: "Átveszem az irányítást.", en: "Take charge.", de: "Ich übernehme Verantwortung." },
    },
    {
      id: 76,
      dimension: "O",
      aspect: "openness",
      text: "Ritkán merülök el a gondolataimban.",
      textByLocale: { hu: "Ritkán merülök el a gondolataimban.", en: "Seldom get lost in thought.", de: "in Es passiert selten, dass ich meinen Gedanken nachhänge." },
      reversed: true,
    },
    {
      id: 77,
      dimension: "N",
      aspect: "volatility",
      text: "Ritkán vesztem el a nyugalmam.",
      textByLocale: { hu: "Ritkán vesztem el a nyugalmam.", en: "Rarely lose my composure.", de: "Es kommt selten vor, dass ich Fassung verliere." },
      reversed: true,
    },
    {
      id: 78,
      dimension: "A",
      aspect: "politeness",
      text: "Kerülöm, hogy ráerőltessem az akaratom másokra.",
      textByLocale: { hu: "Kerülöm, hogy ráerőltessem az akaratom másokra.", en: "Avoid imposing my will on others.", de: "vermeide es, anderen ' meinen Willen aufzuzwingen." },
    },
    {
      id: 79,
      dimension: "O",
      aspect: "openness",
      text: "Szükségem van kreatív levezetésre.",
      textByLocale: { hu: "Szükségem van kreatív levezetésre.", en: "Need a creative outlet.", de: "Ich muss mich kreativ betätigen." },
    },
    {
      id: 80,
      dimension: "C",
      aspect: "orderliness",
      text: "Want everything to be \"just right\".",
      textByLocale: { hu: "Azt akarom, hogy minden „pont jó” legyen.", en: "Want everything to be \"just right\".", de: "Ich wünsche mir, dass alles perfekt ist." },
    },
    {
      id: 81,
      dimension: "O",
      aspect: "openness",
      text: "Szeretek elgondolkodni a dolgokon.",
      textByLocale: { hu: "Szeretek elgondolkodni a dolgokon.", en: "Love to reflect on things.", de: "on Es bereitet mir Freude, über die Dinge nachzudenken." },
    },
    {
      id: 82,
      dimension: "O",
      aspect: "intellect",
      text: "Kerülöm a nehéz olvasmányokat.",
      textByLocale: { hu: "Kerülöm a nehéz olvasmányokat.", en: "Avoid difficult reading material.", de: "Ich vermeide schwierigen l. Lesestoff." },
      reversed: true,
    },
    {
      id: 83,
      dimension: "C",
      aspect: "industriousness",
      text: "Nem a rám váró feladatra koncentrálok.",
      textByLocale: { hu: "Nem a rám váró feladatra koncentrálok.", en: "Don't put my mind on the task at hand.", de: "anchmal bin ich mit meinen 'arr Gedanken nicht bei der Sache." },
      reversed: true,
    },
    {
      id: 84,
      dimension: "E",
      aspect: "assertiveness",
      text: "Visszafogom a véleményemet.",
      textByLocale: { hu: "Visszafogom a véleményemet.", en: "Hold back my opinions.", de: "Ich halte mich mit meiner Meinung eher zurück." },
      reversed: true,
    },
    {
      id: 85,
      dimension: "C",
      aspect: "orderliness",
      text: "Azt akarom, hogy minden apró részlet rendben legyen.",
      textByLocale: { hu: "Azt akarom, hogy minden apró részlet rendben legyen.", en: "Want every detail taken care of.", de: "Ich lege grossen Wert auf details." },
    },
    {
      id: 86,
      dimension: "O",
      aspect: "intellect",
      text: "Gyorsan megértek dolgokat.",
      textByLocale: { hu: "Gyorsan megértek dolgokat.", en: "Am quick to understand things.", de: "Ich habe eine gute gs. Auffassungsgabe." },
    },
    {
      id: 87,
      dimension: "O",
      aspect: "openness",
      text: "Élvezem a természet szépségét.",
      textByLocale: { hu: "Élvezem a természet szépségét.", en: "Enjoy the beauty of nature.", de: "f Es bereitet mir Freude, die Schönheit der Natur zu geniessen." },
    },
    {
      id: 88,
      dimension: "N",
      aspect: "withdrawal",
      text: "Aggódom dolgok miatt.",
      textByLocale: { hu: "Aggódom dolgok miatt.", en: "Worry about things.", de: ". Ich mache mir häufig Sorgen." },
    },
    {
      id: 89,
      dimension: "A",
      aspect: "compassion",
      text: "Érdeklődöm mások hogyléte felől.",
      textByLocale: { hu: "Érdeklődöm mások hogyléte felől.", en: "Inquire about others' well-being.", de: "Ich erkundige mich nach dem 'i Wohlbefinden anderer." },
    },
    {
      id: 90,
      dimension: "O",
      aspect: "openness",
      text: "Mélyen elmerülök a zenében.",
      textByLocale: { hu: "Mélyen elmerülök a zenében.", en: "Get deeply immersed in music.", de: "Ich gehe manchmal völlig in einer Musik auf, die ich höre." },
    },
    {
      id: 91,
      dimension: "A",
      aspect: "politeness",
      text: "Keresem a konfliktust.",
      textByLocale: { hu: "Keresem a konfliktust.", en: "Seek conflict.", de: "Ich suche Streit." },
      reversed: true,
    },
    {
      id: 92,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Távolságot tartok másoktól.",
      textByLocale: { hu: "Távolságot tartok másoktól.", en: "Keep others at a distance.", de: "Ich halte andere auf Distanz." },
      reversed: true,
    },
    {
      id: 93,
      dimension: "C",
      aspect: "industriousness",
      text: "Elrontok dolgokat.",
      textByLocale: { hu: "Elrontok dolgokat.", en: "Mess things up.", de: "Manche Dinge vermassele ich fach." },
      reversed: true,
    },
    {
      id: 94,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Ritkán kap el a lelkesedés.",
      textByLocale: { hu: "Ritkán kap el a lelkesedés.", en: "Rarely get caught up in the excitement.", de: "p Ich lasse mich nicht durch den . Trubel der Ereignisse mitreissen." },
      reversed: true,
    },
    {
      id: 95,
      dimension: "A",
      aspect: "compassion",
      text: "Nem szánok időt másokra.",
      textByLocale: { hu: "Nem szánok időt másokra.", en: "Take no time for others.", de: "Ich nehme mir keine Zeit für andere." },
      reversed: true,
    },
    {
      id: 96,
      dimension: "N",
      aspect: "volatility",
      text: "Nem lehet könnyen felbosszantani.",
      textByLocale: { hu: "Nem lehet könnyen felbosszantani.", en: "Am not easily annoyed.", de: "Ich bin nicht schnell verärgert" },
      reversed: true,
    },
    {
      id: 97,
      dimension: "O",
      aspect: "openness",
      text: "Ritkán ábrándozom.",
      textByLocale: { hu: "Ritkán ábrándozom.", en: "Seldom daydream.", de: ". Es kommt selten vor, dass ich Tagträumen nachgehe." },
      reversed: true,
    },
    {
      id: 98,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Könnyen szerzek barátokat.",
      textByLocale: { hu: "Könnyen szerzek barátokat.", en: "Make friends easily.", de: ". Es fällt mir leicht, neue Freundschaften zu schliessen." },
    },
    {
      id: 99,
      dimension: "O",
      aspect: "intellect",
      text: "Sok információt képes vagyok kezelni.",
      textByLocale: { hu: "Sok információt képes vagyok kezelni.", en: "Can handle a lot of information.", de: "f Ich kann mit einer grossen Menge an informationen umgehen." },
    },
    {
      id: 100,
      dimension: "A",
      aspect: "politeness",
      text: "Kihasználok másokat.",
      textByLocale: { hu: "Kihasználok másokat.", en: "Take advantage of others.", de: "Ich nutze andere aus." },
      reversed: true,
    },
    **/
  ],
};
