import type { TestConfig } from "./types";

/**
 * Big Five / OCEAN personality test (BFAS — Big Five Aspect Scales)
 * Questions sourced from the Big Five Aspect Scales (BFAS) — 100 items, 5 domains × 2 aspects × 10 items.
 */
export const big5Config: TestConfig = {
  type: "BIG_FIVE",
  name: "Big Five",
  description: "Az öt nagy személyiségvonás (OCEAN) mérése.",
  format: "likert",
  dimensions: [
    {
      code: "O",
      label: "Nyitottság",
      labelByLocale: {
        en: "Openness",
        de: "Offenheit",
      },
      color: "#38BDF8",
      description: "A nyitottság a kreativitás, az intellektuális kíváncsiság és az esztétikai érzékenység alapdimenziója. Azt tükrözi, mennyire vonzódik valaki az új ötletekhez, a képzelethez, az elvont gondolkodáshoz és a művészeti élményekhez. Két aspektusa az Intellektus (elméleti gondolkodás, problémamegoldás, szellemi kihívások iránti igény) és az Esztétikai nyitottság (képzelet, művészi fogékonyság, a szépség és az érzelmi mélység megbecsülése).",
      descriptionByLocale: {
        en: "Openness is the core dimension of creativity, intellectual curiosity, and aesthetic sensitivity. It reflects how strongly a person is drawn to new ideas, imagination, abstract thinking, and artistic experience. Its two aspects are Intellect (theoretical reasoning, problem-solving, enjoyment of intellectual challenges) and Aesthetic Openness (imagination, artistic sensitivity, appreciation for beauty and emotional depth).",
        de: "Offenheit ist die Kerndimension von Kreativität, intellektueller Neugier und ästhetischer Empfindsamkeit. Sie zeigt, wie stark jemand zu neuen Ideen, Vorstellungskraft, abstraktem Denken und künstlerischen Erfahrungen neigt. Ihre zwei Aspekte sind Intellekt (theoretisches Denken, Problemlösung, Freude an intellektuellen Herausforderungen) und Ästhetische Offenheit (Vorstellungskraft, künstlerische Sensibilität, Wertschätzung von Schönheit und emotionaler Tiefe).",
      },
      insights: {
        low: "Inkább a bevált, hagyományos megközelítéseket részesíted előnyben. A konkrét, praktikus gondolkodás jellemez, és jól teljesítesz strukturált, kiszámítható környezetben.",
        mid: "A kreativitást és a realizmust egyensúlyban tartod. Nyitott vagy az újszerű ötletekre, de a praktikus szempontokat is figyelembe veszed – ez segít stabil fókuszt és szakértelmet kialakítani.",
        high: "Kíváncsi, képzeletgazdag és reflektív gondolkodásmód jellemez. Az elvont fogalmak, szellemi kihívások és szokatlan megközelítések vonzanak. A tanulás maga is céllá válik, nem csupán eszközzé.",
      },
      insightsByLocale: {
        en: {
          low: "You tend to prefer familiar, traditional approaches. Concrete and practical thinking suits you well, and you perform strongly in structured, predictable environments.",
          mid: "You balance creativity with realism. Open to new ideas while staying grounded in practical matters—a combination that supports stable focus and the development of expertise.",
          high: "Curious, imaginative, and reflective—you are drawn to abstract concepts, intellectual challenges, and unconventional ideas. Learning itself becomes a goal, not just a means.",
        },
        de: {
          low: "Du bevorzugst vertraute, traditionelle Ansätze. Konkretes und praktisches Denken liegt dir, und du arbeitest gut in strukturierten, berechenbaren Umgebungen.",
          mid: "Du balancierst Kreativität mit Realismus. Offen für neue Ideen, verlierst aber den praktischen Boden nicht – eine Kombination, die stabile Fokussierung und Fachkompetenz fördert.",
          high: "Neugierig, einfallsreich und reflektierend – du wirst von abstrakten Konzepten, intellektuellen Herausforderungen und unkonventionellen Ideen angezogen. Das Lernen selbst wird zum Ziel, nicht nur zum Mittel.",
        },
      },
      aspects: [
        { code: "intellect", label: "Intellektus", labelByLocale: { en: "Intellect", de: "Intellekt" } },
        { code: "openness", label: "Nyitottság", labelByLocale: { en: "Openness", de: "Offenheit" } },
      ],
    },
    {
      code: "C",
      label: "Lelkiismeretesség",
      labelByLocale: {
        en: "Conscientiousness",
        de: "Gewissenhaftigkeit",
      },
      color: "#A78BFA",
      description: "A lelkiismeretesség az önfegyelem, a szervezettség és a célirányos viselkedés alapdimenziója. Azt méri, mennyire következetesen teljesíti valaki a kötelezettségeit, tartja be a terveit és viseli a felelősséget. Két aspektusa a Szorgalom (munkamorál, kitartás, ambíció, célok elérésére irányuló hajtóerő) és a Rendszeresség (szervezettség, struktúraigény, szabálykövetés).",
      descriptionByLocale: {
        en: "Conscientiousness is the primary dimension of self-discipline, organization, and goal-directed behavior. It measures how reliably someone fulfills responsibilities, follows plans, and maintains accountability. Its two aspects are Industriousness (work ethic, persistence, ambition, drive to achieve) and Orderliness (organization, preference for structure, rule-following).",
        de: "Gewissenhaftigkeit ist die Kerndimension von Selbstdisziplin, Organisation und zielgerichtetem Verhalten. Sie misst, wie zuverlässig jemand Verpflichtungen erfüllt, Pläne verfolgt und Verantwortung übernimmt. Ihre zwei Aspekte sind Fleiß (Arbeitsmoral, Ausdauer, Ehrgeiz, Antrieb zum Erreichen von Zielen) und Ordentlichkeit (Organisation, Strukturbedürfnis, Regelkonformität).",
      },
      insights: {
        low: "Spontánabb, rugalmasabb megközelítés jellemez. Kevésbé ragaszkodsz rögzített tervekhez és struktúrákhoz, ami változékony helyzetekben alkalmazkodóképességednek kedvez.",
        mid: "Megbízható vagy a feladatok elvégzésében, és rugalmasan alkalmazkodsz a változásokhoz is. Tudsz terveket követni anélkül, hogy egyetlen megközelítéshez ragaszkodnál.",
        high: "Rendszerezett, következetes és felelősségteljes. Külső kontroll nélkül is megbízhatóan teljesítesz, elvállalod a felelősséget a hibáidért, és magas mércét állítasz magad elé. A hosszú távú tervezés és a kitartó végrehajtás az erősséged.",
      },
      insightsByLocale: {
        en: {
          low: "A more spontaneous and flexible approach characterizes you. You prefer fewer fixed plans and structures, which supports adaptability in changing situations.",
          mid: "You are reliable in completing tasks while adapting flexibly to change. You can follow plans without rigidly committing to a single approach.",
          high: "Structured, consistent, and highly accountable. You perform reliably without external oversight, take responsibility for mistakes, and hold yourself to high standards. Long-term planning and persistent execution are your strengths.",
        },
        de: {
          low: "Eine spontanere, flexiblere Herangehensweise kennzeichnet dich. Du bevorzugst weniger starre Pläne, was deine Anpassungsfähigkeit in wechselnden Situationen stärkt.",
          mid: "Du bist zuverlässig bei der Aufgabenerfüllung und passt dich flexibel an Veränderungen an. Du kannst Pläne verfolgen, ohne dich starr auf eine einzige Vorgehensweise festzulegen.",
          high: "Strukturiert, konsequent und verantwortungsbewusst. Du arbeitest zuverlässig ohne externe Kontrolle, übernimmst Verantwortung für Fehler und setzt dir hohe Maßstäbe. Langfristige Planung und beharrliche Umsetzung sind deine Stärken.",
        },
      },
      aspects: [
        { code: "industriousness", label: "Szorgalom", labelByLocale: { en: "Industriousness", de: "Fleiß" } },
        { code: "orderliness", label: "Rendszeresség", labelByLocale: { en: "Orderliness", de: "Ordentlichkeit" } },
      ],
    },
    {
      code: "E",
      label: "Extraverzió",
      labelByLocale: {
        en: "Extraversion",
        de: "Extraversion",
      },
      color: "#F59E0B",
      description: "Az extraverzió a külvilággal való kapcsolódás és a pozitív érzelmek megélésének alapdimenziója. Két aspektusa a Lelkesedés (melegség, szociabilitás, a pozitív érzelmek kapacitása) és a Magabiztosság (kezdeményezőkészség, vezető szerep, dominancia társas helyzetekben). Az alacsony extraverzió nem jelent félénkséget vagy szociális szorongást – az introvertált emberek egyszerűen másképp töltik fel az energiájukat.",
      descriptionByLocale: {
        en: "Extraversion is the core dimension of engagement with the external world and the experience of positive emotion. Its two aspects are Enthusiasm (warmth, sociability, capacity for positive emotion) and Assertiveness (initiative, leadership tendency, dominance in social settings). Low extraversion does not imply shyness or social anxiety—introverted people simply recharge differently.",
        de: "Extraversion ist die Kerndimension der Weltgewandtheit und des Erlebens positiver Emotionen. Ihre zwei Aspekte sind Begeisterung (Wärme, Geselligkeit, Fähigkeit zu positiven Emotionen) und Durchsetzungsvermögen (Initiative, Führungsneigung, Dominanz in sozialen Situationen). Niedrige Extraversion bedeutet nicht Schüchternheit oder soziale Angst – introvertierte Menschen laden ihre Energie einfach anders auf.",
      },
      insights: {
        low: "Inkább introvertált: az egyedüllét, a kisebb társaságok és az alacsonyabb ingerszint illik hozzád. Kevesebb külső impulzusra van szükséged ahhoz, hogy feltöltötten érezd magad.",
        mid: "Kiegyensúlyozott társas energia: tudsz vezető szerepet vállalni és aktívan részt venni közösségi helyzetekben, de a fókuszált, egyéni tevékenységeket is értékeled.",
        high: "Energikus, társaságkedvelő és magabiztos társas helyzetekben. Aktívan keresed az ingereket, mások jelenlétéből töltekezel, és természetesen veszed fel a vezető szerepet.",
      },
      insightsByLocale: {
        en: {
          low: "More introverted: you feel most at ease in solitude, smaller groups, or lower-stimulation environments. You need less external input to feel energized.",
          mid: "Balanced social energy: you can take on leadership roles and engage actively in social settings while also valuing focused, independent work.",
          high: "Energetic, sociable, and confident in social settings. You actively seek stimulation, are energized by others' presence, and naturally gravitate toward leadership roles.",
        },
        de: {
          low: "Eher introvertiert: du fühlst dich in Ruhe, kleineren Gruppen oder reizärmeren Umgebungen am wohlsten. Du brauchst weniger externe Impulse, um dich energiegeladen zu fühlen.",
          mid: "Ausgewogene soziale Energie: du kannst Führungsrollen übernehmen und in sozialen Situationen aktiv mitmachen, schätzt aber auch fokussiertes, eigenständiges Arbeiten.",
          high: "Energisch, gesellig und selbstbewusst in sozialen Situationen. Du suchst aktiv Stimulation, tankst in Gesellschaft auf und übernimmst auf natürliche Weise Führungsrollen.",
        },
      },
      aspects: [
        { code: "enthusiasm", label: "Lelkesedés", labelByLocale: { en: "Enthusiasm", de: "Begeisterung" } },
        { code: "assertiveness", label: "Magabiztosság", labelByLocale: { en: "Assertiveness", de: "Durchsetzungsvermögen" } },
      ],
    },
    {
      code: "A",
      label: "Barátságosság",
      labelByLocale: {
        en: "Agreeableness",
        de: "Verträglichkeit",
      },
      color: "#34D399",
      description: "A barátságosság az együttműködési hajlandóságot, az empátiát és a társas harmónia iránti igényt tükrözi. Két aspektusa az Együttérzés (empátia, mások érzelmi szükségleteire való érzékenység) és az Udvariasság (tisztelet, az agresszív impulzusok gátlása, mások nem kihasználása). Az alacsony barátságosság nem feltétlenül negatív – határozott, kritikus gondolkodással és az önérdek asszertív képviseletével járhat együtt.",
      descriptionByLocale: {
        en: "Agreeableness reflects orientation toward cooperation, empathy, and social harmony. Its two aspects are Compassion (empathy, sensitivity to others' emotional needs) and Politeness (respectfulness, inhibition of aggression, not taking advantage of others). Lower agreeableness is not inherently negative—it can accompany critical thinking and assertive boundary-setting.",
        de: "Verträglichkeit spiegelt die Bereitschaft zur Zusammenarbeit, Empathie und den Wunsch nach sozialem Miteinander wider. Ihre zwei Aspekte sind Mitgefühl (Empathie, Sensibilität für die emotionalen Bedürfnisse anderer) und Höflichkeit (Respekt, Hemmung aggressiver Impulse, kein Ausnutzen anderer). Niedrige Verträglichkeit ist nicht grundsätzlich negativ – sie kann mit kritischem Denken und selbstbewusstem Setzen von Grenzen einhergehen.",
      },
      insights: {
        low: "Határozott és kritikus gondolkodásmód jellemez. Nem félsz a konfrontációtól, és hajlamos vagy megvédeni az álláspontodat – ami kritikus ítéletet igénylő helyzetekben komoly erőforrás.",
        mid: "Rugalmasan együttműködsz másokkal, de képes vagy megvédeni a saját álláspontodat is. Egyensúlyt tartasz az empátia és a határozott fellépés között.",
        high: "Erős együttműködési készség, empátia és törekvés a harmóniára jellemez. Megbocsátó természetű vagy, könnyen kompromisszumot kötsz, és konfliktusos helyzetekben is az összhangot keresed.",
      },
      insightsByLocale: {
        en: {
          low: "Decisive and critical in your thinking. You are not afraid of confrontation and tend to defend your position—a valuable trait in situations requiring firm judgment.",
          mid: "You cooperate flexibly while still defending your own position when needed. You maintain a balance between empathy and assertiveness.",
          high: "Strong cooperative spirit, empathy, and a drive toward harmony. You are forgiving, reach compromises readily, and seek common ground even in conflict.",
        },
        de: {
          low: "Entschlossen und kritisch im Denken. Du scheust keine Konfrontation und neigst dazu, deinen Standpunkt zu vertreten – eine wertvolle Eigenschaft in Situationen, die klare Urteile erfordern.",
          mid: "Du kooperierst flexibel und kannst trotzdem deinen eigenen Standpunkt vertreten. Du hältst die Balance zwischen Empathie und Durchsetzungsvermögen.",
          high: "Starke Kooperationsbereitschaft, Empathie und Streben nach Harmonie. Du bist verzeihend, findest leicht Kompromisse und suchst auch in Konflikten nach Gemeinsamkeiten.",
        },
      },
      aspects: [
        { code: "compassion", label: "Együttérzés", labelByLocale: { en: "Compassion", de: "Mitgefühl" } },
        { code: "politeness", label: "Udvariasság", labelByLocale: { en: "Politeness", de: "Höflichkeit" } },
      ],
    },
    {
      code: "N",
      label: "Neuroticizmus",
      labelByLocale: {
        en: "Neuroticism",
        de: "Neurotizismus",
      },
      color: "#FB7185",
      inverted: true,
      description: "A neuroticizmus a negatív érzelmi reaktivitás és a stresszérzékenység alapdimenziója. Azt mutatja, mennyire erősen reagál valaki a fenyegetésekre, bizonytalanságra és kihívásokra. Két aspektusa a Visszahúzódás (szorongás, szomorúság, öntudat, sebezhetőség) és a Változékonyság (ingerlékenység, düh, érzelmi reaktivitás). Minél alacsonyabb az érték, annál nagyobb az érzelmi stabilitás és ellenállóképesség.",
      descriptionByLocale: {
        en: "Neuroticism is the core dimension of negative emotional reactivity and sensitivity to stress. It reflects how strongly a person responds to perceived threats, uncertainty, and challenges. Its two aspects are Withdrawal (anxiety, sadness, self-consciousness, vulnerability) and Volatility (irritability, anger, emotional reactivity). Lower scores indicate greater emotional stability and resilience.",
        de: "Neurotizismus ist die Kerndimension negativer emotionaler Reaktivität und Stressempfindlichkeit. Er zeigt, wie stark jemand auf wahrgenommene Bedrohungen, Unsicherheit und Herausforderungen reagiert. Seine zwei Aspekte sind Rückzug (Angst, Traurigkeit, Selbstbewusstsein, Verletzlichkeit) und Volatilität (Reizbarkeit, Ärger, emotionale Reaktivität). Niedrigere Werte stehen für größere emotionale Stabilität und Widerstandsfähigkeit.",
      },
      insights: {
        low: "Érzelmileg stabil és ellenálló: ritkán tapasztalsz intenzív negatív érzelmeket, és nyomás alatt is megőrzöd a nyugalmad. Ez az érzelmi egyensúly komoly erőforrás a mindennapokban.",
        mid: "Általában kiegyensúlyozott és stabil, de nagyobb kihívások vagy bizonytalanság esetén fokozottabb érzelmi érzékenység is megjelenik. Ez az egyensúly a legtöbb hétköznapi helyzetben jól működik.",
        high: "Intenzívebb érzelmi reakciókat tapasztalsz, különösen stressz, bizonytalanság vagy kihívások esetén. Ez fokozott érzékenységgel és önreflexióval járhat, ami bizonyos környezetekben – például empatikus vagy kreatív munkában – értékes lehet.",
      },
      insightsByLocale: {
        en: {
          low: "Emotionally stable and resilient: you rarely experience intense negative emotions and tend to maintain calm under pressure. This emotional equilibrium is a significant strength in everyday life.",
          mid: "Generally balanced and stable, with increased emotional sensitivity emerging in more challenging or uncertain situations. This balance works well in most everyday contexts.",
          high: "You experience more intense emotional reactions, especially under stress, uncertainty, or when facing challenges. This comes with heightened sensitivity and self-reflection, which can be valuable in empathic, creative, or detail-oriented contexts.",
        },
        de: {
          low: "Emotional stabil und widerstandsfähig: Du erlebst selten intensive negative Emotionen und bewahrst auch unter Druck die Ruhe. Dieses emotionale Gleichgewicht ist eine bedeutende Stärke im Alltag.",
          mid: "Generell ausgeglichen und stabil, mit erhöhter emotionaler Empfindlichkeit in herausfordernden oder unsicheren Situationen. Dieses Gleichgewicht funktioniert in den meisten alltäglichen Kontexten gut.",
          high: "Du erlebst intensivere emotionale Reaktionen, besonders unter Stress, Unsicherheit oder bei Herausforderungen. Dies geht mit erhöhter Sensibilität und Selbstreflexion einher, was in empathischen, kreativen oder detailorientierten Kontexten wertvoll sein kann.",
        },
      },
      aspects: [
        { code: "withdrawal", label: "Visszahúzódás", labelByLocale: { en: "Withdrawal", de: "Rückzug" } },
        { code: "volatility", label: "Változékonyság", labelByLocale: { en: "Volatility", de: "Volatilität" } },
      ],
    },
  ],
  questions: [
    {
      id: 1,
      dimension: "N",
      aspect: "withdrawal",
      text: "Seldom feel blue.",
      textByLocale: { hu: "Ritkán érzem magam rosszkedvűnek.", en: "Seldom feel blue.", de: "Ich bin selten deprimiert." },
      textObserver: "He/She seldom feels blue.",
      textObserverByLocale: { hu: "Ritkán érzi magát rosszkedvűnek.", en: "He/She seldom feels blue.", de: "Er/Sie ist selten deprimiert." },
      reversed: true,
    },
    {
      id: 2,
      dimension: "A",
      aspect: "compassion",
      text: "Am not interested in other people's problems.",
      textByLocale: { hu: "Nem érdekelnek mások problémái.", en: "Am not interested in other people's problems.", de: "Ich interessiere mich nicht für die Probleme anderer." },
      textObserver: "He/She is not interested in other people's problems.",
      textObserverByLocale: { hu: "Nem érdeklik mások problémái.", en: "He/She is not interested in other people's problems.", de: "Er/Sie interessiert sich nicht für die Probleme anderer." },
      reversed: true,
    },
    {
      id: 3,
      dimension: "C",
      aspect: "industriousness",
      text: "Carry out my plans.",
      textByLocale: { hu: "Véghezviszem, amit elterveztem.", en: "Carry out my plans.", de: "Ich führe meine Vorhaben durch." },
      textObserver: "He/She carries out his/her plans.",
      textObserverByLocale: { hu: "Véghezviszi, amit eltervezett.", en: "He/She carries out his/her plans.", de: "Er/Sie führt seine/ihre Vorhaben durch." },
    },
    {
      id: 4,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Make friends easily.",
      textByLocale: { hu: "Könnyen szerzek barátokat.", en: "Make friends easily.", de: "Es fällt mir leicht, neue Freundschaften zu schließen." },
      textObserver: "He/She makes friends easily.",
      textObserverByLocale: { hu: "Könnyen szerez barátokat.", en: "He/She makes friends easily.", de: "Es fällt ihm/ihr leicht, neue Freundschaften zu schließen." },
    },
    {
      id: 5,
      dimension: "O",
      aspect: "intellect",
      text: "Am quick to understand things.",
      textByLocale: { hu: "Gyorsan megértem a dolgokat.", en: "Am quick to understand things.", de: "Ich habe eine gute Auffassungsgabe." },
      textObserver: "He/She is quick to understand things.",
      textObserverByLocale: { hu: "Gyorsan megérti a dolgokat.", en: "He/She is quick to understand things.", de: "Er/Sie hat eine gute Auffassungsgabe." },
    },
    {
      id: 6,
      dimension: "N",
      aspect: "volatility",
      text: "Get angry easily.",
      textByLocale: { hu: "Könnyen dühbe gurulok.", en: "Get angry easily.", de: "Ich werde schnell ärgerlich." },
      textObserver: "He/She gets angry easily.",
      textObserverByLocale: { hu: "Könnyen dühbe gurul.", en: "He/She gets angry easily.", de: "Er/Sie wird schnell ärgerlich." },
    },
    {
      id: 7,
      dimension: "A",
      aspect: "politeness",
      text: "Respect authority.",
      textByLocale: { hu: "Tisztelem a tekintélyt.", en: "Respect authority.", de: "Ich respektiere Autoritäten." },
      textObserver: "He/She respects authority.",
      textObserverByLocale: { hu: "Tiszteli a tekintélyt.", en: "He/She respects authority.", de: "Er/Sie respektiert Autoritäten." },
    },
    {
      id: 8,
      dimension: "C",
      aspect: "orderliness",
      text: "Leave my belongings around.",
      textByLocale: { hu: "Szanaszét hagyom a holmijaimat.", en: "Leave my belongings around.", de: "Ich lasse meine Sachen herumliegen." },
      textObserver: "He/She leaves his/her belongings around.",
      textObserverByLocale: { hu: "Szanaszét hagyja a holmijait.", en: "He/She leaves his/her belongings around.", de: "Er/Sie lässt seine/ihre Sachen herumliegen." },
      reversed: true,
    },
    {
      id: 9,
      dimension: "E",
      aspect: "assertiveness",
      text: "Take charge.",
      textByLocale: { hu: "Átveszem a vezetést.", en: "Take charge.", de: "Ich übernehme Verantwortung." },
      textObserver: "He/She takes charge.",
      textObserverByLocale: { hu: "Átveszi a vezetést.", en: "He/She takes charge.", de: "Er/Sie übernimmt Verantwortung." },
    },
    {
      id: 10,
      dimension: "O",
      aspect: "openness",
      text: "Enjoy the beauty of nature.",
      textByLocale: { hu: "Élvezem a természet szépségét.", en: "Enjoy the beauty of nature.", de: "Es bereitet mir Freude, die Schönheit der Natur zu genießen." },
      textObserver: "He/She enjoys the beauty of nature.",
      textObserverByLocale: { hu: "Élvezi a természet szépségét.", en: "He/She enjoys the beauty of nature.", de: "Es bereitet ihm/ihr Freude, die Schönheit der Natur zu genießen." },
    },
    {
      id: 11,
      dimension: "N",
      aspect: "withdrawal",
      text: "Am filled with doubts about things.",
      textByLocale: { hu: "Gyakran kételkedem.", en: "Am filled with doubts about things.", de: "Ich bin häufig beunruhigt." },
      textObserver: "He/She is filled with doubts about things.",
      textObserverByLocale: { hu: "Gyakran kételkedik.", en: "He/She is filled with doubts about things.", de: "Er/Sie ist häufig beunruhigt." },
    },
    {
      id: 12,
      dimension: "A",
      aspect: "compassion",
      text: "Feel others' emotions.",
      textByLocale: { hu: "Átérzem mások érzelmeit.", en: "Feel others' emotions.", de: "Ich habe ein Gespür für die Gefühle anderer." },
      textObserver: "He/She feels others' emotions.",
      textObserverByLocale: { hu: "Átérzi mások érzelmeit.", en: "He/She feels others' emotions.", de: "Er/Sie hat ein Gespür für die Gefühle anderer." },
    },
    {
      id: 13,
      dimension: "C",
      aspect: "industriousness",
      text: "Waste my time.",
      textByLocale: { hu: "Gyakran elpazarolom az időmet.", en: "Waste my time.", de: "Ich verschwende meine Zeit." },
      textObserver: "He/She wastes his/her time.",
      textObserverByLocale: { hu: "Gyakran elpazarolja az idejét.", en: "He/She wastes his/her time.", de: "Er/Sie verschwendet seine/ihre Zeit." },
      reversed: true,
    },
    {
      id: 14,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Am hard to get to know.",
      textByLocale: { hu: "Nehéz közel kerülni hozzám.", en: "Am hard to get to know.", de: "Mich näher kennenzulernen fällt schwer." },
      textObserver: "He/She is hard to get to know.",
      textObserverByLocale: { hu: "Nehéz közel kerülni hozzá.", en: "He/She is hard to get to know.", de: "Ihn/Sie näher kennenzulernen fällt schwer." },
      reversed: true,
    },
    {
      id: 15,
      dimension: "O",
      aspect: "intellect",
      text: "Have difficulty understanding abstract ideas.",
      textByLocale: { hu: "Nehezen értem meg az elvont gondolatokat.", en: "Have difficulty understanding abstract ideas.", de: "Ich habe Schwierigkeiten, abstrakte Ideen zu verstehen." },
      textObserver: "He/She has difficulty understanding abstract ideas.",
      textObserverByLocale: { hu: "Nehezen érti meg az elvont gondolatokat.", en: "He/She has difficulty understanding abstract ideas.", de: "Er/Sie hat Schwierigkeiten, abstrakte Ideen zu verstehen." },
      reversed: true,
    },
    {
      id: 16,
      dimension: "N",
      aspect: "volatility",
      text: "Rarely get irritated.",
      textByLocale: { hu: "Ritkán bosszankodom.", en: "Rarely get irritated.", de: "Ich bin selten irritiert." },
      textObserver: "He/She rarely gets irritated.",
      textObserverByLocale: { hu: "Ritkán bosszankodik.", en: "He/She rarely gets irritated.", de: "Er/Sie ist selten irritiert." },
      reversed: true,
    },
    {
      id: 17,
      dimension: "A",
      aspect: "politeness",
      text: "Believe that I am better than others.",
      textByLocale: { hu: "Azt hiszem, jobb vagyok másoknál.", en: "Believe that I am better than others.", de: "Ich fühle mich anderen überlegen." },
      textObserver: "He/She believes that he/she is better than others.",
      textObserverByLocale: { hu: "Azt hiszi, jobb másoknál.", en: "He/She believes that he/she is better than others.", de: "Er/Sie fühlt sich anderen überlegen." },
      reversed: true,
    },
    {
      id: 18,
      dimension: "C",
      aspect: "orderliness",
      text: "Like order.",
      textByLocale: { hu: "Szeretem a rendet.", en: "Like order.", de: "Ich mag Ordnung." },
      textObserver: "He/She likes order.",
      textObserverByLocale: { hu: "Szereti a rendet.", en: "He/She likes order.", de: "Er/Sie mag Ordnung." },
    },
    {
      id: 19,
      dimension: "E",
      aspect: "assertiveness",
      text: "Have a strong personality.",
      textByLocale: { hu: "Erős személyiségem van.", en: "Have a strong personality.", de: "Ich habe eine starke Persönlichkeit." },
      textObserver: "He/She has a strong personality.",
      textObserverByLocale: { hu: "Erős személyisége van.", en: "He/She has a strong personality.", de: "Er/Sie hat eine starke Persönlichkeit." },
    },
    {
      id: 20,
      dimension: "O",
      aspect: "openness",
      text: "Believe in the importance of art.",
      textByLocale: { hu: "Hiszem, hogy a művészet fontos.", en: "Believe in the importance of art.", de: "Kunst ist sehr wichtig für mich." },
      textObserver: "He/She believes in the importance of art.",
      textObserverByLocale: { hu: "Hiszi, hogy a művészet fontos.", en: "He/She believes in the importance of art.", de: "Kunst ist sehr wichtig für ihn/sie." },
    },
    {
      id: 21,
      dimension: "N",
      aspect: "withdrawal",
      text: "Feel comfortable with myself.",
      textByLocale: { hu: "Jól érzem magam a bőrömben.", en: "Feel comfortable with myself.", de: "Ich bin mit mir zufrieden." },
      textObserver: "He/She feels comfortable with him/herself.",
      textObserverByLocale: { hu: "Jól érzi magát a bőrében.", en: "He/She feels comfortable with him/herself.", de: "Er/Sie ist mit sich zufrieden." },
      reversed: true,
    },
    {
      id: 22,
      dimension: "A",
      aspect: "compassion",
      text: "Inquire about others' well-being.",
      textByLocale: { hu: "Érdeklődöm mások jólléte iránt.", en: "Inquire about others' well-being.", de: "Ich erkundige mich nach dem Wohlbefinden anderer." },
      textObserver: "He/She inquires about others' well-being.",
      textObserverByLocale: { hu: "Érdeklődik mások jólléte iránt.", en: "He/She inquires about others' well-being.", de: "Er/Sie erkundigt sich nach dem Wohlbefinden anderer." },
    },
    {
      id: 23,
      dimension: "C",
      aspect: "industriousness",
      text: "Find it difficult to get down to work.",
      textByLocale: { hu: "Nehezen állok neki a munkának.", en: "Find it difficult to get down to work.", de: "Es fällt mir schwer, mich an die Arbeit zu machen." },
      textObserver: "He/She finds it difficult to get down to work.",
      textObserverByLocale: { hu: "Nehezen áll neki a munkának.", en: "He/She finds it difficult to get down to work.", de: "Es fällt ihm/ihr schwer, sich an die Arbeit zu machen." },
      reversed: true,
    },
    {
      id: 24,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Keep others at a distance.",
      textByLocale: { hu: "Távolságot tartok másoktól.", en: "Keep others at a distance.", de: "Ich halte andere auf Distanz." },
      textObserver: "He/She keeps others at a distance.",
      textObserverByLocale: { hu: "Távolságot tart másoktól.", en: "He/She keeps others at a distance.", de: "Er/Sie hält andere auf Distanz." },
      reversed: true,
    },
    {
      id: 25,
      dimension: "O",
      aspect: "intellect",
      text: "Can handle a lot of information.",
      textByLocale: { hu: "Képes vagyok sok információt kezelni.", en: "Can handle a lot of information.", de: "Ich kann mit einer großen Menge an Informationen umgehen." },
      textObserver: "He/She can handle a lot of information.",
      textObserverByLocale: { hu: "Képes sok információt kezelni.", en: "He/She can handle a lot of information.", de: "Er/Sie kann mit einer großen Menge an Informationen umgehen." },
    },
    {
      id: 26,
      dimension: "N",
      aspect: "volatility",
      text: "Get upset easily.",
      textByLocale: { hu: "Könnyen felzaklatnak a dolgok.", en: "Get upset easily.", de: "Ich gerate leicht aus der Fassung." },
      textObserver: "He/She gets upset easily.",
      textObserverByLocale: { hu: "Könnyen felzaklatja valami.", en: "He/She gets upset easily.", de: "Er/Sie gerät leicht aus der Fassung." },
    },
    {
      id: 27,
      dimension: "A",
      aspect: "politeness",
      text: "Hate to seem pushy.",
      textByLocale: { hu: "Utálok tolakodónak tűnni.", en: "Hate to seem pushy.", de: "Es ist mir unangenehm, aufdringlich zu erscheinen." },
      textObserver: "He/She hates to seem pushy.",
      textObserverByLocale: { hu: "Utál tolakodónak tűnni.", en: "He/She hates to seem pushy.", de: "Es ist ihm/ihr unangenehm, aufdringlich zu erscheinen." },
    },
    {
      id: 28,
      dimension: "C",
      aspect: "orderliness",
      text: "Keep things tidy.",
      textByLocale: { hu: "Rendben tartom a dolgaimat.", en: "Keep things tidy.", de: "Ich räume meine Sachen stets auf." },
      textObserver: "He/She keeps things tidy.",
      textObserverByLocale: { hu: "Rendben tartja a dolgait.", en: "He/She keeps things tidy.", de: "Er/Sie räumt seine/ihre Sachen stets auf." },
    },
    {
      id: 29,
      dimension: "E",
      aspect: "assertiveness",
      text: "Lack the talent for influencing people.",
      textByLocale: { hu: "Hiányzik belőlem a tehetség, hogy befolyásoljam az embereket.", en: "Lack the talent for influencing people.", de: "Ich bin nicht gut darin, andere zu beeinflussen." },
      textObserver: "He/She lacks the talent for influencing people.",
      textObserverByLocale: { hu: "Hiányzik belőle a tehetség, hogy befolyásolja az embereket.", en: "He/She lacks the talent for influencing people.", de: "Er/Sie ist nicht gut darin, andere zu beeinflussen." },
      reversed: true,
    },
    {
      id: 30,
      dimension: "O",
      aspect: "openness",
      text: "Love to reflect on things.",
      textByLocale: { hu: "Szeretek elmélyedni a dolgokban.", en: "Love to reflect on things.", de: "Es bereitet mir Freude, über die Dinge nachzudenken." },
      textObserver: "He/She loves to reflect on things.",
      textObserverByLocale: { hu: "Szeret elmélyedni a dolgokban.", en: "He/She loves to reflect on things.", de: "Es bereitet ihm/ihr Freude, über die Dinge nachzudenken." },
    },
    {
      id: 31,
      dimension: "N",
      aspect: "withdrawal",
      text: "Feel threatened easily.",
      textByLocale: { hu: "Könnyen fenyegetve érzem magam.", en: "Feel threatened easily.", de: "Ich fühle mich schnell bedroht." },
      textObserver: "He/She feels threatened easily.",
      textObserverByLocale: { hu: "Könnyen fenyegetve érzi magát.", en: "He/She feels threatened easily.", de: "Er/Sie fühlt sich schnell bedroht." },
    },
    {
      id: 32,
      dimension: "A",
      aspect: "compassion",
      text: "Can't be bothered with other's needs.",
      textByLocale: { hu: "Nem foglalkozom mások szükségleteivel.", en: "Can't be bothered with other's needs.", de: "Die Belange anderer Menschen interessieren mich nicht." },
      textObserver: "He/She can't be bothered with other's needs.",
      textObserverByLocale: { hu: "Nem foglalkozik mások szükségleteivel.", en: "He/She can't be bothered with other's needs.", de: "Die Belange anderer Menschen interessieren ihn/sie nicht." },
      reversed: true,
    },
    {
      id: 33,
      dimension: "C",
      aspect: "industriousness",
      text: "Mess things up.",
      textByLocale: { hu: "Összekuszálom a dolgokat.", en: "Mess things up.", de: "Manche Dinge vermassele ich einfach." },
      textObserver: "He/She messes things up.",
      textObserverByLocale: { hu: "Összekuszálja a dolgokat.", en: "He/She messes things up.", de: "Er/Sie vermasselt manche Dinge einfach." },
      reversed: true,
    },
    {
      id: 34,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Reveal little about myself.",
      textByLocale: { hu: "Keveset árulok el magamról.", en: "Reveal little about myself.", de: "Ich gebe wenig über mich preis." },
      textObserver: "He/She reveals little about him/herself.",
      textObserverByLocale: { hu: "Keveset árul el magáról.", en: "He/She reveals little about him/herself.", de: "Er/Sie gibt wenig über sich preis." },
      reversed: true,
    },
    {
      id: 35,
      dimension: "O",
      aspect: "intellect",
      text: "Like to solve complex problems.",
      textByLocale: { hu: "Szeretek összetett problémákat megoldani.", en: "Like to solve complex problems.", de: "Es bereitet mir Freude, komplexe Probleme zu lösen." },
      textObserver: "He/She likes to solve complex problems.",
      textObserverByLocale: { hu: "Szeret összetett problémákat megoldani.", en: "He/She likes to solve complex problems.", de: "Es bereitet ihm/ihr Freude, komplexe Probleme zu lösen." },
    },
    {
      id: 36,
      dimension: "N",
      aspect: "volatility",
      text: "Keep my emotions under control.",
      textByLocale: { hu: "Kézben tartom az érzelmeimet.", en: "Keep my emotions under control.", de: "Ich kann meine Gefühle gut kontrollieren." },
      textObserver: "He/She keeps his/her emotions under control.",
      textObserverByLocale: { hu: "Kézben tartja az érzelmeit.", en: "He/She keeps his/her emotions under control.", de: "Er/Sie kann seine/ihre Gefühle gut kontrollieren." },
      reversed: true,
    },
    {
      id: 37,
      dimension: "A",
      aspect: "politeness",
      text: "Take advantage of others.",
      textByLocale: { hu: "Néha kihasználok másokat.", en: "Take advantage of others.", de: "Ich nutze andere aus." },
      textObserver: "He/She takes advantage of others.",
      textObserverByLocale: { hu: "Néha kihasznál másokat.", en: "He/She takes advantage of others.", de: "Er/Sie nutzt andere aus." },
      reversed: true,
    },
    {
      id: 38,
      dimension: "C",
      aspect: "orderliness",
      text: "Follow a schedule.",
      textByLocale: { hu: "Követem a beosztásomat.", en: "Follow a schedule.", de: "Ich halte mich an Zeitpläne." },
      textObserver: "He/She follows a schedule.",
      textObserverByLocale: { hu: "Követi a beosztását.", en: "He/She follows a schedule.", de: "Er/Sie hält sich an Zeitpläne." },
    },
    {
      id: 39,
      dimension: "E",
      aspect: "assertiveness",
      text: "Know how to captivate people.",
      textByLocale: { hu: "Tudom, hogyan ragadjam meg az emberek figyelmét.", en: "Know how to captivate people.", de: "Ich kann andere faszinieren." },
      textObserver: "He/She knows how to captivate people.",
      textObserverByLocale: { hu: "Tudja, hogyan ragadja meg az emberek figyelmét.", en: "He/She knows how to captivate people.", de: "Er/Sie kann andere faszinieren." },
    },
    {
      id: 40,
      dimension: "O",
      aspect: "openness",
      text: "Get deeply immersed in music.",
      textByLocale: { hu: "Teljesen elmerülök a zenében.", en: "Get deeply immersed in music.", de: "Ich gehe manchmal völlig in einer Musik auf, die ich höre." },
      textObserver: "He/She gets deeply immersed in music.",
      textObserverByLocale: { hu: "Teljesen elmerül a zenében.", en: "He/She gets deeply immersed in music.", de: "Er/Sie geht manchmal völlig in einer Musik auf, die er/sie hört." },
    },
    {
      id: 41,
      dimension: "N",
      aspect: "withdrawal",
      text: "Rarely feel depressed.",
      textByLocale: { hu: "Ritkán érzem magam depressziósnak.", en: "Rarely feel depressed.", de: "Es kommt selten vor, dass ich mich niedergeschlagen fühle." },
      textObserver: "He/She rarely feels depressed.",
      textObserverByLocale: { hu: "Ritkán érzi magát depressziósnak.", en: "He/She rarely feels depressed.", de: "Es kommt selten vor, dass er/sie sich niedergeschlagen fühlt." },
      reversed: true,
    },
    {
      id: 42,
      dimension: "A",
      aspect: "compassion",
      text: "Sympathize with others' feelings.",
      textByLocale: { hu: "Együtt érzek másokkal.", en: "Sympathize with others' feelings.", de: "Ich kann die Gefühle anderer nachempfinden." },
      textObserver: "He/She sympathizes with others' feelings.",
      textObserverByLocale: { hu: "Együtt érez másokkal.", en: "He/She sympathizes with others' feelings.", de: "Er/Sie kann die Gefühle anderer nachempfinden." },
    },
    {
      id: 43,
      dimension: "C",
      aspect: "industriousness",
      text: "Finish what I start.",
      textByLocale: { hu: "Befejezem, amit elkezdtem.", en: "Finish what I start.", de: "Was ich beginne, bringe ich auch zu Ende." },
      textObserver: "He/She finishes what he/she starts.",
      textObserverByLocale: { hu: "Befejezi, amit elkezdett.", en: "He/She finishes what he/she starts.", de: "Was er/sie beginnt, bringt er/sie auch zu Ende." },
    },
    {
      id: 44,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Warm up quickly to others.",
      textByLocale: { hu: "Hamar megbarátkozom másokkal.", en: "Warm up quickly to others.", de: "Ich lerne schnell neue Leute kennen." },
      textObserver: "He/She warms up quickly to others.",
      textObserverByLocale: { hu: "Hamar megbarátkozik másokkal.", en: "He/She warms up quickly to others.", de: "Er/Sie lernt schnell neue Leute kennen." },
    },
    {
      id: 45,
      dimension: "O",
      aspect: "intellect",
      text: "Avoid philosophical discussions.",
      textByLocale: { hu: "Nem szeretem a filozófiai vitákat.", en: "Avoid philosophical discussions.", de: "Ich vermeide philosophische Diskussionen." },
      textObserver: "He/She avoids philosophical discussions.",
      textObserverByLocale: { hu: "Nem szereti a filozófiai vitákat.", en: "He/She avoids philosophical discussions.", de: "Er/Sie vermeidet philosophische Diskussionen." },
      reversed: true,
    },
    {
      id: 46,
      dimension: "N",
      aspect: "volatility",
      text: "Change my mood a lot.",
      textByLocale: { hu: "Sokat változik a hangulatom.", en: "Change my mood a lot.", de: "Meine Stimmung ändert sich häufig." },
      textObserver: "He/She changes mood a lot.",
      textObserverByLocale: { hu: "Sokat változik a hangulata.", en: "He/She changes mood a lot.", de: "Seine/Ihre Stimmung ändert sich häufig." },
    },
    {
      id: 47,
      dimension: "A",
      aspect: "politeness",
      text: "Avoid imposing my will on others.",
      textByLocale: { hu: "Kerülöm, hogy másokra erőltessem az akaratomat.", en: "Avoid imposing my will on others.", de: "Ich vermeide es, anderen meinen Willen aufzuzwingen." },
      textObserver: "He/She avoids imposing his/her will on others.",
      textObserverByLocale: { hu: "Kerüli, hogy másokra erőltesse az akaratát.", en: "He/She avoids imposing his/her will on others.", de: "Er/Sie vermeidet es, anderen seinen/ihren Willen aufzuzwingen." },
    },
    {
      id: 48,
      dimension: "C",
      aspect: "orderliness",
      text: "Am not bothered by messy people.",
      textByLocale: { hu: "Nem zavar, ha mások rendetlenek.", en: "Am not bothered by messy people.", de: "Es stört mich nicht, wenn andere Menschen unordentlich sind." },
      textObserver: "He/She is not bothered by messy people.",
      textObserverByLocale: { hu: "Nem zavarja, ha mások rendetlenek.", en: "He/She is not bothered by messy people.", de: "Es stört ihn/sie nicht, wenn andere Menschen unordentlich sind." },
      reversed: true,
    },
    {
      id: 49,
      dimension: "E",
      aspect: "assertiveness",
      text: "Wait for others to lead the way.",
      textByLocale: { hu: "Várom, hogy mások mutassák az utat.", en: "Wait for others to lead the way.", de: "Ich überlasse es anderen, den Weg zu weisen." },
      textObserver: "He/She waits for others to lead the way.",
      textObserverByLocale: { hu: "Megvárja, hogy mások mutassák az utat.", en: "He/She waits for others to lead the way.", de: "Er/Sie überlässt es anderen, den Weg zu weisen." },
      reversed: true,
    },
    {
      id: 50,
      dimension: "O",
      aspect: "openness",
      text: "Do not like poetry.",
      textByLocale: { hu: "Nem szeretem a költészetet.", en: "Do not like poetry.", de: "Poesie beeindruckt mich wenig oder gar nicht." },
      textObserver: "He/She does not like poetry.",
      textObserverByLocale: { hu: "Nem szereti a költészetet.", en: "He/She does not like poetry.", de: "Poesie beeindruckt ihn/sie wenig oder gar nicht." },
      reversed: true,
    },
    {
      id: 51,
      dimension: "N",
      aspect: "withdrawal",
      text: "Worry about things.",
      textByLocale: { hu: "Aggódom a dolgok miatt.", en: "Worry about things.", de: "Ich mache mir häufig Sorgen." },
      textObserver: "He/She worries about things.",
      textObserverByLocale: { hu: "Aggódik a dolgok miatt.", en: "He/She worries about things.", de: "Er/Sie macht sich häufig Sorgen." },
    },
    {
      id: 52,
      dimension: "A",
      aspect: "compassion",
      text: "Am indifferent to the feelings of others.",
      textByLocale: { hu: "Közömbös vagyok mások érzéseivel szemben.", en: "Am indifferent to the feelings of others.", de: "Ich stehe den Gefühlen anderer gleichgültig gegenüber." },
      textObserver: "He/She is indifferent to the feelings of others.",
      textObserverByLocale: { hu: "Közömbös mások érzéseivel szemben.", en: "He/She is indifferent to the feelings of others.", de: "Er/Sie steht den Gefühlen anderer gleichgültig gegenüber." },
      reversed: true,
    },
    {
      id: 53,
      dimension: "C",
      aspect: "industriousness",
      text: "Don't put my mind on the task at hand.",
      textByLocale: { hu: "Nem tudok koncentrálni az éppen végzett feladatra.", en: "Don't put my mind on the task at hand.", de: "Manchmal bin ich mit meinen Gedanken nicht bei der Sache." },
      textObserver: "He/She doesn't put his/her mind on the task at hand.",
      textObserverByLocale: { hu: "Nem tud koncentrálni az éppen végzett feladatra.", en: "He/She doesn't put his/her mind on the task at hand.", de: "Er/Sie ist manchmal mit den Gedanken nicht bei der Sache." },
      reversed: true,
    },
    {
      id: 54,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Rarely get caught up in the excitement.",
      textByLocale: { hu: "Ritkán lelkesedem igazán.", en: "Rarely get caught up in the excitement.", de: "Ich lasse mich nicht durch den Trubel der Ereignisse mitreißen." },
      textObserver: "He/She rarely gets caught up in the excitement.",
      textObserverByLocale: { hu: "Ritkán lelkesedik igazán.", en: "He/She rarely gets caught up in the excitement.", de: "Er/Sie lässt sich nicht durch den Trubel der Ereignisse mitreißen." },
      reversed: true,
    },
    {
      id: 55,
      dimension: "O",
      aspect: "intellect",
      text: "Avoid difficult reading material.",
      textByLocale: { hu: "Kerülöm a nehéz olvasnivalókat.", en: "Avoid difficult reading material.", de: "Ich vermeide schwierigen Lesestoff." },
      textObserver: "He/She avoids difficult reading material.",
      textObserverByLocale: { hu: "Kerüli a nehéz olvasnivalókat.", en: "He/She avoids difficult reading material.", de: "Er/Sie vermeidet schwierigen Lesestoff." },
      reversed: true,
    },
    {
      id: 56,
      dimension: "N",
      aspect: "volatility",
      text: "Rarely lose my composure.",
      textByLocale: { hu: "Ritkán veszítem el a nyugalmamat.", en: "Rarely lose my composure.", de: "Es kommt selten vor, dass ich die Fassung verliere." },
      textObserver: "He/She rarely loses composure.",
      textObserverByLocale: { hu: "Ritkán veszíti el a nyugalmát.", en: "He/She rarely loses composure.", de: "Es kommt selten vor, dass er/sie die Fassung verliert." },
      reversed: true,
    },
    {
      id: 57,
      dimension: "A",
      aspect: "politeness",
      text: "Rarely put people under pressure.",
      textByLocale: { hu: "Ritkán nyomás alá helyezek másokat.", en: "Rarely put people under pressure.", de: "Ich setze andere nur selten unter Druck." },
      textObserver: "He/She rarely puts people under pressure.",
      textObserverByLocale: { hu: "Ritkán nyomás alá helyez másokat.", en: "He/She rarely puts people under pressure.", de: "Er/Sie setzt andere nur selten unter Druck." },
    },
    {
      id: 58,
      dimension: "C",
      aspect: "orderliness",
      text: "Want everything to be \"just right.\"",
      textByLocale: { hu: "Azt akarom, hogy minden „éppen megfelelő” legyen.", en: "Want everything to be \"just right.\"", de: "Ich wünsche mir, dass alles perfekt ist." },
      textObserver: "He/She wants everything to be \"just right.\"",
      textObserverByLocale: { hu: "Azt akarja, hogy minden „éppen megfelelő” legyen.", en: "He/She wants everything to be \"just right.\"", de: "Er/Sie wünscht sich, dass alles perfekt ist." },
    },
    {
      id: 59,
      dimension: "E",
      aspect: "assertiveness",
      text: "See myself as a good leader.",
      textByLocale: { hu: "Jó vezetőnek tartom magam.", en: "See myself as a good leader.", de: "Ich bin gut darin, Führung zu übernehmen." },
      textObserver: "He/She sees him/herself as a good leader.",
      textObserverByLocale: { hu: "Jó vezetőnek tartja magát.", en: "He/She sees him/herself as a good leader.", de: "Er/Sie ist gut darin, Führung zu übernehmen." },
    },
    {
      id: 60,
      dimension: "O",
      aspect: "openness",
      text: "Seldom notice the emotional aspects of paintings and pictures.",
      textByLocale: { hu: "Ritkán veszem észre a festmények és képek érzelmi hatását.", en: "Seldom notice the emotional aspects of paintings and pictures.", de: "Gemälde oder Fotografien berühren mich nicht." },
      textObserver: "He/She seldom notices the emotional aspects of paintings and pictures.",
      textObserverByLocale: { hu: "Ritkán veszi észre a festmények és képek érzelmi hatását.", en: "He/She seldom notices the emotional aspects of paintings and pictures.", de: "Gemälde oder Fotografien berühren ihn/sie nicht." },
      reversed: true,
    },
    {
      id: 61,
      dimension: "N",
      aspect: "withdrawal",
      text: "Am easily discouraged.",
      textByLocale: { hu: "Könnyen elveszítem a bátorságomat.", en: "Am easily discouraged.", de: "Ich lasse mich schnell entmutigen." },
      textObserver: "He/She is easily discouraged.",
      textObserverByLocale: { hu: "Könnyen elveszíti a bátorságát.", en: "He/She is easily discouraged.", de: "Er/Sie lässt sich schnell entmutigen." },
    },
    {
      id: 62,
      dimension: "A",
      aspect: "compassion",
      text: "Take no time for others.",
      textByLocale: { hu: "Nem szánok időt másokra.", en: "Take no time for others.", de: "Ich nehme mir keine Zeit für andere." },
      textObserver: "He/She takes no time for others.",
      textObserverByLocale: { hu: "Nem szán időt másokra.", en: "He/She takes no time for others.", de: "Er/Sie nimmt sich keine Zeit für andere." },
      reversed: true,
    },
    {
      id: 63,
      dimension: "C",
      aspect: "industriousness",
      text: "Get things done quickly.",
      textByLocale: { hu: "Gyorsan elvégzem a feladataimat.", en: "Get things done quickly.", de: "Ich erledige meine Aufgaben rasch." },
      textObserver: "He/She gets things done quickly.",
      textObserverByLocale: { hu: "Gyorsan elvégzi a feladatait.", en: "He/She gets things done quickly.", de: "Er/Sie erledigt Aufgaben rasch." },
    },
    {
      id: 64,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Am not a very enthusiastic person.",
      textByLocale: { hu: "Nem vagyok túl lelkes típus.", en: "Am not a very enthusiastic person.", de: "Ich bin keine besonders enthusiastische Person." },
      textObserver: "He/She is not a very enthusiastic person.",
      textObserverByLocale: { hu: "Nem túl lelkes típus.", en: "He/She is not a very enthusiastic person.", de: "Er/Sie ist keine besonders enthusiastische Person." },
      reversed: true,
    },
    {
      id: 65,
      dimension: "O",
      aspect: "intellect",
      text: "Have a rich vocabulary.",
      textByLocale: { hu: "Gazdag szókincsem van.", en: "Have a rich vocabulary.", de: "Ich habe einen reichen Wortschatz." },
      textObserver: "He/She has a rich vocabulary.",
      textObserverByLocale: { hu: "Gazdag szókincse van.", en: "He/She has a rich vocabulary.", de: "Er/Sie hat einen reichen Wortschatz." },
    },
    {
      id: 66,
      dimension: "N",
      aspect: "volatility",
      text: "Am a person whose moods go up and down easily.",
      textByLocale: { hu: "Olyan ember vagyok, akinek a hangulata könnyen ingadozik.", en: "Am a person whose moods go up and down easily.", de: "Meine Stimmung verändert sich leicht." },
      textObserver: "He/She is a person whose moods go up and down easily.",
      textObserverByLocale: { hu: "Olyan ember, akinek a hangulata könnyen ingadozik.", en: "He/She is a person whose moods go up and down easily.", de: "Er/Sie ist eine Person, deren Stimmung sich leicht verändert." },
    },
    {
      id: 67,
      dimension: "A",
      aspect: "politeness",
      text: "Insult people.",
      textByLocale: { hu: "Sértegetem az embereket.", en: "Insult people.", de: "Manchmal beleidige ich andere Leute." },
      textObserver: "He/She insults people.",
      textObserverByLocale: { hu: "Sérteget másokat.", en: "He/She insults people.", de: "Er/Sie beleidigt manchmal andere Leute." },
      reversed: true,
    },
    {
      id: 68,
      dimension: "C",
      aspect: "orderliness",
      text: "Am not bothered by disorder.",
      textByLocale: { hu: "Nem zavar a rendetlenség.", en: "Am not bothered by disorder.", de: "Unordnung stört mich nicht." },
      textObserver: "He/She is not bothered by disorder.",
      textObserverByLocale: { hu: "Nem zavarja a rendetlenség.", en: "He/She is not bothered by disorder.", de: "Unordnung stört ihn/sie nicht." },
      reversed: true,
    },
    {
      id: 69,
      dimension: "E",
      aspect: "assertiveness",
      text: "Can talk others into doing things.",
      textByLocale: { hu: "Rá tudok venni másokat, hogy megtegyenek valamit.", en: "Can talk others into doing things.", de: "Ich kann andere dazu bringen, Dinge zu tun, die ich will." },
      textObserver: "He/She can talk others into doing things.",
      textObserverByLocale: { hu: "Rá tudja venni másokat, hogy megtegyenek valamit.", en: "He/She can talk others into doing things.", de: "Er/Sie kann andere dazu bringen, Dinge zu tun." },
    },
    {
      id: 70,
      dimension: "O",
      aspect: "openness",
      text: "Need a creative outlet.",
      textByLocale: { hu: "Szükségem van valamilyen kreatív kikapcsolódásra.", en: "Need a creative outlet.", de: "Ich muss mich kreativ betätigen." },
      textObserver: "He/She needs a creative outlet.",
      textObserverByLocale: { hu: "Szüksége van valamilyen kreatív kikapcsolódásra.", en: "He/She needs a creative outlet.", de: "Er/Sie muss sich kreativ betätigen." },
    },
    {
      id: 71,
      dimension: "N",
      aspect: "withdrawal",
      text: "Am not embarrassed easily.",
      textByLocale: { hu: "Nem esek könnyen zavarba.", en: "Am not embarrassed easily.", de: "Mir ist selten etwas peinlich." },
      textObserver: "He/She is not embarrassed easily.",
      textObserverByLocale: { hu: "Nem esik könnyen zavarba.", en: "He/She is not embarrassed easily.", de: "Ihm/Ihr ist selten etwas peinlich." },
      reversed: true,
    },
    {
      id: 72,
      dimension: "A",
      aspect: "compassion",
      text: "Take an interest in other people's lives.",
      textByLocale: { hu: "Érdeklődöm mások élete iránt.", en: "Take an interest in other people's lives.", de: "Ich interessiere mich für das Leben anderer." },
      textObserver: "He/She takes an interest in other people's lives.",
      textObserverByLocale: { hu: "Érdeklődik mások élete iránt.", en: "He/She takes an interest in other people's lives.", de: "Er/Sie interessiert sich für das Leben anderer." },
    },
    {
      id: 73,
      dimension: "C",
      aspect: "industriousness",
      text: "Always know what I am doing.",
      textByLocale: { hu: "Tudatosan csinálom, amit csinálok.", en: "Always know what I am doing.", de: "Ich weiß immer, was ich tue." },
      textObserver: "He/She always knows what he/she is doing.",
      textObserverByLocale: { hu: "Tudatosan csinálja, amit csinál.", en: "He/She always knows what he/she is doing.", de: "Er/Sie weiß immer, was er/sie tut." },
    },
    {
      id: 74,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Show my feelings when I'm happy.",
      textByLocale: { hu: "Kimutatom az örömömet, ha boldog vagyok.", en: "Show my feelings when I'm happy.", de: "Wenn ich glücklich bin, dann zeige ich das auch." },
      textObserver: "He/She shows his/her feelings when happy.",
      textObserverByLocale: { hu: "Kimutatja az örömét, ha boldog.", en: "He/She shows his/her feelings when happy.", de: "Wenn er/sie glücklich ist, zeigt er/sie das auch." },
    },
    {
      id: 75,
      dimension: "O",
      aspect: "intellect",
      text: "Think quickly.",
      textByLocale: { hu: "Gyorsan gondolkodom.", en: "Think quickly.", de: "Ich habe eine schnelle Auffassungsgabe." },
      textObserver: "He/She thinks quickly.",
      textObserverByLocale: { hu: "Gyorsan gondolkodik.", en: "He/She thinks quickly.", de: "Er/Sie hat eine schnelle Auffassungsgabe." },
    },
    {
      id: 76,
      dimension: "N",
      aspect: "volatility",
      text: "Am not easily annoyed.",
      textByLocale: { hu: "Nem bosszantodom fel könnyen.", en: "Am not easily annoyed.", de: "Ich bin nicht schnell verärgert." },
      textObserver: "He/She is not easily annoyed.",
      textObserverByLocale: { hu: "Nem bosszantódik fel könnyen.", en: "He/She is not easily annoyed.", de: "Er/Sie ist nicht schnell verärgert." },
      reversed: true,
    },
    {
      id: 77,
      dimension: "A",
      aspect: "politeness",
      text: "Seek conflict.",
      textByLocale: { hu: "Konfliktust keresek.", en: "Seek conflict.", de: "Ich suche Streit." },
      textObserver: "He/She seeks conflict.",
      textObserverByLocale: { hu: "Konfliktust keres.", en: "He/She seeks conflict.", de: "Er/Sie sucht Streit." },
      reversed: true,
    },
    {
      id: 78,
      dimension: "C",
      aspect: "orderliness",
      text: "Dislike routine.",
      textByLocale: { hu: "Nem szeretem a rutint.", en: "Dislike routine.", de: "Routine mag ich nicht." },
      textObserver: "He/She dislikes routine.",
      textObserverByLocale: { hu: "Nem szereti a rutint.", en: "He/She dislikes routine.", de: "Routine mag er/sie nicht." },
      reversed: true,
    },
    {
      id: 79,
      dimension: "E",
      aspect: "assertiveness",
      text: "Hold back my opinions.",
      textByLocale: { hu: "Visszatartom a véleményemet.", en: "Hold back my opinions.", de: "Ich halte mich mit meiner Meinung eher zurück." },
      textObserver: "He/She holds back his/her opinions.",
      textObserverByLocale: { hu: "Visszatartja a véleményét.", en: "He/She holds back his/her opinions.", de: "Er/Sie hält sich mit seiner/ihrer Meinung eher zurück." },
      reversed: true,
    },
    {
      id: 80,
      dimension: "O",
      aspect: "openness",
      text: "Seldom get lost in thought.",
      textByLocale: { hu: "Ritkán merülök el a gondolataimban.", en: "Seldom get lost in thought.", de: "Es passiert selten, dass ich meinen Gedanken nachhänge." },
      textObserver: "He/She seldom gets lost in thought.",
      textObserverByLocale: { hu: "Ritkán merül el a gondolataiban.", en: "He/She seldom gets lost in thought.", de: "Es passiert selten, dass er/sie seinen/ihren Gedanken nachhängt." },
      reversed: true,
    },
    {
      id: 81,
      dimension: "N",
      aspect: "withdrawal",
      text: "Become overwhelmed by events.",
      textByLocale: { hu: "Néha túl soknak érzem a történéseket.", en: "Become overwhelmed by events.", de: "Manchmal ist mir alles zu viel." },
      textObserver: "He/She becomes overwhelmed by events.",
      textObserverByLocale: { hu: "Néha túl soknak érzi a történéseket.", en: "He/She becomes overwhelmed by events.", de: "Manchmal ist ihm/ihr alles zu viel." },
    },
    {
      id: 82,
      dimension: "A",
      aspect: "compassion",
      text: "Don't have a soft side.",
      textByLocale: { hu: "Nincs gyengéd oldalam.", en: "Don't have a soft side.", de: "Mir fehlt eine weiche Seite." },
      textObserver: "He/She doesn't have a soft side.",
      textObserverByLocale: { hu: "Nincs gyengéd oldala.", en: "He/She doesn't have a soft side.", de: "Ihm/Ihr fehlt eine weiche Seite." },
      reversed: true,
    },
    {
      id: 83,
      dimension: "C",
      aspect: "industriousness",
      text: "Postpone decisions.",
      textByLocale: { hu: "Halogatom a döntéseket.", en: "Postpone decisions.", de: "Ich schiebe Entscheidungen auf." },
      textObserver: "He/She postpones decisions.",
      textObserverByLocale: { hu: "Halogatja a döntéseket.", en: "He/She postpones decisions.", de: "Er/Sie schiebt Entscheidungen auf." },
      reversed: true,
    },
    {
      id: 84,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Have a lot of fun.",
      textByLocale: { hu: "Sokat szórakozom.", en: "Have a lot of fun.", de: "Ich habe viel Spaß." },
      textObserver: "He/She has a lot of fun.",
      textObserverByLocale: { hu: "Sokat szórakozik.", en: "He/She has a lot of fun.", de: "Er/Sie hat viel Spaß." },
    },
    {
      id: 85,
      dimension: "O",
      aspect: "intellect",
      text: "Learn things slowly.",
      textByLocale: { hu: "Lassan tanulok meg új dolgokat.", en: "Learn things slowly.", de: "Ich brauche manchmal länger, um etwas Neues zu lernen." },
      textObserver: "He/She learns things slowly.",
      textObserverByLocale: { hu: "Lassan tanul meg új dolgokat.", en: "He/She learns things slowly.", de: "Er/Sie braucht manchmal länger, um etwas Neues zu lernen." },
      reversed: true,
    },
    {
      id: 86,
      dimension: "N",
      aspect: "volatility",
      text: "Get easily agitated.",
      textByLocale: { hu: "Könnyen izgalomba jövök.", en: "Get easily agitated.", de: "Ich bin schnell aufgewühlt." },
      textObserver: "He/She gets easily agitated.",
      textObserverByLocale: { hu: "Könnyen izgalomba jön.", en: "He/She gets easily agitated.", de: "Er/Sie ist schnell aufgewühlt." },
    },
    {
      id: 87,
      dimension: "A",
      aspect: "politeness",
      text: "Love a good fight.",
      textByLocale: { hu: "Szeretem az összetűzéseket.", en: "Love a good fight.", de: "Ich mag Diskussionen und Auseinandersetzungen." },
      textObserver: "He/She loves a good fight.",
      textObserverByLocale: { hu: "Szereti az összetűzéseket.", en: "He/She loves a good fight.", de: "Er/Sie mag Diskussionen und Auseinandersetzungen." },
      reversed: true,
    },
    {
      id: 88,
      dimension: "C",
      aspect: "orderliness",
      text: "See that rules are observed.",
      textByLocale: { hu: "Figyelek arra, hogy betartsák a szabályokat.", en: "See that rules are observed.", de: "Ich achte darauf, dass Regeln eingehalten werden." },
      textObserver: "He/She sees that rules are observed.",
      textObserverByLocale: { hu: "Figyel arra, hogy betartsák a szabályokat.", en: "He/She sees that rules are observed.", de: "Er/Sie achtet darauf, dass Regeln eingehalten werden." },
    },
    {
      id: 89,
      dimension: "E",
      aspect: "assertiveness",
      text: "Am the first to act.",
      textByLocale: { hu: "Én szoktam kezdeményezni.", en: "Am the first to act.", de: "Ich übernehme häufig die Initiative." },
      textObserver: "He/She is the first to act.",
      textObserverByLocale: { hu: "Ő szokott kezdeményezni.", en: "He/She is the first to act.", de: "Er/Sie übernimmt häufig die Initiative." },
    },
    {
      id: 90,
      dimension: "O",
      aspect: "openness",
      text: "Seldom daydream.",
      textByLocale: { hu: "Ritkán álmodozom.", en: "Seldom daydream.", de: "Es kommt selten vor, dass ich Tagträumen nachgehe." },
      textObserver: "He/She seldom daydreams.",
      textObserverByLocale: { hu: "Ritkán álmodozik.", en: "He/She seldom daydreams.", de: "Es kommt selten vor, dass er/sie Tagträumen nachgeht." },
      reversed: true,
    },
    {
      id: 91,
      dimension: "N",
      aspect: "withdrawal",
      text: "Am afraid of many things.",
      textByLocale: { hu: "Sok mindentől félek.", en: "Am afraid of many things.", de: "Ich sorge mich über viele Dinge." },
      textObserver: "He/She is afraid of many things.",
      textObserverByLocale: { hu: "Sok mindentől fél.", en: "He/She is afraid of many things.", de: "Er/Sie sorgt sich über viele Dinge." },
    },
    {
      id: 92,
      dimension: "A",
      aspect: "compassion",
      text: "Like to do things for others.",
      textByLocale: { hu: "Szívesen teszek másokért dolgokat.", en: "Like to do things for others.", de: "Es bereitet mir Freude, etwas für andere zu tun." },
      textObserver: "He/She likes to do things for others.",
      textObserverByLocale: { hu: "Szívesen tesz másokért dolgokat.", en: "He/She likes to do things for others.", de: "Es bereitet ihm/ihr Freude, etwas für andere zu tun." },
    },
    {
      id: 93,
      dimension: "C",
      aspect: "industriousness",
      text: "Am easily distracted.",
      textByLocale: { hu: "Könnyen elkalandozik a figyelmem.", en: "Am easily distracted.", de: "Ich lasse mich leicht ablenken." },
      textObserver: "He/She is easily distracted.",
      textObserverByLocale: { hu: "Könnyen elkalandozik a figyelme.", en: "He/She is easily distracted.", de: "Er/Sie lässt sich leicht ablenken." },
      reversed: true,
    },
    {
      id: 94,
      dimension: "E",
      aspect: "enthusiasm",
      text: "Laugh a lot.",
      textByLocale: { hu: "Sokat nevetek.", en: "Laugh a lot.", de: "Ich lache viel." },
      textObserver: "He/She laughs a lot.",
      textObserverByLocale: { hu: "Sokat nevet.", en: "He/She laughs a lot.", de: "Er/Sie lacht viel." },
    },
    {
      id: 95,
      dimension: "O",
      aspect: "intellect",
      text: "Formulate ideas clearly.",
      textByLocale: { hu: "Világosan fogalmazom meg a gondolataimat.", en: "Formulate ideas clearly.", de: "Ich kann meine Gedanken klar formulieren." },
      textObserver: "He/She formulates ideas clearly.",
      textObserverByLocale: { hu: "Világosan fogalmazza meg a gondolatait.", en: "He/She formulates ideas clearly.", de: "Er/Sie kann Gedanken klar formulieren." },
    },
    {
      id: 96,
      dimension: "N",
      aspect: "volatility",
      text: "Can be stirred up easily.",
      textByLocale: { hu: "Könnyen felkavarodom.", en: "Can be stirred up easily.", de: "Ich bin schnell gerührt." },
      textObserver: "He/She can be stirred up easily.",
      textObserverByLocale: { hu: "Könnyen felkavarodik.", en: "He/She can be stirred up easily.", de: "Er/Sie ist schnell gerührt." },
    },
    {
      id: 97,
      dimension: "A",
      aspect: "politeness",
      text: "Am out for my own personal gain.",
      textByLocale: { hu: "A saját hasznomra törekszem.", en: "Am out for my own personal gain.", de: "Ich schaue auf meinen persönlichen Vorteil." },
      textObserver: "He/She is out for his/her own personal gain.",
      textObserverByLocale: { hu: "A saját hasznára törekszik.", en: "He/She is out for his/her own personal gain.", de: "Er/Sie schaut auf den persönlichen Vorteil." },
      reversed: true,
    },
    {
      id: 98,
      dimension: "C",
      aspect: "orderliness",
      text: "Want every detail taken care of.",
      textByLocale: { hu: "Azt akarom, hogy minden részlet rendben legyen.", en: "Want every detail taken care of.", de: "Ich lege großen Wert auf Details." },
      textObserver: "He/She wants every detail taken care of.",
      textObserverByLocale: { hu: "Azt akarja, hogy minden részlet rendben legyen.", en: "He/She wants every detail taken care of.", de: "Er/Sie legt großen Wert auf Details." },
    },
    {
      id: 99,
      dimension: "E",
      aspect: "assertiveness",
      text: "Do not have an assertive personality.",
      textByLocale: { hu: "Nem vagyok igazán határozott.", en: "Do not have an assertive personality.", de: "Ich bin nicht durchsetzungsfähig." },
      textObserver: "He/She does not have an assertive personality.",
      textObserverByLocale: { hu: "Nem igazán határozott.", en: "He/She does not have an assertive personality.", de: "Er/Sie ist nicht durchsetzungsfähig." },
      reversed: true,
    },
    {
      id: 100,
      dimension: "O",
      aspect: "openness",
      text: "See beauty in things that others might not notice.",
      textByLocale: { hu: "Szépséget látok olyan dolgokban, amelyeket mások talán észre sem vesznek.", en: "See beauty in things that others might not notice.", de: "In manchen Dingen sehe ich etwas Schönes, das anderen verborgen bleibt." },
      textObserver: "He/She sees beauty in things that others might not notice.",
      textObserverByLocale: { hu: "Szépséget lát olyan dolgokban, amelyeket mások talán észre sem vesznek.", en: "He/She sees beauty in things that others might not notice.", de: "Er/Sie sieht in manchen Dingen etwas Schönes, das anderen verborgen bleibt." },
    },
  ],
};
