import type { TestConfig } from "./types";

/**
 * Official HEXACO-PI-R (60 questions)
 */
export const hexacoConfig: TestConfig = {
  type: "HEXACO",
  name: "HEXACO-PI-R",
  description: "A hivatalos HEXACO személyiségteszt 60 kérdéssel.",
  format: "likert",
  dimensions: [
    {
      code: "H",
      label: "Honesty–Humility",
      labelByLocale: {
        en: "Honesty–Humility",
        hu: "Őszinteség-Alázat",
        de: "Ehrlichkeit–Bescheidenheit",
      },
      color: "#818CF8",
      description: "Measures the extent to which you avoid manipulating others, feel tempted to break rules, desire material wealth, and claim elevated social status.",
      descriptionByLocale: {
        en: "Measures the extent to which you avoid manipulating others, feel tempted to break rules, desire material wealth, and claim elevated social status.",
        hu: "Azt méri, mennyire kerülöd mások manipulálását, mennyire vonz a szabályok megszegése, mennyire vágysz anyagi gazdagságra, és mennyire igényelsz kiemelt társadalmi státuszt.",
        de: "Misst, inwieweit du es vermeidest, andere zu manipulieren, Regeln zu brechen, Reichtum zu begehren und besonderen sozialen Status zu beanspruchen.",
      },
      insights: {
        low: "You tend to flatter others to get what you want, feel tempted to break rules for personal profit, and have a strong sense of entitlement.",
        mid: "You balance personal interests with ethical considerations, adapting your approach to the situation.",
        high: "You avoid manipulating others, feel little desire for material wealth, and approach others with genuine sincerity and humility.",
      },
      insightsByLocale: {
        en: {
          low: "You tend to flatter others to get what you want, feel tempted to break rules for personal profit, and have a strong sense of entitlement.",
          mid: "You balance personal interests with ethical considerations, adapting your approach to the situation.",
          high: "You avoid manipulating others, feel little desire for material wealth, and approach others with genuine sincerity and humility.",
        },
        hu: {
          low: "Hajlamos vagy mások hízelgésére az érdekeidért, a szabályok megszegése csábít, és erős anyagi és státuszmotivációval rendelkezel.",
          mid: "Kiegyensúlyozottan kezeled a személyes érdeket és az etikai megfontolásokat.",
          high: "Nem manipulálod másokat, kevéssé vonz az anyagi gazdagság, és szerényen, őszintén viszonyulsz másokhoz.",
        },
        de: {
          low: "Du neigst dazu, andere zu schmeicheln, Regeln zu umgehen und hast ein starkes Gefühl von Anspruch und Statusdenken.",
          mid: "Du balancierst persönliche Interessen und ethische Überlegungen situationsabhängig aus.",
          high: "Du manipulierst keine anderen, begehrst wenig materiellen Reichtum und begegnest anderen mit aufrichtiger Bescheidenheit.",
        },
      },
      facets: [
        { code: "sincerity", label: "Sincerity", labelByLocale: { en: "Sincerity", hu: "Őszinteség", de: "Aufrichtigkeit" } },
        { code: "fairness", label: "Fairness", labelByLocale: { en: "Fairness", hu: "Igazságosság", de: "Fairness" } },
        { code: "greed_avoidance", label: "Greed Avoidance", labelByLocale: { en: "Greed Avoidance", hu: "Kapzsiság-kerülés", de: "Genügsamkeit" } },
        { code: "modesty", label: "Modesty", labelByLocale: { en: "Modesty", hu: "Szerénység", de: "Bescheidenheit" } },
      ],
    },
    {
      code: "E",
      label: "Emotionality",
      labelByLocale: {
        en: "Emotionality",
        hu: "Érzelmi stabilitás",
        de: "Emotionalität",
      },
      color: "#FB7185",
      description: "Measures your tendency to experience fear, anxiety, and emotional vulnerability, and your need for emotional support from others.",
      descriptionByLocale: {
        en: "Measures your tendency to experience fear, anxiety, and emotional vulnerability, and your need for emotional support from others.",
        hu: "Az érzelmi félelem, szorongás és sebezhetőség mértékét, valamint a mások általi érzelmi támasz igényét méri.",
        de: "Misst deine Neigung, Angst, Sorgen und emotionale Verletzlichkeit zu erleben sowie dein Bedürfnis nach emotionaler Unterstützung durch andere.",
      },
      insights: {
        low: "Emotionally resilient — you rarely feel fear or anxiety, need little emotional support, and remain detached under pressure.",
        mid: "You experience moderate emotional responses, occasionally seeking support but generally managing stress independently.",
        high: "You experience strong emotions — fear, anxiety, and empathy — and often feel the need to share your concerns with others.",
      },
      insightsByLocale: {
        en: {
          low: "Emotionally resilient — you rarely feel fear or anxiety, need little emotional support, and remain detached under pressure.",
          mid: "You experience moderate emotional responses, occasionally seeking support but generally managing stress independently.",
          high: "You experience strong emotions — fear, anxiety, and empathy — and often feel the need to share your concerns with others.",
        },
        hu: {
          low: "Érzelmileg ellenálló: ritkán félsz vagy aggódsz, kevés érzelmi támogatásra van szükséged, és nyomás alatt is megőrzöd a távolságtartásodat.",
          mid: "Mérsékelten reagálsz érzelmileg – alkalmanként keresed mások támogatását, de általában önállóan kezeled a stresszt.",
          high: "Erős érzelmeket élsz át – félelmet, szorongást és empátiát –, és gyakran szükséged van arra, hogy megoszd a gondjaidat másokkal.",
        },
        de: {
          low: "Emotional belastbar — du hast selten Angst oder Sorgen, brauchst wenig Unterstützung und bleibst unter Druck distanziert.",
          mid: "Du erlebst gemäßigte emotionale Reaktionen, suchst gelegentlich Unterstützung und bewältigst Stress meist selbstständig.",
          high: "Du erlebst starke Emotionen — Angst, Sorge und Empathie — und hast oft das Bedürfnis, deine Sorgen mit anderen zu teilen.",
        },
      },
      facets: [
        { code: "fearfulness", label: "Fearfulness", labelByLocale: { en: "Fearfulness", hu: "Félelem", de: "Ängstlichkeit" } },
        { code: "anxiety", label: "Anxiety", labelByLocale: { en: "Anxiety", hu: "Szorongás", de: "Besorgnis" } },
        { code: "dependence", label: "Dependence", labelByLocale: { en: "Dependence", hu: "Függőség", de: "Abhängigkeit" } },
        { code: "sentimentality", label: "Sentimentality", labelByLocale: { en: "Sentimentality", hu: "Érzelmesség", de: "Empfindsamkeit" } },
      ],
    },
    {
      code: "X",
      label: "Extraversion",
      labelByLocale: {
        en: "Extraversion",
        hu: "Extraverzió",
        de: "Extraversion",
      },
      color: "#F59E0B",
      description: "Measures your social confidence, enjoyment of interaction with others, and overall sense of enthusiasm and energy.",
      descriptionByLocale: {
        en: "Measures your social confidence, enjoyment of interaction with others, and overall sense of enthusiasm and energy.",
        hu: "A társas magabiztosságot, a szociális interakciók élvezetét, valamint az általános energiát és lelkesedést méri.",
        de: "Misst soziale Selbstsicherheit, Freude an Interaktion mit anderen sowie allgemeinen Enthusiasmus und Energie.",
      },
      insights: {
        low: "You may feel unpopular or awkward in the spotlight, prefer solitary activities, and feel less energetic or optimistic than others.",
        mid: "You can engage socially and take on leadership roles, while also enjoying independent tasks and quieter moments.",
        high: "You feel confident and energized in social settings, enjoy group interactions, and have a positive sense of yourself.",
      },
      insightsByLocale: {
        en: {
          low: "You may feel unpopular or awkward in the spotlight, prefer solitary activities, and feel less energetic or optimistic than others.",
          mid: "You can engage socially and take on leadership roles, while also enjoying independent tasks and quieter moments.",
          high: "You feel confident and energized in social settings, enjoy group interactions, and have a positive sense of yourself.",
        },
        hu: {
          low: "Kényelmetlenül érezheted magad a reflektorfényben, kevésbé tartod magad népszerűnek, és inkább az egyéni tevékenységeket preferálod.",
          mid: "Társas helyzetekben képes vagy vezető szerepet vállalni és egyéni tevékenységeket egyaránt élvezni.",
          high: "Magabiztosnak és energikusnak érzed magad társas közegben, élvezed a csoportokat, és pozitívan gondolsz magadra.",
        },
        de: {
          low: "Du fühlst dich in sozialen Situationen möglicherweise unsicher oder fehl am Platz, bevorzugst Einzelaktivitäten und wirkst weniger energiegeladen.",
          mid: "Du kannst soziale Situationen meistern und Führungsrollen übernehmen, genießt aber auch unabhängige Aufgaben.",
          high: "Du fühlst dich in sozialen Umgebungen selbstsicher und energiegeladen, genießt Gruppeninteraktionen und hast ein positives Selbstbild.",
        },
      },
      facets: [
        { code: "social_self_esteem", label: "Social Self-Esteem", labelByLocale: { en: "Social Self-Esteem", hu: "Társas önértékelés", de: "Soziales Selbstwertgefühl" } },
        { code: "social_boldness", label: "Social Boldness", labelByLocale: { en: "Social Boldness", hu: "Társas bátorság", de: "Soziale Kühnheit" } },
        { code: "sociability", label: "Sociability", labelByLocale: { en: "Sociability", hu: "Társaságkedvelés", de: "Geselligkeit" } },
        { code: "liveliness", label: "Liveliness", labelByLocale: { en: "Liveliness", hu: "Élénkség", de: "Lebhaftigkeit" } },
      ],
    },
    {
      code: "A",
      label: "Agreeableness",
      labelByLocale: {
        en: "Agreeableness",
        hu: "Barátságosság",
        de: "Verträglichkeit",
      },
      color: "#34D399",
      description: "Measures your tendency to forgive, cooperate with others, and control your anger when treated badly.",
      descriptionByLocale: {
        en: "Measures your tendency to forgive, cooperate with others, and control your anger when treated badly.",
        hu: "A megbocsátás, az együttműködés és a harag kezelésének hajlandóságát méri a másokkal való érintkezésben.",
        de: "Misst deine Neigung, anderen zu vergeben, zu kooperieren und Ärger in schwierigen Situationen zu kontrollieren.",
      },
      insights: {
        low: "You tend to hold grudges, judge others critically, defend your point of view stubbornly, and feel anger readily in response to mistreatment.",
        mid: "You can cooperate and compromise with others, while still defending your position when needed.",
        high: "You forgive easily, are lenient toward others, willing to cooperate and compromise, and rarely lose your temper.",
      },
      insightsByLocale: {
        en: {
          low: "You tend to hold grudges, judge others critically, defend your point of view stubbornly, and feel anger readily in response to mistreatment.",
          mid: "You can cooperate and compromise with others, while still defending your position when needed.",
          high: "You forgive easily, are lenient toward others, willing to cooperate and compromise, and rarely lose your temper.",
        },
        hu: {
          low: "Hajlamos vagy haragot tartani, kritikusan ítéled meg mások hibáit, makacsan véded az álláspontodat, és könnyen felgerjedsz.",
          mid: "Tudsz együttműködni és kompromisszumot kötni, miközben szükség esetén megvédeni az álláspontodat.",
          high: "Könnyen megbocsátasz, elnéző vagy mások iránt, hajlandó vagy együttműködni, és ritkán veszíted el a türelmedet.",
        },
        de: {
          low: "Du neigst dazu, Groll zu hegen, andere kritisch zu beurteilen, deinen Standpunkt stur zu verteidigen und bei Fehlbehandlung schnell wütend zu werden.",
          mid: "Du kannst kooperieren und Kompromisse eingehen, während du bei Bedarf deinen Standpunkt verteidigst.",
          high: "Du vergibst leicht, bist anderen gegenüber nachsichtig, zur Zusammenarbeit bereit und verlierst selten die Geduld.",
        },
      },
      facets: [
        { code: "forgiveness", label: "Forgiveness", labelByLocale: { en: "Forgiveness", hu: "Megbocsátás", de: "Vergebung" } },
        { code: "gentleness", label: "Gentleness", labelByLocale: { en: "Gentleness", hu: "Szelídség", de: "Sanftmut" } },
        { code: "flexibility", label: "Flexibility", labelByLocale: { en: "Flexibility", hu: "Rugalmasság", de: "Flexibilität" } },
        { code: "patience", label: "Patience", labelByLocale: { en: "Patience", hu: "Türelem", de: "Geduld" } },
      ],
    },
    {
      code: "C",
      label: "Conscientiousness",
      labelByLocale: {
        en: "Conscientiousness",
        hu: "Lelkiismeretesség",
        de: "Gewissenhaftigkeit",
      },
      color: "#A78BFA",
      description: "Measures how organized, diligent, thorough, and deliberate you are in pursuing your goals.",
      descriptionByLocale: {
        en: "Measures how organized, diligent, thorough, and deliberate you are in pursuing your goals.",
        hu: "Azt méri, mennyire szervezett, szorgalmas, aprólékos és megfontolt vagy a céljaid elérésében.",
        de: "Misst, wie organisiert, fleißig, gründlich und überlegt du bei der Verfolgung deiner Ziele bist.",
      },
      insights: {
        low: "You prefer a spontaneous approach — less concerned with order, tend to avoid difficult goals, and may act on impulse rather than reflection.",
        mid: "You execute tasks reliably and can adapt to changes without being overly perfectionist or rigid.",
        high: "You organize your time and surroundings carefully, work toward goals with discipline, strive for accuracy, and deliberate carefully before deciding.",
      },
      insightsByLocale: {
        en: {
          low: "You prefer a spontaneous approach — less concerned with order, tend to avoid difficult goals, and may act on impulse rather than reflection.",
          mid: "You execute tasks reliably and can adapt to changes without being overly perfectionist or rigid.",
          high: "You organize your time and surroundings carefully, work toward goals with discipline, strive for accuracy, and deliberate carefully before deciding.",
        },
        hu: {
          low: "Inkább spontán megközelítést preferálsz: kevésbé foglalkoztat a rend, hajlamos vagy a nehéz célokat kerülni, és impulzusok alapján döntesz.",
          mid: "Megbízhatóan hajtod végre a feladatokat és képes vagy alkalmazkodni a változásokhoz anélkül, hogy tökéletességre törekednél.",
          high: "Gondosan szervezed az idődet és a környezetedet, fegyelmezetten dolgozol a céljaidért, pontosságra törekedve, és döntés előtt alaposan mérlegelsz.",
        },
        de: {
          low: "Du bevorzugst einen spontanen Ansatz — wenig besorgt um Ordnung, meidest schwierige Ziele und handelst eher aus dem Bauch heraus.",
          mid: "Du erledigst Aufgaben zuverlässig und kannst dich anpassen, ohne dabei übertrieben perfektionistisch zu sein.",
          high: "Du organisierst Zeit und Umgebung sorgfältig, arbeitest diszipliniert auf deine Ziele hin, strebst nach Genauigkeit und überlegst vor Entscheidungen.",
        },
      },
      facets: [
        { code: "organization", label: "Organization", labelByLocale: { en: "Organization", hu: "Szervezettség", de: "Organisation" } },
        { code: "diligence", label: "Diligence", labelByLocale: { en: "Diligence", hu: "Szorgalom", de: "Fleiß" } },
        { code: "perfectionism", label: "Perfectionism", labelByLocale: { en: "Perfectionism", hu: "Perfekcionizmus", de: "Perfektionismus" } },
        { code: "prudence", label: "Prudence", labelByLocale: { en: "Prudence", hu: "Megfontoltság", de: "Besonnenheit" } },
      ],
    },
    {
      code: "O",
      label: "Openness",
      labelByLocale: {
        en: "Openness",
        hu: "Nyitottság",
        de: "Offenheit",
      },
      color: "#38BDF8",
      description: "Measures your intellectual curiosity, creativity, and attraction to art, nature, unusual ideas, and new experiences.",
      descriptionByLocale: {
        en: "Measures your intellectual curiosity, creativity, and attraction to art, nature, unusual ideas, and new experiences.",
        hu: "Az intellektuális kíváncsiságot, a kreativitást és a szokatlan ötletek, a művészet és az új élmények iránti vonzódást méri.",
        de: "Misst intellektuelle Neugier, Kreativität sowie die Anziehungskraft von Kunst, Natur, ungewöhnlichen Ideen und neuen Erfahrungen.",
      },
      insights: {
        low: "You tend to be unimpressed by art, feel little intellectual curiosity, avoid creative pursuits, and feel little attraction toward unconventional ideas.",
        mid: "You are open to some new ideas and creative experiences, while remaining grounded in practical thinking.",
        high: "You are drawn to beauty in art and nature, highly curious across many domains, imaginative in daily life, and interested in unusual or unconventional ideas.",
      },
      insightsByLocale: {
        en: {
          low: "You tend to be unimpressed by art, feel little intellectual curiosity, avoid creative pursuits, and feel little attraction toward unconventional ideas.",
          mid: "You are open to some new ideas and creative experiences, while remaining grounded in practical thinking.",
          high: "You are drawn to beauty in art and nature, highly curious across many domains, imaginative in daily life, and interested in unusual or unconventional ideas.",
        },
        hu: {
          low: "Nem ragadnak el különösebben a műalkotások, kevés szellemi kíváncsiságot érzel, kerülöd a kreatív tevékenységeket, és nem vonzanak a szokatlan ötletek.",
          mid: "Nyitott vagy néhány új ötletre és kreatív élményre, miközben a gyakorlatias gondolkodásban is maradasz.",
          high: "Vonzódsz a természet és a művészet szépségéhez, rendkívül kíváncsi vagy, képzelőerőd gazdag, és érdekesnek találod a szokatlan gondolatokat.",
        },
        de: {
          low: "Kunstwerke beeindrucken dich wenig, du verspürst geringe intellektuelle Neugier, meidest kreative Tätigkeiten und zeigst wenig Interesse an unkonventionellen Ideen.",
          mid: "Du bist offen für einige neue Ideen und kreative Erfahrungen, bleibst aber im praktischen Denken verwurzelt.",
          high: "Du wirst von Schönheit in Kunst und Natur angezogen, bist in vielen Bereichen sehr neugierig, fantasievoll im Alltag und interessiert an ungewöhnlichen Ideen.",
        },
      },
      facets: [
        { code: "aesthetic_appreciation", label: "Aesthetic Appreciation", labelByLocale: { en: "Aesthetic Appreciation", hu: "Esztétikai fogékonyság", de: "Ästhetisches Empfinden" } },
        { code: "inquisitiveness", label: "Inquisitiveness", labelByLocale: { en: "Inquisitiveness", hu: "Kíváncsiság", de: "Wissbegier" } },
        { code: "creativity", label: "Creativity", labelByLocale: { en: "Creativity", hu: "Kreativitás", de: "Kreativität" } },
        { code: "unconventionality", label: "Unconventionality", labelByLocale: { en: "Unconventionality", hu: "Eredetiség", de: "Unkonventionalität" } },
      ],
    },
  ],
  questions: [
    {
      id: 1,
      dimension: "O",
      facet: "aesthetic_appreciation",
      text: "I would be quite bored by a visit to an art gallery.",
      textByLocale: {
        hu: "Meglehetősen untatna egy képtár meglátogatása.",
        en: "I would be quite bored by a visit to an art gallery.",
        de: "Der Besuch einer Kunstausstellung würde mich ziemlich langweilen.",
      },
      textObserver: "He/she would be quite bored by a visit to an art gallery.",
      textObserverByLocale: {
        en: "He/she would be quite bored by a visit to an art gallery.",
        hu: "Meglehetősen untatná egy képtár meglátogatása.",
        de: "Der Besuch einer Kunstausstellung würde ihn/sie ziemlich langweilen.",
      },
      reversed: true,
    },
    {
      id: 2,
      dimension: "C",
      facet: "organization",
      text: "I plan ahead and organize things, to avoid scrambling at the last minute.",
      textByLocale: {
        hu: "A dolgaimat előre eltervezem, hogy elkerüljem az utolsó percben való kapkodást.",
        en: "I plan ahead and organize things, to avoid scrambling at the last minute.",
        de: "Ich plane im Voraus und organisiere, damit in letzter Minute kein Zeitdruck aufkommt.",
      },
      textObserver: "He/she plans ahead and organizes things, to avoid scrambling at the last minute.",
      textObserverByLocale: {
        en: "He/she plans ahead and organizes things, to avoid scrambling at the last minute.",
        hu: "A dolgait előre eltervezi, hogy elkerülje az utolsó percben való kapkodást.",
        de: "Er/Sie plant im Voraus und organisiert, damit in letzter Minute kein Zeitdruck aufkommt.",
      },
    },
    {
      id: 3,
      dimension: "A",
      facet: "forgiveness",
      text: "I rarely hold a grudge, even against people who have badly wronged me.",
      textByLocale: {
        hu: "Még azokkal szemben sem vagyok haragtartó, akik csúnyán megbántottak.",
        en: "I rarely hold a grudge, even against people who have badly wronged me.",
        de: "Ich habe selten Wut im Bauch, nicht mal gegen Leute, die mich sehr ungerecht behandelt haben.",
      },
      textObserver: "He/she rarely holds a grudge, even against people who have badly wronged him/her.",
      textObserverByLocale: {
        en: "He/she rarely holds a grudge, even against people who have badly wronged him/her.",
        hu: "Még azokkal szemben sem haragtartó, akik csúnyán megbántották.",
        de: "Er/Sie hat selten Wut im Bauch, nicht mal gegen Leute, die ihn/sie sehr ungerecht behandelt haben.",
      },
    },
    {
      id: 4,
      dimension: "X",
      facet: "social_self_esteem",
      text: "I feel reasonably satisfied with myself overall.",
      textByLocale: {
        hu: "Alapjában véve úgy érzem, hogy elégedett vagyok magammal.",
        en: "I feel reasonably satisfied with myself overall.",
        de: "Im Allgemeinen bin ich mit mir ziemlich zufrieden.",
      },
      textObserver: "He/she feels reasonably satisfied with himself/herself overall.",
      textObserverByLocale: {
        en: "He/she feels reasonably satisfied with himself/herself overall.",
        hu: "Alapjában véve elégedett magával.",
        de: "Im Allgemeinen ist er/sie mit sich ziemlich zufrieden.",
      },
    },
    {
      id: 5,
      dimension: "E",
      facet: "fearfulness",
      text: "I would feel afraid if I had to travel in bad weather conditions.",
      textByLocale: {
        hu: "Nyugtalansággal töltene el, ha rossz időjárási körülmények között kellene utazást vállalnom.",
        en: "I would feel afraid if I had to travel in bad weather conditions.",
        de: "Ich hätte Angst, wenn ich bei schlechten Wetterbedingungen verreisen müsste.",
      },
      textObserver: "He/she would feel afraid if he/she had to travel in bad weather conditions.",
      textObserverByLocale: {
        en: "He/she would feel afraid if he/she had to travel in bad weather conditions.",
        hu: "Nyugtalansággal töltené el, ha rossz időjárási körülmények között kellene utazást vállalnia.",
        de: "Er/Sie hätte Angst, wenn er/sie bei schlechten Wetterbedingungen verreisen müsste.",
      },
    },
    {
      id: 6,
      dimension: "H",
      facet: "sincerity",
      text: "I wouldn't use flattery to get a raise or promotion at work, even if I thought it would succeed.",
      textByLocale: {
        hu: "Akkor sem hízelegnék a főnökömnek, ha tudnám, fizetésemelést vagy előrelépest érnék el vele.",
        en: "I wouldn't use flattery to get a raise or promotion at work, even if I thought it would succeed.",
        de: "Ich würde keine Schmeicheleien benutzen, um eine Gehaltserhöhung zu bekommen oder befördert zu werden, auch wenn ich wüsste, dass es erfolgreich wäre. Bitte wenden…",
      },
      textObserver: "He/she wouldn't use flattery to get a raise or promotion at work, even if he/she thought it would succeed.",
      textObserverByLocale: {
        en: "He/she wouldn't use flattery to get a raise or promotion at work, even if he/she thought it would succeed.",
        hu: "Akkor sem hízelegne a főnökének, ha tudná, fizetésemelést vagy előrelépést érne el vele.",
        de: "Er/Sie würde keine Schmeicheleien benutzen, um eine Gehaltserhöhung zu bekommen oder befördert zu werden, auch wenn er/sie wüsste, dass es erfolgreich wäre.",
      },
    },
    {
      id: 7,
      dimension: "O",
      facet: "inquisitiveness",
      text: "I'm interested in learning about the history and politics of other countries.",
      textByLocale: {
        hu: "Érdekelnek más országok történelmi és politikai sajátosságai.",
        en: "I'm interested in learning about the history and politics of other countries.",
        de: "Ich bin daran interessiert, etwas über die Geschichte und Politik anderer Länder zu lernen.",
      },
      textObserver: "He/she is interested in learning about the history and politics of other countries.",
      textObserverByLocale: {
        en: "He/she is interested in learning about the history and politics of other countries.",
        hu: "Érdeklik más országok történelmi és politikai sajátosságai.",
        de: "Er/Sie ist daran interessiert, etwas über die Geschichte und Politik anderer Länder zu lernen.",
      },
    },
    {
      id: 8,
      dimension: "C",
      facet: "diligence",
      text: "I often push myself very hard when trying to achieve a goal.",
      textByLocale: {
        hu: "Céljaim elérésére gyakran minden erőmet bevetem.",
        en: "I often push myself very hard when trying to achieve a goal.",
        de: "Ich treibe mich oft selbst sehr stark an, wenn ich versuche, ein Ziel zu erreichen.",
      },
      textObserver: "He/she often pushes himself/herself very hard when trying to achieve a goal.",
      textObserverByLocale: {
        en: "He/she often pushes himself/herself very hard when trying to achieve a goal.",
        hu: "Céljai elérésére gyakran minden erejét beveti.",
        de: "Er/Sie treibt sich oft selbst sehr stark an, wenn er/sie versucht, ein Ziel zu erreichen.",
      },
    },
    {
      id: 9,
      dimension: "A",
      facet: "gentleness",
      text: "People sometimes tell me that I am too critical of others.",
      textByLocale: {
        hu: "Az ismerőseim gyakran állítják, hogy túl kritikus vagyok másokhoz.",
        en: "People sometimes tell me that I am too critical of others.",
        de: "Andere sagen mir manchmal, dass ich zu kritisch gegenüber anderen bin.",
      },
      textObserver: "People sometimes say that he/she is too critical of others.",
      textObserverByLocale: {
        en: "People sometimes say that he/she is too critical of others.",
        hu: "Az ismerősei gyakran állítják, hogy túl kritikus másokkal.",
        de: "Andere sagen ihm/ihr manchmal, dass er/sie zu kritisch gegenüber anderen ist.",
      },
      reversed: true,
    },
    {
      id: 10,
      dimension: "X",
      facet: "social_boldness",
      text: "I rarely express my opinions in group meetings.",
      textByLocale: {
        hu: "Csoportos megbeszéléseken ritkán adok hangot véleményemnek.",
        en: "I rarely express my opinions in group meetings.",
        de: "Bei Gruppentreffen sage ich nur selten meine Meinung.",
      },
      textObserver: "He/she rarely expresses his/her opinions in group meetings.",
      textObserverByLocale: {
        en: "He/she rarely expresses his/her opinions in group meetings.",
        hu: "Csoportos megbeszéléseken ritkán ad hangot véleményének.",
        de: "Bei Gruppentreffen sagt er/sie nur selten seine/ihre Meinung.",
      },
      reversed: true,
    },
    {
      id: 11,
      dimension: "E",
      facet: "anxiety",
      text: "I sometimes can't help worrying about little things.",
      textByLocale: {
        hu: "Néha nem tudom megállni, hogy ne aggodalmaskodjak apróságokon.",
        en: "I sometimes can't help worrying about little things.",
        de: "Ich kann manchmal nichts dagegen machen, dass ich mir über kleine Dinge Sorgen mache.",
      },
      textObserver: "He/she worries about little things.",
      textObserverByLocale: {
        en: "He/she worries about little things.",
        hu: "Néha nem tudja megállni, hogy ne aggodalmaskodjon apróságokon.",
        de: "Er/Sie kann manchmal nichts dagegen machen, dass er/sie sich über kleine Dinge Sorgen macht.",
      },
    },
    {
      id: 12,
      dimension: "H",
      facet: "fairness",
      text: "If I knew that I could never get caught, I would be willing to steal a million dollars.",
      textByLocale: {
        hu: "Ha tudnám, hogy sosem kapnak el, kész lennék egy millió dollárt vagy eurót ellopni.",
        en: "If I knew that I could never get caught, I would be willing to steal a million dollars.",
        de: "Wenn ich wüsste, dass ich niemals erwischt werde, wäre ich bereit, eine Million zu stehlen.",
      },
      textObserver: "If he/she knew that he/she could never get caught, he/she would be willing to steal a million dollars.",
      textObserverByLocale: {
        en: "If he/she knew that he/she could never get caught, he/she would be willing to steal a million dollars.",
        hu: "Ha tudná, hogy sosem kapják el, kész lenne egy millió dollárt vagy eurót ellopni.",
        de: "Wenn er/sie wüsste, dass er/sie niemals erwischt wird, wäre er/sie bereit, eine Million zu stehlen.",
      },
      reversed: true,
    },
    {
      id: 13,
      dimension: "O",
      facet: "creativity",
      text: "I would enjoy creating a work of art, such as a novel, a song, or a painting.",
      textByLocale: {
        hu: "Szívesen alkotnék valami művészi munkát: egy regényt, zeneszámot, vagy festményt.",
        en: "I would enjoy creating a work of art, such as a novel, a song, or a painting.",
        de: "Ich würde es genießen, ein Kunstwerk zu schaffen, etwa einen Roman, ein Lied oder ein Gemälde.",
      },
      textObserver: "He/she would enjoy creating a work of art, such as a novel, a song, or a painting.",
      textObserverByLocale: {
        en: "He/she would enjoy creating a work of art, such as a novel, a song, or a painting.",
        hu: "Szívesen alkotna valami művészi munkát: egy regényt, zeneszámot vagy festményt.",
        de: "Er/Sie würde es genießen, ein Kunstwerk zu schaffen, etwa einen Roman, ein Lied oder ein Gemälde.",
      },
    },
    {
      id: 14,
      dimension: "C",
      facet: "perfectionism",
      text: "When working on something, I don't pay much attention to small details.",
      textByLocale: {
        hu: "Ha dolgozom valamin, nem igazán fordítok különös figyelmet az apró részletekre.",
        en: "When working on something, I don't pay much attention to small details.",
        de: "Wenn ich an irgendetwas arbeite, beachte ich kleine Details nicht allzu sehr.",
      },
      textObserver: "When working on something, he/she doesn't pay much attention to small details.",
      textObserverByLocale: {
        en: "When working on something, he/she doesn't pay much attention to small details.",
        hu: "Ha dolgozik valamin, nem igazán fordít különös figyelmet az apró részletekre.",
        de: "Wenn er/sie an irgendetwas arbeitet, beachtet er/sie kleine Details nicht allzu sehr.",
      },
      reversed: true,
    },
    {
      id: 15,
      dimension: "A",
      facet: "flexibility",
      text: "People sometimes tell me that I'm too stubborn.",
      textByLocale: {
        hu: "Az ismerőseim néha azt mondják, hogy túlzottan makacs vagyok.",
        en: "People sometimes tell me that I'm too stubborn.",
        de: "Andere sagen mir manchmal, dass ich zu dickköpfig bin.",
      },
      textObserver: "People sometimes think that he/she is too stubborn.",
      textObserverByLocale: {
        en: "People sometimes think that he/she is too stubborn.",
        hu: "Az ismerősei néha azt mondják, hogy túlzottan makacs.",
        de: "Andere sagen ihm/ihr manchmal, dass er/sie zu dickköpfig ist.",
      },
      reversed: true,
    },
    {
      id: 16,
      dimension: "X",
      facet: "sociability",
      text: "I prefer jobs that involve active social interaction to those that involve working alone.",
      textByLocale: {
        hu: "Inkább az olyan munkákat szeretem ahol emberekkel kell foglalkozni, mint ahol egyedül kell dolgozni.",
        en: "I prefer jobs that involve active social interaction to those that involve working alone.",
        de: "Ich ziehe Berufe, in denen man sich aktiv mit anderen Menschen auseinandersetzt solchen vor, in denen man alleine arbeitet.",
      },
      textObserver: "He/she prefers jobs that involve active social interaction to those that involve working alone.",
      textObserverByLocale: {
        en: "He/she prefers jobs that involve active social interaction to those that involve working alone.",
        hu: "Inkább az olyan munkákat szereti, ahol emberekkel kell foglalkozni.",
        de: "Er/Sie zieht Berufe vor, in denen man sich aktiv mit anderen Menschen auseinandersetzt.",
      },
    },
    {
      id: 17,
      dimension: "E",
      facet: "dependence",
      text: "When I suffer from a painful experience, I need someone to make me feel comfortable.",
      textByLocale: {
        hu: "Ha valami rossz történt velem, szükségem van valakire, aki megvígasztal.",
        en: "When I suffer from a painful experience, I need someone to make me feel comfortable.",
        de: "Wenn ich wegen einer schmerzvollen Erfahrung leide, brauche ich jemanden, der mich tröstet.",
      },
      textObserver: "When he/she suffers from a painful experience, he/she needs someone to make him/her feel comfortable.",
      textObserverByLocale: {
        en: "When he/she suffers from a painful experience, he/she needs someone to make him/her feel comfortable.",
        hu: "Ha valami rossz történt vele, szüksége van valakire, aki megvigasztalja.",
        de: "Wenn er/sie wegen einer schmerzvollen Erfahrung leidet, brauche er/sie jemanden, der ihn/sie tröstet.",
      },
    },
    {
      id: 18,
      dimension: "H",
      facet: "greed_avoidance",
      text: "Having a lot of money is not especially important to me.",
      textByLocale: {
        hu: "Nem igazán fontos nekem, hogy sok pénzem legyen.",
        en: "Having a lot of money is not especially important to me.",
        de: "Viel Geld zu haben ist nicht besonders wichtig für mich.",
      },
      textObserver: "Having a lot of money is not especially important to him/her.",
      textObserverByLocale: {
        en: "Having a lot of money is not especially important to him/her.",
        hu: "Nem igazán fontos neki, hogy sok pénze legyen.",
        de: "Viel Geld zu haben ist nicht besonders wichtig für ihn/sie.",
      },
    },
    {
      id: 19,
      dimension: "O",
      facet: "unconventionality",
      text: "I think that paying attention to radical ideas is a waste of time.",
      textByLocale: {
        hu: "A radikális nézetekkel való foglalkozás egyszerűen időpocsékolás.",
        en: "I think that paying attention to radical ideas is a waste of time.",
        de: "Ich denke, dass es Zeitverschwendung ist, radikalen Ideen Aufmerksamkeit zu schenken.",
      },
      textObserver: "He/she thinks that paying attention to radical ideas is a waste of time.",
      textObserverByLocale: {
        en: "He/she thinks that paying attention to radical ideas is a waste of time.",
        hu: "A radikális nézetekkel való foglalkozás szerinte egyszerűen időpocsékolás.",
        de: "Er/Sie denkt, dass es Zeitverschwendung ist, radikalen Ideen Aufmerksamkeit zu schenken.",
      },
      reversed: true,
    },
    {
      id: 20,
      dimension: "C",
      facet: "prudence",
      text: "I make decisions based on the feeling of the moment rather than on careful thought.",
      textByLocale: {
        hu: "Inkább a pillanatnyi érzelmeim, mint a gondos megfontolás vezet a döntéseimben.",
        en: "I make decisions based on the feeling of the moment rather than on careful thought.",
        de: "Ich treffe Entscheidungen eher aus dem Bauch heraus als durch sorgfältiges Nachdenken.",
      },
      textObserver: "He/she makes decisions based on the feeling of the moment rather than on careful thought.",
      textObserverByLocale: {
        en: "He/she makes decisions based on the feeling of the moment rather than on careful thought.",
        hu: "Inkább a pillanatnyi érzelmei vezetik a döntéseiben.",
        de: "Er/Sie trifft Entscheidungen eher aus dem Bauch heraus als durch sorgfältiges Nachdenken.",
      },
      reversed: true,
    },
    {
      id: 21,
      dimension: "A",
      facet: "patience",
      text: "People think of me as someone who has a quick temper.",
      textByLocale: {
        hu: "Az emberek robbanékony természetűnek tartanak.",
        en: "People think of me as someone who has a quick temper.",
        de: "Andere halten mich für jähzornig.",
      },
      textObserver: "People think of him/her as someone who has a quick temper.",
      textObserverByLocale: {
        en: "People think of him/her as someone who has a quick temper.",
        hu: "Az emberek robbanékony természetűnek tartják.",
        de: "Andere halten ihn/sie für jähzornig.",
      },
      reversed: true,
    },
    {
      id: 22,
      dimension: "X",
      facet: "liveliness",
      text: "On most days, I feel cheerful and optimistic.",
      textByLocale: {
        hu: "Többnyire vidám és optimista vagyok.",
        en: "On most days, I feel cheerful and optimistic.",
        de: "An den meisten Tagen bin ich fröhlich und optimistisch.",
      },
      textObserver: "On most days, he/she feels cheerful and optimistic.",
      textObserverByLocale: {
        en: "On most days, he/she feels cheerful and optimistic.",
        hu: "Többnyire vidám és optimista.",
        de: "An den meisten Tagen ist er/sie fröhlich und optimistisch.",
      },
    },
    {
      id: 23,
      dimension: "E",
      facet: "sentimentality",
      text: "I feel like crying when I see other people crying.",
      textByLocale: {
        hu: "Úgy érzem engem is elkap a sírás, ha másokat sírni látok.",
        en: "I feel like crying when I see other people crying.",
        de: "Ich könnte weinen, wenn ich andere Personen sehe, die weinen.",
      },
      textObserver: "He/she feels like crying when he/she sees other people crying.",
      textObserverByLocale: {
        en: "He/she feels like crying when he/she sees other people crying.",
        hu: "Úgy érzi, őt is elkapja a sírás, ha másokat sírni lát.",
        de: "Er/Sie könnte weinen, wenn er/sie andere Personen sieht, die weinen.",
      },
    },
    {
      id: 24,
      dimension: "H",
      facet: "modesty",
      text: "I think that I am entitled to more respect than the average person is.",
      textByLocale: {
        hu: "Úgy érzem, hogy több elismerés jár nekem mint egy átlagembernek.",
        en: "I think that I am entitled to more respect than the average person is.",
        de: "Ich denke, dass ich mehr Respekt verdiene als ein durchschnittlicher Mensch.",
      },
      textObserver: "He/she thinks that he/she is entitled to more respect than the average person is.",
      textObserverByLocale: {
        en: "He/she thinks that he/she is entitled to more respect than the average person is.",
        hu: "Úgy érzi, több elismerés jár neki, mint egy átlagembernek.",
        de: "Er/Sie denkt, dass er/sie mehr Respekt verdient als ein durchschnittlicher Mensch.",
      },
      reversed: true,
    },
    {
      id: 25,
      dimension: "O",
      facet: "aesthetic_appreciation",
      text: "If I had the opportunity, I would like to attend a classical music concert.",
      textByLocale: {
        hu: "Ha az alkalom úgy hozná, szívesen elmennék egy klasszikus koncertre.",
        en: "If I had the opportunity, I would like to attend a classical music concert.",
        de: "Wenn ich die Gelegenheit dazu hätte, würde ich gerne ein Konzert mit klassischer Musik besuchen.",
      },
      textObserver: "If he/she had the opportunity, he/she would like to attend a classical music concert.",
      textObserverByLocale: {
        en: "If he/she had the opportunity, he/she would like to attend a classical music concert.",
        hu: "Szívesen elmenne egy klasszikus koncertre.",
        de: "Er/Sie würde gerne ein Konzert mit klassischer Musik besuchen.",
      },
    },
    {
      id: 26,
      dimension: "C",
      facet: "organization",
      text: "When working, I sometimes have difficulties due to being disorganized.",
      textByLocale: {
        hu: "A munkámban néha hátráltat, hogy nem vagyok jól organizált.",
        en: "When working, I sometimes have difficulties due to being disorganized.",
        de: "Wenn ich arbeite, habe ich manchmal Schwierigkeiten, weil ich unorganisiert bin.",
      },
      textObserver: "When working, he/she sometimes has difficulties due to being disorganized.",
      textObserverByLocale: {
        en: "When working, he/she sometimes has difficulties due to being disorganized.",
        hu: "A munkájában néha hátráltatja, hogy nem jól szervezett.",
        de: "Wenn er/sie arbeitet, hat er/sie manchmal Schwierigkeiten, weil er/sie unorganisiert ist.",
      },
      reversed: true,
    },
    {
      id: 27,
      dimension: "A",
      facet: "forgiveness",
      text: "My attitude toward people who have treated me badly is \"forgive and forget\".",
      textByLocale: {
        hu: "Ha valaki rosszul bánt velem, képes vagyok megbocsátani és a feledés fátylát boritani a történtekre.",
        en: "My attitude toward people who have treated me badly is \"forgive and forget\".",
        de: "Meine Einstellung gegenüber Personen, die mich schlecht behandelt haben, ist \\\"vergeben und vergessen\\\".",
      },
      textObserver: "His/her attitude toward people who have treated him/her badly is \"forgive and forget\".",
      textObserverByLocale: {
        en: "His/her attitude toward people who have treated him/her badly is \"forgive and forget\".",
        hu: "Képes megbocsátani és feledni.",
        de: "Seine/Ihre Einstellung ist \u201Evergeben und vergessen\u201C.",
      },
    },
    {
      id: 28,
      dimension: "X",
      facet: "social_self_esteem",
      text: "I feel that I am an unpopular person.",
      textByLocale: {
        hu: "Úgy érzem, hogy népszerűtlen vagyok.",
        en: "I feel that I am an unpopular person.",
        de: "Ich bin der Meinung, dass ich nicht beliebt bin.",
      },
      textObserver: "He/she feels that he/she is an unpopular person.",
      textObserverByLocale: {
        en: "He/she feels that he/she is an unpopular person.",
        hu: "Úgy érzi, hogy népszerűtlen.",
        de: "Er/Sie ist der Meinung, dass er/sie nicht beliebt ist.",
      },
      reversed: true,
    },
    {
      id: 29,
      dimension: "E",
      facet: "fearfulness",
      text: "When it comes to physical danger, I am very fearful.",
      textByLocale: {
        hu: "Testi épsegemet veszélyeztető helyzetekben nagyon félek.",
        en: "When it comes to physical danger, I am very fearful.",
        de: "Wenn es um körperliche Gefahren geht, bin ich sehr ängstlich.",
      },
      textObserver: "When it comes to physical danger, he/she is very fearful.",
      textObserverByLocale: {
        en: "When it comes to physical danger, he/she is very fearful.",
        hu: "Testi épségét veszélyeztető helyzetekben nagyon fél.",
        de: "Wenn es um körperliche Gefahren geht, ist er/sie sehr ängstlich.",
      },
    },
    {
      id: 30,
      dimension: "H",
      facet: "sincerity",
      text: "If I want something from someone, I will laugh at that person's worst jokes.",
      textByLocale: {
        hu: "Ha valakitől valamit akarok, akkor még a faviccein is képes vagyok nevetni.",
        en: "If I want something from someone, I will laugh at that person's worst jokes.",
        de: "Wenn ich von jemandem etwas will, lache ich auch noch über dessen schlechteste Witze.",
      },
      textObserver: "If he/she wants something from someone, he/she will laugh at that person's worst jokes.",
      textObserverByLocale: {
        en: "If he/she wants something from someone, he/she will laugh at that person's worst jokes.",
        hu: "Ha valakitől valamit akar, még a rossz viccein is nevet.",
        de: "Wenn er/sie von jemandem etwas will, lacht er/sie auch über schlechte Witze.",
      },
      reversed: true,
    },
    {
      id: 31,
      dimension: "O",
      facet: "inquisitiveness",
      text: "I've never really enjoyed looking through an encyclopedia.",
      textByLocale: {
        hu: "Igazándiból még sohasem lapozgattam élvezettel egy lexikonban.",
        en: "I've never really enjoyed looking through an encyclopedia.",
        de: "Ich habe es noch nie wirklich gemocht, eine Enzyklopädie durchzublättern.",
      },
      textObserver: "He/she has never really enjoyed looking through an encyclopedia.",
      textObserverByLocale: {
        en: "He/she has never really enjoyed looking through an encyclopedia.",
        hu: "Valószínűleg még sohasem lapozgatott élvezettel egy lexikonban.",
        de: "Er/Sie hat es noch nie wirklich gemocht, eine Enzyklopädie durchzublättern.",
      },
      reversed: true,
    },
    {
      id: 32,
      dimension: "C",
      facet: "diligence",
      text: "I do only the minimum amount of work needed to get by.",
      textByLocale: {
        hu: "Ami a munkát illeti, csak a legszükségesebb erőbedobással dolgozom.",
        en: "I do only the minimum amount of work needed to get by.",
        de: "Ich arbeite nur so viel wie nötig, um gerade so durchzukommen.",
      },
      textObserver: "He/she does only the minimum amount of work needed to get by.",
      textObserverByLocale: {
        en: "He/she does only the minimum amount of work needed to get by.",
        hu: "Csak a legszükségesebb erőbedobással dolgozik.",
        de: "Er/Sie arbeitet nur so viel wie nötig, um gerade so durchzukommen.",
      },
      reversed: true,
    },
    {
      id: 33,
      dimension: "A",
      facet: "gentleness",
      text: "I tend to be lenient in judging other people.",
      textByLocale: {
        hu: "Jobbára jóindulattal ítélkezem mások felett.",
        en: "I tend to be lenient in judging other people.",
        de: "Ich neige dazu, nachsichtig zu sein, wenn ich andere beurteile.",
      },
      textObserver: "He/she tends to be lenient in judging other people.",
      textObserverByLocale: {
        en: "He/she tends to be lenient in judging other people.",
        hu: "Jobbára jóindulattal ítélkezik mások felett.",
        de: "Er/Sie neigt dazu, nachsichtig zu sein.",
      },
    },
    {
      id: 34,
      dimension: "X",
      facet: "social_boldness",
      text: "In social situations, I'm usually the one who makes the first move.",
      textByLocale: {
        hu: "Társas helyzetekben általában én vagyok az, aki beszélgetést kezdeményez.",
        en: "In social situations, I'm usually the one who makes the first move.",
        de: "In sozialen Situationen bin ich gewöhnlich der, der den ersten Schritt macht.",
      },
      textObserver: "In social situations, he/she is usually the one who makes the first move.",
      textObserverByLocale: {
        en: "In social situations, he/she is usually the one who makes the first move.",
        hu: "Társas helyzetekben általában ő kezdeményez.",
        de: "In sozialen Situationen macht er/sie gewöhnlich den ersten Schritt.",
      },
    },
    {
      id: 35,
      dimension: "E",
      facet: "anxiety",
      text: "I worry a lot less than most people do.",
      textByLocale: {
        hu: "Sokkal kevesebbet aggodalmaskodom mint általában a többi ember szokott.",
        en: "I worry a lot less than most people do.",
        de: "Ich mache mir viel weniger Sorgen als die meisten Leute.",
      },
      textObserver: "He/she worries a lot less than most people do.",
      textObserverByLocale: {
        en: "He/she worries a lot less than most people do.",
        hu: "Sokkal kevesebbet aggódik, mint a legtöbb ember.",
        de: "Er/Sie macht sich viel weniger Sorgen als die meisten Leute.",
      },
      reversed: true,
    },
    {
      id: 36,
      dimension: "H",
      facet: "fairness",
      text: "I would never accept a bribe, even if it were very large.",
      textByLocale: {
        hu: "Sosem hagynám magam megvesztegetni, mindegy mekkora is lenne az az ajánlat.",
        en: "I would never accept a bribe, even if it were very large.",
        de: "Ich würde niemals Bestechungsgeld annehmen, auch wenn es sehr viel wäre. Bitte wenden…",
      },
      textObserver: "He/she would never accept a bribe, even if it were very large.",
      textObserverByLocale: {
        en: "He/she would never accept a bribe, even if it were very large.",
        hu: "Sosem hagyná magát megvesztegetni.",
        de: "Er/Sie würde niemals Bestechungsgeld annehmen.",
      },
    },
    {
      id: 37,
      dimension: "O",
      facet: "creativity",
      text: "People have often told me that I have a good imagination.",
      textByLocale: {
        hu: "Sokszor mondták már nekem, hogy jó a fantáziám.",
        en: "People have often told me that I have a good imagination.",
        de: "Man hat mir schon oft gesagt, dass ich eine gute Vorstellungskraft habe.",
      },
      textObserver: "He/she has a good imagination.",
      textObserverByLocale: {
        en: "He/she has a good imagination.",
        hu: "Jó a fantáziája.",
        de: "Er/Sie hat eine gute Vorstellungskraft.",
      },
    },
    {
      id: 38,
      dimension: "C",
      facet: "perfectionism",
      text: "I always try to be accurate in my work, even at the expense of time.",
      textByLocale: {
        hu: "A munkámban megpróbálok még akkor is mindig precíznek lenni, ha ez többletidőmbe kerül.",
        en: "I always try to be accurate in my work, even at the expense of time.",
        de: "Ich versuche immer, fehlerfrei zu arbeiten, auch wenn es Zeit kostet.",
      },
      textObserver: "He/she always tries to be accurate in his/her work, even at the expense of time.",
      textObserverByLocale: {
        en: "He/she always tries to be accurate in his/her work, even at the expense of time.",
        hu: "Mindig precíz próbál lenni a munkájában.",
        de: "Er/Sie versucht immer, fehlerfrei zu arbeiten.",
      },
    },
    {
      id: 39,
      dimension: "A",
      facet: "flexibility",
      text: "I am usually quite flexible in my opinions when people disagree with me.",
      textByLocale: {
        hu: "Általában könnyen megváltoztatom a véleményem, ha az emberek nem értenek vele egyet.",
        en: "I am usually quite flexible in my opinions when people disagree with me.",
        de: "Ich bin gewöhnlich ziemlich flexibel in meinen Ansichten, wenn andere Leute mir nicht zustimmen.",
      },
      textObserver: "He/she is usually quite flexible in his/her opinions.",
      textObserverByLocale: {
        en: "He/she is usually quite flexible in his/her opinions.",
        hu: "Általában könnyen megváltoztatja a véleményét.",
        de: "Er/Sie ist gewöhnlich flexibel in seinen/ihren Ansichten.",
      },
    },
    {
      id: 40,
      dimension: "X",
      facet: "sociability",
      text: "The first thing that I always do in a new place is to make friends.",
      textByLocale: {
        hu: "Ha egy új helyre kerülök, hamarosan új barátságokat is kötök.",
        en: "The first thing that I always do in a new place is to make friends.",
        de: "Das erste, was ich an einem neuen Ort tue, ist, Freundschaften zu schließen.",
      },
      textObserver: "The first thing that he/she always does in a new place is to make friends.",
      textObserverByLocale: {
        en: "The first thing that he/she always does in a new place is to make friends.",
        hu: "Új helyen hamar barátságokat köt.",
        de: "Das erste, was er/sie tut, ist, Freundschaften zu schließen.",
      },
    },
    {
      id: 41,
      dimension: "E",
      facet: "dependence",
      text: "I can handle difficult situations without needing emotional support from anyone else.",
      textByLocale: {
        hu: "Nehezebb helyzetekkel is elboldogulok anélkül, hogy érzelmi támogatásra lenne szükségem.",
        en: "I can handle difficult situations without needing emotional support from anyone else.",
        de: "Ich kann mit schwierigen Situationen umgehen, ohne dass ich emotionale Unterstützung von irgendjemandem brauche.",
      },
      textObserver: "He/she can handle difficult situations without needing emotional support.",
      textObserverByLocale: {
        en: "He/she can handle difficult situations without needing emotional support.",
        hu: "Nehezebb helyzetekkel is elboldogul támogatás nélkül.",
        de: "Er/Sie kann schwierige Situationen ohne emotionale Unterstützung bewältigen.",
      },
      reversed: true,
    },
    {
      id: 42,
      dimension: "H",
      facet: "greed_avoidance",
      text: "I would get a lot of pleasure from owning expensive luxury goods.",
      textByLocale: {
        hu: "Nagyon tudnék neki örülni, ha méregdrága, luxus cuccaim lennének.",
        en: "I would get a lot of pleasure from owning expensive luxury goods.",
        de: "Es würde mir viel Freude bereiten, teure Luxusgüter zu besitzen. Bitte wenden…",
      },
      textObserver: "He/she would get pleasure from owning expensive luxury goods.",
      textObserverByLocale: {
        en: "He/she would get pleasure from owning expensive luxury goods.",
        hu: "Örülne drága luxuscikkek birtoklásának.",
        de: "Er/Sie hätte Freude an teuren Luxusgütern.",
      },
      reversed: true,
    },
    {
      id: 43,
      dimension: "O",
      facet: "unconventionality",
      text: "I like people who have unconventional views.",
      textByLocale: {
        hu: "Nekem szimpatikusak azok az emberek, akiknek eredeti, az átlagtól eltérő nézeteik vannak.",
        en: "I like people who have unconventional views.",
        de: "Ich mag Leute, die unkonventionelle Ideen haben.",
      },
      textObserver: "He/she likes people who have unconventional views.",
      textObserverByLocale: {
        en: "He/she likes people who have unconventional views.",
        hu: "Szimpatikusak neki az eredeti nézeteket valló emberek.",
        de: "Er/Sie mag Leute mit unkonventionellen Ideen.",
      },
    },
    {
      id: 44,
      dimension: "C",
      facet: "prudence",
      text: "I make a lot of mistakes because I don't think before I act.",
      textByLocale: {
        hu: "Sok hibát követek el, mert előbb cselekszem és csak aztán gondolkodom.",
        en: "I make a lot of mistakes because I don't think before I act.",
        de: "Ich mache viele Fehler, weil ich nicht nachdenke, bevor ich handele.",
      },
      textObserver: "He/she makes mistakes because he/she doesn't think before acting.",
      textObserverByLocale: {
        en: "He/she makes mistakes because he/she doesn't think before acting.",
        hu: "Sok hibát követ el, mert előbb cselekszik.",
        de: "Er/Sie macht viele Fehler, weil er/sie nicht nachdenkt.",
      },
      reversed: true,
    },
    {
      id: 45,
      dimension: "A",
      facet: "patience",
      text: "Most people tend to get angry more quickly than I do.",
      textByLocale: {
        hu: "A legtöbb embert könnyebb felbosszantani mint engem.",
        en: "Most people tend to get angry more quickly than I do.",
        de: "Die meisten Leute werden schneller ärgerlich als ich.",
      },
      textObserver: "Most people get angry more quickly than he/she does.",
      textObserverByLocale: {
        en: "Most people get angry more quickly than he/she does.",
        hu: "A legtöbb embert könnyebb felbosszantani, mint őt.",
        de: "Die meisten Leute werden schneller ärgerlich.",
      },
    },
    {
      id: 46,
      dimension: "X",
      facet: "liveliness",
      text: "Most people are more upbeat and dynamic than I generally am.",
      textByLocale: {
        hu: "A legtöbb ember dinamikusabb és élettelibb mint én vagyok.",
        en: "Most people are more upbeat and dynamic than I generally am.",
        de: "Die meisten Leute sind aufgedrehter und dynamischer als ich es im Allgemeinen bin.",
      },
      textObserver: "Most people are more upbeat and dynamic than he/she.",
      textObserverByLocale: {
        en: "Most people are more upbeat and dynamic than he/she.",
        hu: "A legtöbb ember dinamikusabb nála.",
        de: "Die meisten Leute sind dynamischer.",
      },
      reversed: true,
    },
    {
      id: 47,
      dimension: "E",
      facet: "sentimentality",
      text: "I feel strong emotions when someone close to me is going away for a long time.",
      textByLocale: {
        hu: "Nagyon megindít, ha hozzám közelálló személyektől kell hosszútávra elbúcsúznom.",
        en: "I feel strong emotions when someone close to me is going away for a long time.",
        de: "Ich fühle starke Emotionen, wenn jemand, der mir nahe steht, für eine längere Zeit weggeht.",
      },
      textObserver: "He/she feels strong emotions when someone close goes away.",
      textObserverByLocale: {
        en: "He/she feels strong emotions when someone close goes away.",
        hu: "Nagyon megindítja a hosszú búcsú.",
        de: "Er/Sie fühlt starke Emotionen beim Abschied.",
      },
    },
    {
      id: 48,
      dimension: "H",
      facet: "modesty",
      text: "I want people to know that I am an important person of high status.",
      textByLocale: {
        hu: "Azt szeretném, ha mások fontos és magas pozicióban lévő embernek tartanának.",
        en: "I want people to know that I am an important person of high status.",
        de: "Ich will, dass alle wissen, dass ich eine wichtige angesehene Person bin.",
      },
      textObserver: "He/she wants people to know he/she is important.",
      textObserverByLocale: {
        en: "He/she wants people to know he/she is important.",
        hu: "Szeretné, ha fontos embernek tartanák.",
        de: "Er/Sie will als wichtige Person gelten.",
      },
      reversed: true,
    },
    {
      id: 49,
      dimension: "O",
      facet: "creativity",
      text: "I don't think of myself as the artistic or creative type.",
      textByLocale: {
        hu: "Nem hiszem, hogy én egy kreatív vagy művészileg tehetséges típus vagyok.",
        en: "I don't think of myself as the artistic or creative type.",
        de: "Ich halte mich nicht für einen künstlerischen oder kreativen Menschen.",
      },
      textObserver: "I don't think of him/her as artistic.",
      textObserverByLocale: {
        en: "I don't think of him/her as artistic.",
        hu: "Nem gondolom művészi típusnak.",
        de: "Er/Sie hält sich nicht für künstlerisch.",
      },
      reversed: true,
    },
    {
      id: 50,
      dimension: "C",
      facet: "perfectionism",
      text: "People often call me a perfectionist.",
      textByLocale: {
        hu: "Az emberek gyakran tartanak perfekcionistának.",
        en: "People often call me a perfectionist.",
        de: "Andere nennen mich oft einen Perfektionisten.",
      },
      textObserver: "People often call him/her a perfectionist.",
      textObserverByLocale: {
        en: "People often call him/her a perfectionist.",
        hu: "Gyakran tartják perfekcionistának.",
        de: "Andere nennen ihn/sie oft einen Perfektionisten.",
      },
    },
    {
      id: 51,
      dimension: "A",
      facet: "gentleness",
      text: "Even when people make a lot of mistakes, I rarely say anything negative.",
      textByLocale: {
        hu: "Még akkor sem nyilatkozom másokról negatívan, ha sok hibát követnek el.",
        en: "Even when people make a lot of mistakes, I rarely say anything negative.",
        de: "Selbst wenn Leute viele Fehler machen, sage ich nur selten etwas Negatives.",
      },
      textObserver: "He/she rarely says negative things.",
      textObserverByLocale: {
        en: "He/she rarely says negative things.",
        hu: "Ritkán nyilatkozik negatívan.",
        de: "Er/Sie sagt selten etwas Negatives.",
      },
    },
    {
      id: 52,
      dimension: "X",
      facet: "social_self_esteem",
      text: "I sometimes feel that I am a worthless person.",
      textByLocale: {
        hu: "Néha az az érzésem, hogy értéktelen ember vagyok.",
        en: "I sometimes feel that I am a worthless person.",
        de: "Manchmal habe ich den Eindruck, dass ich wertlos bin.",
      },
      textObserver: "He/she sometimes feels worthless.",
      textObserverByLocale: {
        en: "He/she sometimes feels worthless.",
        hu: "Néha értéktelennek érzi magát.",
        de: "Manchmal fühlt er/sie sich wertlos.",
      },
      reversed: true,
    },
    {
      id: 53,
      dimension: "E",
      facet: "fearfulness",
      text: "Even in an emergency I wouldn't feel like panicking.",
      textByLocale: {
        hu: "Még egy vészhelyzetben sem veszteném el a fejem.",
        en: "Even in an emergency I wouldn't feel like panicking.",
        de: "Selbst in einem Notfall würde ich nicht in Panik geraten.",
      },
      textObserver: "Even in an emergency he/she wouldn't panic.",
      textObserverByLocale: {
        en: "Even in an emergency he/she wouldn't panic.",
        hu: "Vészhelyzetben sem esik pánikba.",
        de: "Selbst im Notfall würde er/sie nicht in Panik geraten.",
      },
      reversed: true,
    },
    {
      id: 54,
      dimension: "H",
      facet: "sincerity",
      text: "I wouldn't pretend to like someone just to get that person to do favors for me.",
      textByLocale: {
        hu: "Nem tettetném, hogy kedvelek valakit csak azért, hogy rávegyem egy szívességre.",
        en: "I wouldn't pretend to like someone just to get that person to do favors for me.",
        de: "Ich würde nicht vortäuschen, jemanden zu mögen, nur um diese Person dazu zu bringen, mir Gefälligkeiten zu erweisen.",
      },
      textObserver: "He/she wouldn't pretend to like someone to get favors.",
      textObserverByLocale: {
        en: "He/she wouldn't pretend to like someone to get favors.",
        hu: "Nem tettetné, hogy kedvel valakit csak azért, hogy rávegye egy szívességre.",
        de: "Er/Sie würde nicht vortäuschen, jemanden zu mögen.",
      },
    },
    {
      id: 55,
      dimension: "O",
      facet: "unconventionality",
      text: "I find it boring to discuss philosophy.",
      textByLocale: {
        hu: "A filozófiai eszmecseréket unalmasnak tartom.",
        en: "I find it boring to discuss philosophy.",
        de: "Ich finde es langweilig, über Philosophie zu diskutieren.",
      },
      textObserver: "He/she finds philosophy boring.",
      textObserverByLocale: {
        en: "He/she finds philosophy boring.",
        hu: "Unalmasnak tartja a filozófiai eszmecseréket.",
        de: "Er/Sie findet Philosophie langweilig.",
      },
      reversed: true,
    },
    {
      id: 56,
      dimension: "C",
      facet: "prudence",
      text: "I prefer to do whatever comes to mind, rather than stick to a plan.",
      textByLocale: {
        hu: "Inkább spontán szeretek cselekedni, mint mindent előre eltervezni.",
        en: "I prefer to do whatever comes to mind, rather than stick to a plan.",
        de: "Ich ziehe es vor, das zu tun, was mir gerade in den Sinn kommt, anstatt an einem Plan festzuhalten.",
      },
      textObserver: "He/she prefers spontaneity over planning.",
      textObserverByLocale: {
        en: "He/she prefers spontaneity over planning.",
        hu: "Inkább spontán cselekszik.",
        de: "Er/Sie handelt lieber spontan.",
      },
      reversed: true,
    },
    {
      id: 57,
      dimension: "A",
      facet: "flexibility",
      text: "When people tell me that I'm wrong, my first reaction is to argue with them.",
      textByLocale: {
        hu: "Ha azt mondják, hogy nincs igazam, az első reakciőm, hogy vitába szállok.",
        en: "When people tell me that I'm wrong, my first reaction is to argue with them.",
        de: "Wenn mir andere sagen, dass ich falsch liege, ist meine erste Reaktion, mit ihnen zu streiten.",
      },
      textObserver: "His/her first reaction is to argue.",
      textObserverByLocale: {
        en: "His/her first reaction is to argue.",
        hu: "Első reakciója a vita.",
        de: "Er/Sie streitet als erste Reaktion.",
      },
      reversed: true,
    },
    {
      id: 58,
      dimension: "X",
      facet: "social_boldness",
      text: "When I'm in a group of people, I'm often the one who speaks on behalf of the group.",
      textByLocale: {
        hu: "Ha egy csoport tagja vagyok, gyakran leszek a szovivője is.",
        en: "When I'm in a group of people, I'm often the one who speaks on behalf of the group.",
        de: "Wenn ich in einer Gruppe von Leuten bin, bin ich oft derjenige, der im Namen der Gruppe spricht.",
      },
      textObserver: "He/she often speaks for the group.",
      textObserverByLocale: {
        en: "He/she often speaks for the group.",
        hu: "Gyakran ő a szóvivő egy csoportban.",
        de: "Er/Sie spricht oft im Namen der Gruppe.",
      },
    },
    {
      id: 59,
      dimension: "E",
      facet: "sentimentality",
      text: "I remain unemotional even in situations where most people get very sentimental.",
      textByLocale: {
        hu: "Semleges maradok olyan helyzetekben is, ahol mások érzelmessé válnak.",
        en: "I remain unemotional even in situations where most people get very sentimental.",
        de: "Ich bleibe emotionslos, selbst in Situationen, in denen die meisten Leute sehr sentimental werden.",
      },
      textObserver: "He/she remains unemotional in sentimental situations.",
      textObserverByLocale: {
        en: "He/she remains unemotional in sentimental situations.",
        hu: "Érzelemmentes marad szentimentális helyzetekben is.",
        de: "Er/Sie bleibt emotionslos.",
      },
      reversed: true,
    },
    {
      id: 60,
      dimension: "H",
      facet: "fairness",
      text: "I'd be tempted to use counterfeit money, if I were sure I could get away with it.",
      textByLocale: {
        hu: "Kísértésbe vinne, hogy hamisított pénzt használjak, ha tudnám, biztos nem buknék le vele.",
        en: "I'd be tempted to use counterfeit money, if I were sure I could get away with it.",
        de: "Ich würde in die Versuchung geraten, Falschgeld zu benutzen, wenn ich sicher sein könnte, damit durchzukommen.",
      },
      textObserver: "He/she would be tempted to use counterfeit money.",
      textObserverByLocale: {
        en: "He/she would be tempted to use counterfeit money.",
        hu: "Kísértésbe vinné hamis pénzt használni.",
        de: "Er/Sie würde Falschgeld benutzen.",
      },
      reversed: true,
    },
  ],
};
