import type { TestConfig } from "./types";
import { hexacoConfig } from "./hexaco";

/**
 * Modified HEXACO — same 6 dimensions, independently phrased questions
 * Same facet structure as the official HEXACO-PI-R (4 facets × 6 dims × 4 items)
 * 96 items total, all Likert 1–5
 */
export const hexacoModifiedConfig: TestConfig = {
  type: "HEXACO_MODIFIED",
  name: "Módosított HEXACO",
  description: "Saját módosított HEXACO kérdéssor, ugyanazzal a 6 dimenzióval.",
  format: "likert",
  dimensions: hexacoConfig.dimensions,
  questions: [
    // ── H: Honesty-Humility ──────────────────────────────────────────────
    {
      id: 1,
      dimension: "H",
      facet: "sincerity",
      text: "Ha valamit akarok valakitől, képes vagyok kedvesnek mutatkozni iránta, még akkor is, ha valójában nem szimpatikus.",
      textByLocale: {
        hu: "Ha valamit akarok valakitől, képes vagyok kedvesnek mutatkozni iránta, még akkor is, ha valójában nem szimpatikus.",
        en: "I can act friendly toward someone I don't really like if I need something from them.",
        de: "Ich kann mich freundlich gegenüber jemandem verhalten, den ich eigentlich nicht mag, wenn ich etwas von ihm brauche.",
      },
      reversed: true,
    },
    {
      id: 2,
      dimension: "H",
      facet: "sincerity",
      text: "Nem vagyok hajlandó hízelkedni olyanoknak, akiknek hatalmuk van felettem, még ha előnyt is húzhatnék belőle.",
      textByLocale: {
        hu: "Nem vagyok hajlandó hízelkedni olyanoknak, akiknek hatalmuk van felettem, még ha előnyt is húzhatnék belőle.",
        en: "I won't flatter people in power, even if it could benefit me.",
        de: "Ich schmeichle Personen mit Macht nicht, auch wenn es mir Vorteile bringen könnte.",
      },
    },
    {
      id: 3,
      dimension: "H",
      facet: "sincerity",
      text: "Ha valakitől valamit akarok, képes vagyok eltúlzottan hízelkedőnek mutatkozni, hogy megkapjam, amit akarok.",
      textByLocale: {
        hu: "Ha valakitől valamit akarok, képes vagyok eltúlzottan hízelkedőnek mutatkozni, hogy megkapjam, amit akarok.",
        en: "When I need something, I can put on an excessively flattering act to get what I want.",
        de: "Wenn ich etwas brauche, kann ich übermäßig schmeichelnd auftreten, um zu bekommen, was ich will.",
      },
      reversed: true,
    },
    {
      id: 4,
      dimension: "H",
      facet: "sincerity",
      text: "Nem játszom meg a barátságot olyan emberek felé, akiket valójában nem kedvelek.",
      textByLocale: {
        hu: "Nem játszom meg a barátságot olyan emberek felé, akiket valójában nem kedvelek.",
        en: "I don't fake friendliness toward people I don't genuinely like.",
        de: "Ich tue gegenüber Menschen, die ich eigentlich nicht mag, keine Freundlichkeit vor.",
      },
    },
    {
      id: 5,
      dimension: "H",
      facet: "fairness",
      text: "Ha biztosan kideríthetetlen maradna, elfogadnék illegális úton szerzett nagy összeget.",
      textByLocale: {
        hu: "Ha biztosan kideríthetetlen maradna, elfogadnék illegális úton szerzett nagy összeget.",
        en: "I would accept a large sum of money if I was certain no one would ever find out it was illegal.",
        de: "Ich würde eine große Summe Geld annehmen, wenn ich sicher sein könnte, dass niemand herausfindet, dass sie illegal war.",
      },
      reversed: true,
    },
    {
      id: 6,
      dimension: "H",
      facet: "fairness",
      text: "Ha pénzszűkében lennék, fontolóra venném kétes eredetű áruk megvételét.",
      textByLocale: {
        hu: "Ha pénzszűkében lennék, fontolóra venném kétes eredetű áruk megvételét.",
        en: "If I were short on money, I might consider buying goods of dubious origin.",
        de: "Wenn ich knapp bei Kasse wäre, würde ich überlegen, Waren zweifelhafter Herkunft zu kaufen.",
      },
      reversed: true,
    },
    {
      id: 7,
      dimension: "H",
      facet: "fairness",
      text: "Semmilyen körülmények között nem fogadnék el kenőpénzt vagy megvesztegetést.",
      textByLocale: {
        hu: "Semmilyen körülmények között nem fogadnék el kenőpénzt vagy megvesztegetést.",
        en: "Under no circumstances would I accept a bribe or corrupt offer.",
        de: "Unter keinen Umständen würde ich eine Bestechung oder ein korruptes Angebot annehmen.",
      },
    },
    {
      id: 8,
      dimension: "H",
      facet: "fairness",
      text: "Ha garantáltan megúszhatnám, fontolóra venném a pénzügyi szabályok kijátszását saját hasznomra.",
      textByLocale: {
        hu: "Ha garantáltan megúszhatnám, fontolóra venném a pénzügyi szabályok kijátszását saját hasznomra.",
        en: "If I could get away with it, I would consider bending financial rules for my own benefit.",
        de: "Wenn ich damit durchkäme, würde ich überlegen, Finanzregeln zu meinem eigenen Vorteil zu beugen.",
      },
      reversed: true,
    },
    {
      id: 9,
      dimension: "H",
      facet: "greed_avoidance",
      text: "A gazdagság megszerzése nem motivál különösebben.",
      textByLocale: {
        hu: "A gazdagság megszerzése nem motivál különösebben.",
        en: "Becoming wealthy is not a major motivation for me.",
        de: "Reich zu werden motiviert mich nicht besonders.",
      },
    },
    {
      id: 10,
      dimension: "H",
      facet: "greed_avoidance",
      text: "Vonz a gazdagság és a társadalmi presztízs által meghatározott életvitel.",
      textByLocale: {
        hu: "Vonz a gazdagság és a társadalmi presztízs által meghatározott életvitel.",
        en: "I am attracted to the lifestyle associated with wealth and social prestige.",
        de: "Mich zieht der Lebensstil an, der mit Reichtum und sozialem Ansehen verbunden ist.",
      },
      reversed: true,
    },
    {
      id: 11,
      dimension: "H",
      facet: "greed_avoidance",
      text: "Szívesen mutogatnám a jólétemet és az anyagi sikereimet mások előtt.",
      textByLocale: {
        hu: "Szívesen mutogatnám a jólétemet és az anyagi sikereimet mások előtt.",
        en: "I would enjoy showing off my wealth and material success to others.",
        de: "Es würde mir gefallen, meinen Wohlstand und materiellen Erfolg vor anderen zur Schau zu stellen.",
      },
      reversed: true,
    },
    {
      id: 12,
      dimension: "H",
      facet: "greed_avoidance",
      text: "A drága státuszszimbólumok és luxuscikkek komoly vonzerőt gyakorolnak rám.",
      textByLocale: {
        hu: "A drága státuszszimbólumok és luxuscikkek komoly vonzerőt gyakorolnak rám.",
        en: "Expensive status symbols and luxury items hold a strong appeal for me.",
        de: "Teure Statussymbole und Luxusgüter haben eine starke Anziehungskraft auf mich.",
      },
      reversed: true,
    },
    {
      id: 13,
      dimension: "H",
      facet: "modesty",
      text: "Nem tartom magam különlegesebbnek vagy értékesebbnek, mint az átlagembert.",
      textByLocale: {
        hu: "Nem tartom magam különlegesebbnek vagy értékesebbnek, mint az átlagembert.",
        en: "I don't consider myself more special or valuable than the average person.",
        de: "Ich halte mich nicht für besonderer oder wertvoller als den Durchschnittsmenschen.",
      },
    },
    {
      id: 14,
      dimension: "H",
      facet: "modesty",
      text: "Kényelmetlenül érezném magam, ha mások különleges tisztelettel és alázattal kezelnének.",
      textByLocale: {
        hu: "Kényelmetlenül érezném magam, ha mások különleges tisztelettel és alázattal kezelnének.",
        en: "I would feel uncomfortable if others treated me with special reverence.",
        de: "Ich würde mich unwohl fühlen, wenn andere mich mit besonderer Ehrerbietung behandelten.",
      },
    },
    {
      id: 15,
      dimension: "H",
      facet: "modesty",
      text: "Meggyőződésem, hogy a teljesítményem és az értékem meghaladja az átlagot.",
      textByLocale: {
        hu: "Meggyőződésem, hogy a teljesítményem és az értékem meghaladja az átlagot.",
        en: "I believe my achievements and worth are above average.",
        de: "Ich bin überzeugt, dass meine Leistungen und mein Wert über dem Durchschnitt liegen.",
      },
      reversed: true,
    },
    {
      id: 16,
      dimension: "H",
      facet: "modesty",
      text: "Fontos számomra, hogy mások kiemelkedő és befolyásos személyiségnek lássanak.",
      textByLocale: {
        hu: "Fontos számomra, hogy mások kiemelkedő és befolyásos személyiségnek lássanak.",
        en: "It matters to me that others see me as a prominent and influential person.",
        de: "Es ist mir wichtig, dass andere mich als eine herausragende und einflussreiche Person wahrnehmen.",
      },
      reversed: true,
    },

    // ── E: Emotionality ──────────────────────────────────────────────────
    {
      id: 17,
      dimension: "E",
      facet: "fearfulness",
      text: "Szorongok, ha bizonytalan vagy kockázatos körülmények között kell hosszú utat megtennem.",
      textByLocale: {
        hu: "Szorongok, ha bizonytalan vagy kockázatos körülmények között kell hosszú utat megtennem.",
        en: "I feel anxious about travelling in uncertain or risky conditions.",
        de: "Ich fühle mich unwohl, wenn ich unter unsicheren oder riskanten Bedingungen reisen muss.",
      },
    },
    {
      id: 18,
      dimension: "E",
      facet: "fearfulness",
      text: "Kockázatos feladatokat is elvállalok, ha szükséges.",
      textByLocale: {
        hu: "Kockázatos feladatokat is elvállalok, ha szükséges.",
        en: "I am willing to take on risky tasks when necessary.",
        de: "Ich übernehme auch riskante Aufgaben, wenn es nötig ist.",
      },
      reversed: true,
    },
    {
      id: 19,
      dimension: "E",
      facet: "fearfulness",
      text: "Az olyan helyzetek, ahol a testi biztonságom forog kockán, komoly félelmet váltanak ki bennem.",
      textByLocale: {
        hu: "Az olyan helyzetek, ahol a testi biztonságom forog kockán, komoly félelmet váltanak ki bennem.",
        en: "Situations where my physical safety is at risk cause me significant fear.",
        de: "Situationen, in denen meine körperliche Sicherheit auf dem Spiel steht, lösen bei mir erhebliche Angst aus.",
      },
    },
    {
      id: 20,
      dimension: "E",
      facet: "fearfulness",
      text: "Veszélyes vagy pánikszerű helyzetekben is megőrzöm a hidegvéremet.",
      textByLocale: {
        hu: "Veszélyes vagy pánikszerű helyzetekben is megőrzöm a hidegvéremet.",
        en: "I keep my composure even in dangerous or panic-inducing situations.",
        de: "Ich bewahre meine Ruhe auch in gefährlichen oder panikerzeugenden Situationen.",
      },
      reversed: true,
    },
    {
      id: 21,
      dimension: "E",
      facet: "anxiety",
      text: "Sokszor aggódom olyan dolgokon is, amelyek valójában nem fontosak.",
      textByLocale: {
        hu: "Sokszor aggódom olyan dolgokon is, amelyek valójában nem fontosak.",
        en: "I often worry about things that don't really matter.",
        de: "Ich mache mir oft Sorgen um Dinge, die eigentlich keine Rolle spielen.",
      },
    },
    {
      id: 22,
      dimension: "E",
      facet: "anxiety",
      text: "Az átlagos embernél ritkábban gyötörnek aggodalmak és szorongások.",
      textByLocale: {
        hu: "Az átlagos embernél ritkábban gyötörnek aggodalmak és szorongások.",
        en: "I experience worries and anxieties less often than most people.",
        de: "Ich leide seltener unter Sorgen und Ängsten als die meisten Menschen.",
      },
      reversed: true,
    },
    {
      id: 23,
      dimension: "E",
      facet: "anxiety",
      text: "A napi stressz és aggodalmak ritkán zavarják meg az alvásomat.",
      textByLocale: {
        hu: "A napi stressz és aggodalmak ritkán zavarják meg az alvásomat.",
        en: "Daily stress and worries rarely disturb my sleep.",
        de: "Alltäglicher Stress und Sorgen stören meinen Schlaf selten.",
      },
      reversed: true,
    },
    {
      id: 24,
      dimension: "E",
      facet: "anxiety",
      text: "A fontos döntések kimenetelére való várakozás nagyfokú szorongást vált ki belőlem.",
      textByLocale: {
        hu: "A fontos döntések kimenetelére való várakozás nagyfokú szorongást vált ki belőlem.",
        en: "Waiting for the outcome of an important decision triggers significant anxiety in me.",
        de: "Das Warten auf das Ergebnis einer wichtigen Entscheidung löst bei mir erhebliche Angst aus.",
      },
    },
    {
      id: 25,
      dimension: "E",
      facet: "dependence",
      text: "Nehéz időkben határozottan igénylem, hogy valaki mellém álljon és támogasson.",
      textByLocale: {
        hu: "Nehéz időkben határozottan igénylem, hogy valaki mellém álljon és támogasson.",
        en: "In difficult times, I strongly need someone to be there for me.",
        de: "In schwierigen Zeiten brauche ich dringend jemanden, der für mich da ist.",
      },
    },
    {
      id: 26,
      dimension: "E",
      facet: "dependence",
      text: "Nehézségek esetén is képes vagyok önállóan megbirkózni az érzelmi terhekkel.",
      textByLocale: {
        hu: "Nehézségek esetén is képes vagyok önállóan megbirkózni az érzelmi terhekkel.",
        en: "Even in difficult situations, I can manage my emotional burden on my own.",
        de: "Selbst in schwierigen Situationen schaffe ich es, meine emotionale Last alleine zu bewältigen.",
      },
      reversed: true,
    },
    {
      id: 27,
      dimension: "E",
      facet: "dependence",
      text: "Könnyebben viselem a terheket, ha megoszthatom a problémáimat valakivel.",
      textByLocale: {
        hu: "Könnyebben viselem a terheket, ha megoszthatom a problémáimat valakivel.",
        en: "I find it easier to cope with difficulties when I can share my problems with someone.",
        de: "Es fällt mir leichter, Schwierigkeiten zu bewältigen, wenn ich meine Probleme mit jemandem teilen kann.",
      },
    },
    {
      id: 28,
      dimension: "E",
      facet: "dependence",
      text: "Általában a gondjaimat magamnak tartom, és nem szoktam másokat terhelni velük.",
      textByLocale: {
        hu: "Általában a gondjaimat magamnak tartom, és nem szoktam másokat terhelni velük.",
        en: "I generally keep my troubles to myself and don't burden others with them.",
        de: "Im Allgemeinen behalte ich meine Sorgen für mich und belaste andere nicht damit.",
      },
      reversed: true,
    },
    {
      id: 29,
      dimension: "E",
      facet: "sentimentality",
      text: "Könnyen megérintenek mások fájdalmas érzelmei.",
      textByLocale: {
        hu: "Könnyen megérintenek mások fájdalmas érzelmei.",
        en: "I am easily moved by other people's emotional pain.",
        de: "Ich lasse mich leicht von den Schmerzen anderer berühren.",
      },
    },
    {
      id: 30,
      dimension: "E",
      facet: "sentimentality",
      text: "Képes vagyok mélyen beleélni magam a közel álló embereimnek az érzelmeibe.",
      textByLocale: {
        hu: "Képes vagyok mélyen beleélni magam a közel álló embereimnek az érzelmeibe.",
        en: "I am able to deeply empathize with the emotions of people close to me.",
        de: "Ich kann mich tief in die Gefühle von mir nahestehenden Menschen einfühlen.",
      },
    },
    {
      id: 31,
      dimension: "E",
      facet: "sentimentality",
      text: "Mélyen megérint, ha hosszabb időre el kell válnom a közel állóimtól.",
      textByLocale: {
        hu: "Mélyen megérint, ha hosszabb időre el kell válnom a közel állóimtól.",
        en: "I am deeply affected when I have to part from people who are close to me.",
        de: "Es berührt mich tief, wenn ich mich für längere Zeit von mir nahestehenden Menschen verabschieden muss.",
      },
    },
    {
      id: 32,
      dimension: "E",
      facet: "sentimentality",
      text: "Érzelmileg távolságtartó tudok maradni akkor is, amikor mások érzékenyen reagálnak.",
      textByLocale: {
        hu: "Érzelmileg távolságtartó tudok maradni akkor is, amikor mások érzékenyen reagálnak.",
        en: "I can remain emotionally detached even when others react with sensitivity.",
        de: "Ich kann emotional distanziert bleiben, auch wenn andere empfindlich reagieren.",
      },
      reversed: true,
    },

    // ── X: eXtraversion ─────────────────────────────────────────────────
    {
      id: 33,
      dimension: "X",
      facet: "social_self_esteem",
      text: "Összességében jól érzem magam a bőrömben.",
      textByLocale: {
        hu: "Összességében jól érzem magam a bőrömben.",
        en: "Overall, I feel comfortable with who I am.",
        de: "Im Großen und Ganzen fühle ich mich in meiner Haut wohl.",
      },
    },
    {
      id: 34,
      dimension: "X",
      facet: "social_self_esteem",
      text: "Azt hiszem, az emberek általában kedvelnek és pozitívan tekintenek rám.",
      textByLocale: {
        hu: "Azt hiszem, az emberek általában kedvelnek és pozitívan tekintenek rám.",
        en: "I believe people generally like me and view me positively.",
        de: "Ich glaube, die meisten Menschen mögen mich und sehen mich in einem positiven Licht.",
      },
    },
    {
      id: 35,
      dimension: "X",
      facet: "social_self_esteem",
      text: "Sokszor úgy érzem, hogy nem különösebben kedvelnek az emberek.",
      textByLocale: {
        hu: "Sokszor úgy érzem, hogy nem különösebben kedvelnek az emberek.",
        en: "I often feel that people don't really care much for me.",
        de: "Ich habe oft das Gefühl, dass Menschen mir gegenüber nicht besonders freundlich eingestellt sind.",
      },
      reversed: true,
    },
    {
      id: 36,
      dimension: "X",
      facet: "social_self_esteem",
      text: "Olykor kétség fog el afelől, hogy valóban van-e értékem mások szemében.",
      textByLocale: {
        hu: "Olykor kétség fog el afelől, hogy valóban van-e értékem mások szemében.",
        en: "Sometimes I doubt whether I really have any value in the eyes of others.",
        de: "Manchmal zweifle ich daran, ob ich wirklich einen Wert in den Augen anderer habe.",
      },
      reversed: true,
    },
    {
      id: 37,
      dimension: "X",
      facet: "social_boldness",
      text: "Idegen emberek között is könnyedén felveszem a szót és kezdeményezem az ismerkedést.",
      textByLocale: {
        hu: "Idegen emberek között is könnyedén felveszem a szót és kezdeményezem az ismerkedést.",
        en: "I find it easy to start a conversation even with people I don't know.",
        de: "Es fällt mir leicht, auch mit Fremden ein Gespräch zu beginnen.",
      },
    },
    {
      id: 38,
      dimension: "X",
      facet: "social_boldness",
      text: "Visszafogom magam, ha csoportban kellene elmondani a véleményemet.",
      textByLocale: {
        hu: "Visszafogom magam, ha csoportban kellene elmondani a véleményemet.",
        en: "I hold back when it comes to sharing my views in a group.",
        de: "Ich halte mich zurück, wenn es darum geht, meine Meinung in einer Gruppe zu äußern.",
      },
      reversed: true,
    },
    {
      id: 39,
      dimension: "X",
      facet: "social_boldness",
      text: "Csoportban természetesen adódik, hogy én vegyem át az irányítást és képviseljem a csoportot.",
      textByLocale: {
        hu: "Csoportban természetesen adódik, hogy én vegyem át az irányítást és képviseljem a csoportot.",
        en: "In a group, I naturally take on the role of spokesperson and leader.",
        de: "In einer Gruppe übernehme ich natürlich die Rolle des Sprechers und Anführers.",
      },
    },
    {
      id: 40,
      dimension: "X",
      facet: "social_boldness",
      text: "Nagy közönség előtt megszólalni komoly szorongást okoz nekem.",
      textByLocale: {
        hu: "Nagy közönség előtt megszólalni komoly szorongást okoz nekem.",
        en: "Speaking in front of a large audience causes me significant anxiety.",
        de: "Vor einem großen Publikum zu sprechen bereitet mir erhebliche Angst.",
      },
      reversed: true,
    },
    {
      id: 41,
      dimension: "X",
      facet: "sociability",
      text: "Feltölt, ha csoportban vagyok és pezsgő társasági élet zajlik körülöttem.",
      textByLocale: {
        hu: "Feltölt, ha csoportban vagyok és pezsgő társasági élet zajlik körülöttem.",
        en: "Being in a lively group setting fills me with energy.",
        de: "Es erfüllt mich mit Energie, in einer lebhaften Gruppe zu sein.",
      },
    },
    {
      id: 42,
      dimension: "X",
      facet: "sociability",
      text: "Inkább elkerülöm a felületes, könnyed csevegést.",
      textByLocale: {
        hu: "Inkább elkerülöm a felületes, könnyed csevegést.",
        en: "I tend to avoid idle or trivial conversation.",
        de: "Ich vermeide oberflächliche oder bedeutungslose Gespräche.",
      },
      reversed: true,
    },
    {
      id: 43,
      dimension: "X",
      facet: "sociability",
      text: "Jobban teljesítek és érzem magam csapatban, mint egyedüli munkavégzés során.",
      textByLocale: {
        hu: "Jobban teljesítek és érzem magam csapatban, mint egyedüli munkavégzés során.",
        en: "I perform better and feel better working as part of a team than working alone.",
        de: "Ich arbeite besser und fühle mich besser als Teil eines Teams als beim alleinigen Arbeiten.",
      },
    },
    {
      id: 44,
      dimension: "X",
      facet: "sociability",
      text: "Ismeretlen környezetben is gyorsan kialakítok értékes kapcsolatokat.",
      textByLocale: {
        hu: "Ismeretlen környezetben is gyorsan kialakítok értékes kapcsolatokat.",
        en: "Even in unfamiliar surroundings, I quickly form meaningful connections.",
        de: "Auch in unbekannter Umgebung knüpfe ich schnell bedeutungsvolle Verbindungen.",
      },
    },
    {
      id: 45,
      dimension: "X",
      facet: "liveliness",
      text: "Általában lendületes és tettrekész vagyok.",
      textByLocale: {
        hu: "Általában lendületes és tettrekész vagyok.",
        en: "I am generally lively and ready to take action.",
        de: "Im Allgemeinen bin ich lebhaft und handlungsbereit.",
      },
    },
    {
      id: 46,
      dimension: "X",
      facet: "liveliness",
      text: "Alapvetően derűs és pozitív hozzáállással közelítek az élethez.",
      textByLocale: {
        hu: "Alapvetően derűs és pozitív hozzáállással közelítek az élethez.",
        en: "I approach life with a fundamentally positive and cheerful attitude.",
        de: "Ich gehe das Leben grundsätzlich mit einer positiven und fröhlichen Einstellung an.",
      },
    },
    {
      id: 47,
      dimension: "X",
      facet: "liveliness",
      text: "Hajlamos vagyok komolyabb és visszafogottabb hangulatba esni, mint az emberek általában.",
      textByLocale: {
        hu: "Hajlamos vagyok komolyabb és visszafogottabb hangulatba esni, mint az emberek általában.",
        en: "I tend to fall into a more subdued and serious mood than people generally do.",
        de: "Ich neige dazu, in eine gedämpftere und ernstere Stimmung zu verfallen als die meisten Menschen.",
      },
      reversed: true,
    },
    {
      id: 48,
      dimension: "X",
      facet: "liveliness",
      text: "Úgy érzem, kevésbé vagyok élénk és aktív, mint az emberek többsége.",
      textByLocale: {
        hu: "Úgy érzem, kevésbé vagyok élénk és aktív, mint az emberek többsége.",
        en: "I feel less lively and active than most people around me.",
        de: "Ich fühle mich weniger lebhaft und aktiv als die meisten Menschen um mich herum.",
      },
      reversed: true,
    },

    // ── A: Agreeableness ─────────────────────────────────────────────────
    {
      id: 49,
      dimension: "A",
      facet: "forgiveness",
      text: "Nehezen tudok tartós haragot tartani, még akkor is, ha valaki mélyen bántott.",
      textByLocale: {
        hu: "Nehezen tudok tartós haragot tartani, még akkor is, ha valaki mélyen bántott.",
        en: "I find it hard to stay angry at people, even when they have really hurt me.",
        de: "Ich kann auf Menschen kaum nachtragen, selbst wenn sie mir wirklich wehgetan haben.",
      },
    },
    {
      id: 50,
      dimension: "A",
      facet: "forgiveness",
      text: "Ha valaki megbántott, igyekszem megbocsátani és nem görgetni magam előtt a sérelmeket.",
      textByLocale: {
        hu: "Ha valaki megbántott, igyekszem megbocsátani és nem görgetni magam előtt a sérelmeket.",
        en: "When someone hurts me, I try to forgive and not carry the grievance with me.",
        de: "Wenn mich jemand verletzt, versuche ich zu vergeben und den Groll nicht mit mir zu tragen.",
      },
    },
    {
      id: 51,
      dimension: "A",
      facet: "forgiveness",
      text: "Ha egyszer becsaptak, nehezen tudok újra megbízni az illetőben.",
      textByLocale: {
        hu: "Ha egyszer becsaptak, nehezen tudok újra megbízni az illetőben.",
        en: "Once someone has betrayed my trust, it is hard for me to trust them again.",
        de: "Wenn jemand mein Vertrauen missbraucht hat, fällt es mir schwer, ihm wieder zu vertrauen.",
      },
      reversed: true,
    },
    {
      id: 52,
      dimension: "A",
      facet: "forgiveness",
      text: "A mély sérelmeket nehéz nekem igazán elengedni és megbocsátani.",
      textByLocale: {
        hu: "A mély sérelmeket nehéz nekem igazán elengedni és megbocsátani.",
        en: "It is hard for me to truly let go and forgive when I have been deeply hurt.",
        de: "Es fällt mir schwer, wirklich loszulassen und zu vergeben, wenn ich tief verletzt wurde.",
      },
      reversed: true,
    },
    {
      id: 53,
      dimension: "A",
      facet: "gentleness",
      text: "Jellemzően elnéző vagyok, ha mások hibáznak vagy hiányosságot mutatnak.",
      textByLocale: {
        hu: "Jellemzően elnéző vagyok, ha mások hibáznak vagy hiányosságot mutatnak.",
        en: "I tend to be understanding and tolerant when others make mistakes.",
        de: "Ich bin in der Regel verständnisvoll und geduldig, wenn andere Fehler machen.",
      },
    },
    {
      id: 54,
      dimension: "A",
      facet: "gentleness",
      text: "Hajlamos vagyok rámutatni mások gyengeségeire és hibáira.",
      textByLocale: {
        hu: "Hajlamos vagyok rámutatni mások gyengeségeire és hibáira.",
        en: "I tend to point out others' weaknesses and mistakes.",
        de: "Ich neige dazu, auf die Schwächen und Fehler anderer hinzuweisen.",
      },
      reversed: true,
    },
    {
      id: 55,
      dimension: "A",
      facet: "gentleness",
      text: "Másokat megértőn és kedvezően értékelek, nem keresem a hibákat bennük.",
      textByLocale: {
        hu: "Másokat megértőn és kedvezően értékelek, nem keresem a hibákat bennük.",
        en: "I evaluate others generously and with understanding, rather than looking for their faults.",
        de: "Ich beurteile andere großzügig und verständnisvoll, anstatt nach ihren Fehlern zu suchen.",
      },
    },
    {
      id: 56,
      dimension: "A",
      facet: "gentleness",
      text: "Tartózkodok attól, hogy negatívan ítéljek el másokat, még ha sorozatosan hibáznak is.",
      textByLocale: {
        hu: "Tartózkodok attól, hogy negatívan ítéljek el másokat, még ha sorozatosan hibáznak is.",
        en: "I refrain from judging others negatively, even when they repeatedly make mistakes.",
        de: "Ich enthalte mich eines negativen Urteils über andere, selbst wenn sie wiederholt Fehler machen.",
      },
    },
    {
      id: 57,
      dimension: "A",
      facet: "flexibility",
      text: "Nyitottan hallgatom mások ellenérveit, és szívesen felülvizsgálom a saját álláspontomat.",
      textByLocale: {
        hu: "Nyitottan hallgatom mások ellenérveit, és szívesen felülvizsgálom a saját álláspontomat.",
        en: "I openly consider counterarguments and am willing to revise my own position.",
        de: "Ich höre mir Gegenargumente offen an und überprüfe gerne meine eigene Haltung.",
      },
    },
    {
      id: 58,
      dimension: "A",
      facet: "flexibility",
      text: "Ha egyszer kialakult egy véleményem, ritkán változtatok rajta.",
      textByLocale: {
        hu: "Ha egyszer kialakult egy véleményem, ritkán változtatok rajta.",
        en: "Once I've formed an opinion, I rarely change it.",
        de: "Wenn ich mir einmal eine Meinung gebildet habe, ändere ich sie selten.",
      },
      reversed: true,
    },
    {
      id: 59,
      dimension: "A",
      facet: "flexibility",
      text: "Ha valaki megkérdőjelezi az álláspontomat, ösztönösen védekezni kezdek.",
      textByLocale: {
        hu: "Ha valaki megkérdőjelezi az álláspontomat, ösztönösen védekezni kezdek.",
        en: "When someone questions my position, my instinct is to defend myself.",
        de: "Wenn jemand meine Position in Frage stellt, ist mein Instinkt, mich zu verteidigen.",
      },
      reversed: true,
    },
    {
      id: 60,
      dimension: "A",
      facet: "flexibility",
      text: "Ha meg vagyok győződve az igazamról, nehezen hajlok a kompromisszumra.",
      textByLocale: {
        hu: "Ha meg vagyok győződve az igazamról, nehezen hajlok a kompromisszumra.",
        en: "When I'm convinced I'm right, I find it hard to compromise.",
        de: "Wenn ich überzeugt bin, dass ich recht habe, fällt es mir schwer, Kompromisse einzugehen.",
      },
      reversed: true,
    },
    {
      id: 61,
      dimension: "A",
      facet: "patience",
      text: "Akkor sem robbanok ki, ha valaki szándékosan kellemetlenkedik nekem.",
      textByLocale: {
        hu: "Akkor sem robbanok ki, ha valaki szándékosan kellemetlenkedik nekem.",
        en: "I stay calm even when someone is deliberately unpleasant to me.",
        de: "Ich bleibe ruhig, auch wenn jemand mich absichtlich ärgert.",
      },
    },
    {
      id: 62,
      dimension: "A",
      facet: "patience",
      text: "Könnyen elvesztem a türelmemet, ha valami nem az elképzeléseim szerint alakul.",
      textByLocale: {
        hu: "Könnyen elvesztem a türelmemet, ha valami nem az elképzeléseim szerint alakul.",
        en: "I easily lose patience when things don't go the way I want.",
        de: "Ich verliere leicht die Geduld, wenn Dinge nicht so laufen wie ich es mir vorstelle.",
      },
      reversed: true,
    },
    {
      id: 63,
      dimension: "A",
      facet: "patience",
      text: "Ritkán ingerülök fel, még akkor is, ha provokálnak.",
      textByLocale: {
        hu: "Ritkán ingerülök fel, még akkor is, ha provokálnak.",
        en: "I rarely get irritated, even when provoked.",
        de: "Ich ärgere mich selten, selbst wenn man mich provoziert.",
      },
    },
    {
      id: 64,
      dimension: "A",
      facet: "patience",
      text: "Ha valaki szándékosan sért, nehezen tudom féken tartani az indulataimat.",
      textByLocale: {
        hu: "Ha valaki szándékosan sért, nehezen tudom féken tartani az indulataimat.",
        en: "When someone deliberately offends me, I find it hard to control my anger.",
        de: "Wenn jemand mich absichtlich beleidigt, fällt es mir schwer, meine Wut im Zaum zu halten.",
      },
      reversed: true,
    },

    // ── C: Conscientiousness ─────────────────────────────────────────────
    {
      id: 65,
      dimension: "C",
      facet: "organization",
      text: "Fontos számomra, hogy a környezetem rendben és tisztán legyen.",
      textByLocale: {
        hu: "Fontos számomra, hogy a környezetem rendben és tisztán legyen.",
        en: "I care about keeping my surroundings tidy and orderly.",
        de: "Es ist mir wichtig, dass meine Umgebung ordentlich und sauber ist.",
      },
    },
    {
      id: 66,
      dimension: "C",
      facet: "organization",
      text: "Rendszeresen előre megtervezem a teendőimet, hogy elkerüljem a késői sietséget.",
      textByLocale: {
        hu: "Rendszeresen előre megtervezem a teendőimet, hogy elkerüljem a késői sietséget.",
        en: "I regularly plan my tasks in advance to avoid last-minute rushing.",
        de: "Ich plane meine Aufgaben regelmäßig im Voraus, um Last-Minute-Stress zu vermeiden.",
      },
    },
    {
      id: 67,
      dimension: "C",
      facet: "organization",
      text: "Körülöttem általában meglehetősen rendetlenség szokott lenni.",
      textByLocale: {
        hu: "Körülöttem általában meglehetősen rendetlenség szokott lenni.",
        en: "My surroundings tend to be fairly disorganized and messy.",
        de: "Meine Umgebung ist meistens ziemlich unordentlich und chaotisch.",
      },
      reversed: true,
    },
    {
      id: 68,
      dimension: "C",
      facet: "organization",
      text: "Rendszertelenségem időnként akadályt jelent a hatékony munkavégzésben.",
      textByLocale: {
        hu: "Rendszertelenségem időnként akadályt jelent a hatékony munkavégzésben.",
        en: "My lack of organization sometimes gets in the way of working effectively.",
        de: "Meine Unorganisiertheit steht manchmal einer effektiven Arbeit im Wege.",
      },
      reversed: true,
    },
    {
      id: 69,
      dimension: "C",
      facet: "diligence",
      text: "Szeretek kihívást jelentő célokat kitűzni, és keményen dolgozni értük.",
      textByLocale: {
        hu: "Szeretek kihívást jelentő célokat kitűzni, és keményen dolgozni értük.",
        en: "I like setting challenging goals for myself and working hard to achieve them.",
        de: "Ich setze gerne anspruchsvolle Ziele und arbeite hart daran, sie zu erreichen.",
      },
    },
    {
      id: 70,
      dimension: "C",
      facet: "diligence",
      text: "Ha kitűzöm magam elé, mindent megteszek egy cél elérése érdekében.",
      textByLocale: {
        hu: "Ha kitűzöm magam elé, mindent megteszek egy cél elérése érdekében.",
        en: "Once I commit to a goal, I give everything I have to achieve it.",
        de: "Wenn ich mich einem Ziel verschreibe, gebe ich alles, um es zu erreichen.",
      },
    },
    {
      id: 71,
      dimension: "C",
      facet: "diligence",
      text: "Céljaim elérésekor könnyen elveszítem a motivációt és félbehagyom a munkát.",
      textByLocale: {
        hu: "Céljaim elérésekor könnyen elveszítem a motivációt és félbehagyom a munkát.",
        en: "When pursuing a goal, I easily lose motivation and give up before finishing.",
        de: "Beim Verfolgen eines Ziels verliere ich leicht die Motivation und höre auf, bevor ich fertig bin.",
      },
      reversed: true,
    },
    {
      id: 72,
      dimension: "C",
      facet: "diligence",
      text: "Általában csak akkora energiát fektetek a munkába, amennyi feltétlenül szükséges.",
      textByLocale: {
        hu: "Általában csak akkora energiát fektetek a munkába, amennyi feltétlenül szükséges.",
        en: "I generally put in only as much effort at work as is absolutely necessary.",
        de: "Ich stecke im Allgemeinen nur so viel Energie in die Arbeit, wie absolut notwendig ist.",
      },
      reversed: true,
    },
    {
      id: 73,
      dimension: "C",
      facet: "perfectionism",
      text: "Nehezen tudom letenni a munkát addig, amíg minden apró részlet tökéletes.",
      textByLocale: {
        hu: "Nehezen tudom letenni a munkát addig, amíg minden apró részlet tökéletes.",
        en: "I find it hard to stop working on something until every detail is exactly right.",
        de: "Es fällt mir schwer, mit einer Arbeit aufzuhören, bevor jedes Detail stimmt.",
      },
    },
    {
      id: 74,
      dimension: "C",
      facet: "perfectionism",
      text: "Csak akkor vagyok elégedett a munkámmal, ha az minden szempontból pontos és hibátlan.",
      textByLocale: {
        hu: "Csak akkor vagyok elégedett a munkámmal, ha az minden szempontból pontos és hibátlan.",
        en: "I am only satisfied with my work when it is accurate and error-free in every respect.",
        de: "Ich bin mit meiner Arbeit nur zufrieden, wenn sie in jeder Hinsicht präzise und fehlerfrei ist.",
      },
    },
    {
      id: 75,
      dimension: "C",
      facet: "perfectionism",
      text: "A részletek gondos ellenőrzése nem különösebben jellemző rám munkavégzés közben.",
      textByLocale: {
        hu: "A részletek gondos ellenőrzése nem különösebben jellemző rám munkavégzés közben.",
        en: "Carefully checking details is not something I naturally do when working.",
        de: "Das sorgfältige Prüfen von Details ist beim Arbeiten nicht meine Stärke.",
      },
      reversed: true,
    },
    {
      id: 76,
      dimension: "C",
      facet: "perfectionism",
      text: "Fontosnak tartom, hogy amit csinálok, az kifogástalan legyen – ez sokszor szembetűnik másoknak is.",
      textByLocale: {
        hu: "Fontosnak tartom, hogy amit csinálok, az kifogástalan legyen – ez sokszor szembetűnik másoknak is.",
        en: "I consider it important that what I do is flawless – others often notice this about me too.",
        de: "Es ist mir wichtig, dass das, was ich tue, einwandfrei ist – das fällt anderen oft auch auf.",
      },
    },
    {
      id: 77,
      dimension: "C",
      facet: "prudence",
      text: "Igyekszem átgondolt döntéseket hozni, és nem hagyom, hogy az érzelmeim kapkodásra csábítsanak.",
      textByLocale: {
        hu: "Igyekszem átgondolt döntéseket hozni, és nem hagyom, hogy az érzelmeim kapkodásra csábítsanak.",
        en: "I try to make thoughtful decisions and don't let my emotions push me into hasty actions.",
        de: "Ich versuche durchdachte Entscheidungen zu treffen und lasse mich nicht von meinen Gefühlen zu voreiligen Handlungen verleiten.",
      },
    },
    {
      id: 78,
      dimension: "C",
      facet: "prudence",
      text: "Döntés előtt általában nem sokat gondolkozom a következményeken.",
      textByLocale: {
        hu: "Döntés előtt általában nem sokat gondolkozom a következményeken.",
        en: "I usually don't spend much time thinking about the consequences before making a decision.",
        de: "Ich denke normalerweise nicht lange über die Konsequenzen nach, bevor ich eine Entscheidung treffe.",
      },
      reversed: true,
    },
    {
      id: 79,
      dimension: "C",
      facet: "prudence",
      text: "Általában cselekvés előtt nem sokat fontolgatom a lehetséges következményeket.",
      textByLocale: {
        hu: "Általában cselekvés előtt nem sokat fontolgatom a lehetséges következményeket.",
        en: "I usually act first and consider the possible consequences later.",
        de: "Ich handle meistens zuerst und denke dann erst über die möglichen Folgen nach.",
      },
      reversed: true,
    },
    {
      id: 80,
      dimension: "C",
      facet: "prudence",
      text: "Tervek és szabályok helyett inkább a pillanat hívásának szoktam engedelmeskedni.",
      textByLocale: {
        hu: "Tervek és szabályok helyett inkább a pillanat hívásának szoktam engedelmeskedni.",
        en: "Rather than following plans and rules, I tend to follow the call of the moment.",
        de: "Statt Plänen und Regeln zu folgen, neige ich dazu, dem Ruf des Augenblicks zu folgen.",
      },
      reversed: true,
    },

    // ── O: Openness to Experience ────────────────────────────────────────
    {
      id: 81,
      dimension: "O",
      facet: "aesthetic_appreciation",
      text: "A vizuális művészet nem vonz különösebben.",
      textByLocale: {
        hu: "A vizuális művészet nem vonz különösebben.",
        en: "Visual art doesn't particularly appeal to me.",
        de: "Bildende Kunst spricht mich nicht besonders an.",
      },
      reversed: true,
    },
    {
      id: 82,
      dimension: "O",
      facet: "aesthetic_appreciation",
      text: "A költészet és a líra valóban megragadja a figyelmemet.",
      textByLocale: {
        hu: "A költészet és a líra valóban megragadja a figyelmemet.",
        en: "Poetry and literary verse genuinely capture my attention.",
        de: "Gedichte und literarische Lyrik fesseln meine Aufmerksamkeit wirklich.",
      },
    },
    {
      id: 83,
      dimension: "O",
      facet: "aesthetic_appreciation",
      text: "A klasszikus zene és az előadóművészet valódi gyönyörűséget okoz nekem.",
      textByLocale: {
        hu: "A klasszikus zene és az előadóművészet valódi gyönyörűséget okoz nekem.",
        en: "Classical music and performing arts bring me genuine pleasure.",
        de: "Klassische Musik und darstellende Kunst bereiten mir echte Freude.",
      },
    },
    {
      id: 84,
      dimension: "O",
      facet: "aesthetic_appreciation",
      text: "A természet szépségét és hangulatát szívesen figyelgetem el.",
      textByLocale: {
        hu: "A természet szépségét és hangulatát szívesen figyelgetem el.",
        en: "I enjoy quietly observing the beauty and atmosphere of nature.",
        de: "Ich genieße es, die Schönheit und Atmosphäre der Natur ruhig zu beobachten.",
      },
    },
    {
      id: 85,
      dimension: "O",
      facet: "inquisitiveness",
      text: "Szívesen tájékozódom más kultúrák és nemzetek történelméről.",
      textByLocale: {
        hu: "Szívesen tájékozódom más kultúrák és nemzetek történelméről.",
        en: "I enjoy learning about the history of different cultures and nations.",
        de: "Ich interessiere mich für die Geschichte verschiedener Kulturen und Völker.",
      },
    },
    {
      id: 86,
      dimension: "O",
      facet: "inquisitiveness",
      text: "Vonz az ismeretlen helyek és tájak felfedezése, akár csak térkép segítségével.",
      textByLocale: {
        hu: "Vonz az ismeretlen helyek és tájak felfedezése, akár csak térkép segítségével.",
        en: "I enjoy exploring unknown places and landscapes, even if just on a map.",
        de: "Ich erkunde gerne unbekannte Orte und Landschaften, auch wenn es nur auf einer Karte ist.",
      },
    },
    {
      id: 87,
      dimension: "O",
      facet: "inquisitiveness",
      text: "A tudomány és a technológia fejlődése nem kelt különösebb érdeklődést bennem.",
      textByLocale: {
        hu: "A tudomány és a technológia fejlődése nem kelt különösebb érdeklődést bennem.",
        en: "The development of science and technology doesn't particularly interest me.",
        de: "Die Entwicklung von Wissenschaft und Technologie interessiert mich nicht besonders.",
      },
      reversed: true,
    },
    {
      id: 88,
      dimension: "O",
      facet: "inquisitiveness",
      text: "Az enciklopédiák és ismeretterjesztő kiadványok böngészése valódi szórakozás számomra.",
      textByLocale: {
        hu: "Az enciklopédiák és ismeretterjesztő kiadványok böngészése valódi szórakozás számomra.",
        en: "Browsing encyclopaedias and educational publications is a real pleasure for me.",
        de: "Das Durchstöbern von Enzyklopädien und Sachbüchern ist für mich ein echtes Vergnügen.",
      },
    },
    {
      id: 89,
      dimension: "O",
      facet: "creativity",
      text: "Vonzódást érzek a kreatív alkotás felé, legyen szó írásról, zenéről vagy képzőművészetről.",
      textByLocale: {
        hu: "Vonzódást érzek a kreatív alkotás felé, legyen szó írásról, zenéről vagy képzőművészetről.",
        en: "I feel drawn to creative expression, whether through writing, music, or visual art.",
        de: "Ich fühle mich vom kreativen Ausdruck angezogen, sei es durch Schreiben, Musik oder bildende Kunst.",
      },
    },
    {
      id: 90,
      dimension: "O",
      facet: "creativity",
      text: "Mások is észreveszik rajtam, hogy gazdag és élénk a képzeletem.",
      textByLocale: {
        hu: "Mások is észreveszik rajtam, hogy gazdag és élénk a képzeletem.",
        en: "Others also notice that I have a rich and vivid imagination.",
        de: "Andere bemerken ebenfalls, dass ich eine reiche und lebhafte Vorstellungskraft habe.",
      },
    },
    {
      id: 91,
      dimension: "O",
      facet: "creativity",
      text: "A kiszámítható, rutinszerű munkát előnyben részesítem az alkotói kihívásokkal szemben.",
      textByLocale: {
        hu: "A kiszámítható, rutinszerű munkát előnyben részesítem az alkotói kihívásokkal szemben.",
        en: "I prefer predictable, routine work over tasks that require creative thinking.",
        de: "Ich bevorzuge vorhersehbare Routineaufgaben gegenüber Tätigkeiten, die kreatives Denken erfordern.",
      },
      reversed: true,
    },
    {
      id: 92,
      dimension: "O",
      facet: "creativity",
      text: "A kreatív és alkotói munkák nem tartoznak az erősségeim közé.",
      textByLocale: {
        hu: "A kreatív és alkotói munkák nem tartoznak az erősségeim közé.",
        en: "Creative and artistic work is not among my strengths.",
        de: "Kreative und künstlerische Arbeit gehört nicht zu meinen Stärken.",
      },
      reversed: true,
    },
    {
      id: 93,
      dimension: "O",
      facet: "unconventionality",
      text: "Érdekesnek találom az olyan embereket, akik más szemszögből látják a világot.",
      textByLocale: {
        hu: "Érdekesnek találom az olyan embereket, akik más szemszögből látják a világot.",
        en: "I find people who see the world from a different angle genuinely interesting.",
        de: "Ich finde Menschen interessant, die die Welt aus einem anderen Blickwinkel betrachten.",
      },
    },
    {
      id: 94,
      dimension: "O",
      facet: "unconventionality",
      text: "Kicsit kilógok a sorból – nem passzolok teljesen a megszokott mintákba.",
      textByLocale: {
        hu: "Kicsit kilógok a sorból – nem passzolok teljesen a megszokott mintákba.",
        en: "I stand out a bit – I don't quite fit into the usual patterns.",
        de: "Ich falle etwas aus der Reihe – ich passe nicht ganz in die üblichen Muster.",
      },
    },
    {
      id: 95,
      dimension: "O",
      facet: "unconventionality",
      text: "Kerülöm a hagyományokat felrúgó és szélsőséges elképzeléseket.",
      textByLocale: {
        hu: "Kerülöm a hagyományokat felrúgó és szélsőséges elképzeléseket.",
        en: "I avoid ideas that challenge conventions or push boundaries.",
        de: "Ich meide Ideen, die Konventionen herausfordern oder Grenzen überschreiten.",
      },
      reversed: true,
    },
    {
      id: 96,
      dimension: "O",
      facet: "unconventionality",
      text: "Az elvont gondolati kísérletezés és a filozofikus vita nem igazán köt le.",
      textByLocale: {
        hu: "Az elvont gondolati kísérletezés és a filozofikus vita nem igazán köt le.",
        en: "Abstract philosophical speculation and debate don't really engage me.",
        de: "Abstrakte philosophische Spekulation und Debatte fesseln mich nicht wirklich.",
      },
      reversed: true,
    },
  ],
};
