import type { Localized } from "./questions";

/** Display catalogue only. Persisted binary codes and scoring rules are unchanged. */
export const OPERATING_CATALOGUE = {
  "0000": {"code": "SECP", "name": {"hu": "Tervezők", "en": "Planners"}, "description": {"hu": "Az információkat rendezett, visszakereshető formában osztják meg. A szerepek és felelősségek világosak, a fő döntéseket egy központi döntéshozó hozza meg, a munka pedig előre egyeztetett terv szerint halad. Ez a jelenlegi gyakorlatot írja le; önmagában nem mutatja meg, hogy a tagok mennyire kedvelik ezt a működésmódot.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["könyvelési csapat", "pénzügyi adminisztráció", "megfelelőségi terület", "szabályozott adminisztratív működés"]},
  "0001": {"code": "SECA", "name": {"hu": "Navigátorok", "en": "Navigators"}, "description": {"hu": "A szerepek, felelősségek és a döntési jogkörök világosak, az irányt többnyire a vezető jelöli ki. A megvalósítás módját ugyanakkor a csapat a helyzethez igazíthatja. Tudják, mit kell elérniük és ki hozza meg a végső döntést, de az odavezető út változhat.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["projektcsapat", "ügyfélszolgálat", "szakértői csapat egy erős vezető mellett", "olyan termék- vagy szolgáltatásfejlesztés, ahol a cél kötött, de az út változhat"]},
  "0010": {"code": "SEDP", "name": {"hu": "Rendszerépítők", "en": "System builders"}, "description": {"hu": "A munka szervezett és jól dokumentálható, a szerepek és felelősségek világosak. A döntési jogkörök több ember vagy szakterület között oszlanak meg, miközben a csapat előre egyeztetett terv szerint halad.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["nagyobb projektcsapat", "mérnöki vagy kivitelező csapat", "komplex szakértői csapat", "több önálló funkcióból álló operatív egység"]},
  "0011": {"code": "SEDA", "name": {"hu": "Fejlesztők", "en": "Developers"}, "description": {"hu": "A keretek, szerepek és alapfolyamatok világosak. A tagok a saját hatáskörükben dönthetnek, és a munka menetét is gyorsan a helyzethez igazíthatják. Az átlátható rend mellett jelentős önállóságuk van.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["érett agilis csapat", "szolgáltatásfejlesztési csapat", "több szenior szakértőből álló csapat", "önálló döntési jogosultsággal működő projektcsapat"]},
  "0100": {"code": "SOCP", "name": {"hu": "Zenekar", "en": "Orchestra"}, "description": {"hu": "Az információkat rendezetten kezelik, a fő döntéseket egy központi döntéshozó hozza meg, a munka pedig terv szerint halad. A napi feladatokat többnyire közvetlen egyeztetésekkel és a megszokott közös munkamenetre támaszkodva hangolják össze.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kis- és középvállalkozás vezetői csapata", "tulajdonosvezérelt szakértői csapat", "családi vállalkozás", "stabil, összeszokott operatív csapat"]},
  "0101": {"code": "SOCA", "name": {"hu": "Produkciós iroda", "en": "Production office"}, "description": {"hu": "Az információk könnyen hozzáférhetők, az alapkeretek világosak, és többnyire egyértelmű, ki hozza meg a végső döntést. A napi munkát a kialakult együttműködésre támaszkodva szervezik, és rugalmasan alkalmazkodnak. A vezető kijelöli az irányt, a megvalósítás módjában a csapat nagy szabadságot kap.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["kisebb tanácsadó cég", "kreatív szakértői csapat erős vezetővel", "vállalkozói környezet", "gyorsan reagáló szolgáltatócsapat"]},
  "0110": {"code": "SODP", "name": {"hu": "Céh", "en": "Guild"}, "description": {"hu": "Az információkat rendezetten kezelik, a napi munka összehangolásában pedig a tagok megszokott együttműködésére támaszkodnak. A döntési jogkörök megoszlanak, a feladatokat előre egyeztetett terv szerint, kiszámíthatóan végzik.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["mérnöki projektcsapat", "szenior szakértői csapat", "kutatás-fejlesztési projekt", "komplex ügyfélprojekt"]},
  "0111": {"code": "SODA", "name": {"hu": "Műhely", "en": "Workshop"}, "description": {"hu": "A csapat világos alapokra és könnyen hozzáférhető információkra építhet. A napi munkát a kialakult közös szokások tartják össze, a döntési jogkörök megoszlanak, a megvalósítás pedig a helyzethez igazodik. A közös kereteken belül a tagok nagyrészt maguk szervezik a munkájukat.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["agilis termékcsapat", "cross-functional innovation team", "digitális szolgáltatásfejlesztő csapat", "tapasztalt startupcsapat"]},
  "1000": {"code": "IECP", "name": {"hu": "Irányítók", "en": "Directors"}, "description": {"hu": "Az információkat többnyire közvetlenül, kötetlen formában osztják meg. A feladatokat ugyanakkor előre egyeztetik, a szerepek és elvárások világosak. A fő döntéseket egy központi döntéshozó hozza meg, a munka tervszerűen halad.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb termelőcsapat", "műhely vagy szakipari csapat", "rendezvényszervezés", "tulajdonosvezérelt szolgáltatócsapat"]},
  "1001": {"code": "IECA", "name": {"hu": "Helyzetmegoldók", "en": "Problem solvers"}, "description": {"hu": "A csapat gyorsan, közvetlenül osztja meg az információkat. A szerepek, elvárások és felelősségek világosak, a végső döntést többnyire egy vezető hozza meg. A megvalósítás módjában jelentős mozgástér marad.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["rendezvényszervező csapat", "gyors reagálású szolgáltatási csapat", "ügynökségi projektcsapat", "értékesítési csapat erős vezetővel"]},
  "1010": {"code": "IEDP", "name": {"hu": "Összehangolók", "en": "Coordinators"}, "description": {"hu": "Az információkat gyorsan, kötetlenül osztják meg, miközben a feladatokat előre egyeztetik, és a felelősségek világosak. Több tagnak is van döntési jogköre. A munka előre meghatározott célok és ütemezés szerint halad.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["szenior szakértői projektcsapat", "építészeti vagy mérnöki tervezőcsapat", "tanácsadói projektcsapat", "összetett szakmai szolgáltatás"]},
  "1011": {"code": "IEDA", "name": {"hu": "Játékmesterek", "en": "Game masters"}, "description": {"hu": "Az információkat többnyire közvetlenül osztják meg, a szerepek és felelősségek világosak. A döntési jogkörök megoszlanak, a csapat pedig gyorsan igazítja a munka menetét a helyzethez. A rugalmasság mellett is követhető marad, ki miért felel.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["kreatív ügynökségi csapat", "design-team", "gyors projektkörnyezet", "több szakterületet összefogó kampánycsapat"]},
  "1100": {"code": "IOCP", "name": {"hu": "Társulat", "en": "Ensemble"}, "description": {"hu": "A napi információcsere és a munka összehangolása főként személyes kapcsolatokra és kötetlen egyeztetésekre épül. A fő döntéseket egy központi döntéshozó hozza meg. Ha az irány már világos, a csapat előre egyeztetett terv szerint halad.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb szolgáltatóvállalkozás", "családi vállalkozás", "tulajdonos által vezetett szakértői csapat", "összeszokott operatív egység"]},
  "1101": {"code": "IOCA", "name": {"hu": "Stáb", "en": "Crew"}, "description": {"hu": "A mindennapi munkát személyes egyeztetések, bizalom és a helyzetből adódó feladatmegosztás tartja össze. A végső döntést jellemzően egy vezető vagy tulajdonos hozza meg. A csapat a megvalósításban nagy szabadságot kap, és gyorsan alkalmazkodik.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["induló startup alapítói csapata", "kis kreatív vállalkozás", "kis létszámú, szakosodott tanácsadócég", "vállalkozó által vezetett kis csapat"]},
  "1110": {"code": "IODP", "name": {"hu": "Alkotótársak", "en": "Co-creators"}, "description": {"hu": "A napi együttműködést kevés formális szabály köti. Az információcsere és a feladatok összehangolása főként a személyes kapcsolatokra épül, a döntési jogkörök megoszlanak. A csapat ugyanakkor az előre vállalt terv és teljesítési célok szerint halad.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["szenior szakértőkből álló projektcsapat", "filmes vagy produkciós csapat", "kutatócsoport", "szakmai partnerhálózat"]},
  "1111": {"code": "IODA", "name": {"hu": "Rögtönzők", "en": "Improvisers"}, "description": {"hu": "Kevés a formális keret: az információkat közvetlenül osztják meg, a feladatokat pedig a helyzethez és az egymás közötti kapcsolatokhoz igazodva hangolják össze. Ott születik döntés, ahol a legtöbb szükséges információ rendelkezésre áll. A munka menete folyamatosan alakul; a csapat nagyrészt maga szervezi a működését.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["korai fázisú startup", "kis innovációs csapat", "kreatív kollektíva", "magas bizalmi szinttel működő szenior csapat"]},
} as const satisfies Record<string, { code: string; name: Localized; description: Localized; examples: readonly string[] }>;
export type CatalogueKey = keyof typeof OPERATING_CATALOGUE;
export const OPERATING_FAMILIES = [
  { code: "SE", name: { hu: "Mérnökök", en: "Engineers" }, tone: "bg-bronze-soft" },
  { code: "SO", name: { hu: "Mesterek", en: "Masters" }, tone: "bg-sage-soft" },
  { code: "IE", name: { hu: "Szervezők", en: "Organizers" }, tone: "bg-[var(--color-layer-org-soft)]" },
  { code: "IO", name: { hu: "Alkotóközösségek", en: "Creative communities" }, tone: "bg-[var(--color-layer-team-soft)]" },
] as const;
export function cataloguePattern(key: string | null | undefined) {
  return key && Object.hasOwn(OPERATING_CATALOGUE, key) ? OPERATING_CATALOGUE[key as CatalogueKey] : null;
}
