import type { Localized } from "./questions";

/** Display catalogue only. Persisted binary codes and scoring rules are unchanged. */
export const OPERATING_CATALOGUE = {
  "0000": {"code": "SECP", "name": {"hu": "Tervezők", "en": "Planners"}, "description": {"hu": "A Tervezők mintázatában a csapat tagjai közös, visszakereshető formában rögzítik az információkat. Előre tisztázzák, ki miért felel, a fő döntéseket pedig egy kijelölt vezető hozza meg. A munka egyeztetett terv szerint halad. Ez a munkaszervezés módját írja le; önmagában nem mondja meg, mennyire kedvelik a tagok ezt a működést.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["könyvelési csapat", "pénzügyi adminisztráció", "megfelelőségi terület", "szabályozott adminisztratív működés"]},
  "0001": {"code": "SECA", "name": {"hu": "Navigátorok", "en": "Navigators"}, "description": {"hu": "A Navigátorok mintázatában a csapat tagjai közös, visszakereshető formában rögzítik az információkat, és előre tisztázzák, ki miért felel. A fő döntéseket egy kijelölt vezető hozza meg. A megvalósítás menetén a csapat a helyzethez igazodva változtat.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["projektcsapat", "ügyfélszolgálat", "szakértői csapat egy erős vezető mellett", "olyan termék- vagy szolgáltatásfejlesztés, ahol a cél kötött, de az út változhat"]},
  "0010": {"code": "SEDP", "name": {"hu": "Rendszerépítők", "en": "System builders"}, "description": {"hu": "A Rendszerépítők mintázatában a csapat tagjai visszakereshetően rögzítik az információkat, és előre tisztázzák a feladatokat. Több ember vagy szakterület is kap döntési jogkört. A munka az előre egyeztetett tervet követi.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["nagyobb projektcsapat", "mérnöki vagy kivitelező csapat", "komplex szakértői csapat", "több önálló funkcióból álló operatív egység"]},
  "0011": {"code": "SEDA", "name": {"hu": "Fejlesztők", "en": "Developers"}, "description": {"hu": "A Fejlesztők mintázatában a csapat tagjai közös, visszakereshető formában rögzítik az információkat. Előre tisztázzák, ki miért felel, és a tagok a saját hatáskörükben döntenek. A munka menetét a tapasztalataikhoz igazítják.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["érett agilis csapat", "szolgáltatásfejlesztési csapat", "több szenior szakértőből álló csapat", "önálló döntési jogosultsággal működő projektcsapat"]},
  "0100": {"code": "SOCP", "name": {"hu": "Zenekar", "en": "Orchestra"}, "description": {"hu": "A Zenekar mintázatában a csapat tagjai rendezetten, visszakereshetően kezelik az információkat. A napi feladatokat közvetlen egyeztetésekkel és a közös szokásaikra támaszkodva hangolják össze. A fő döntéseket egy kijelölt vezető hozza meg, a munka pedig előre egyeztetett terv szerint halad.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kis- és középvállalkozás vezetői csapata", "tulajdonosvezérelt szakértői csapat", "családi vállalkozás", "stabil, összeszokott operatív csapat"]},
  "0101": {"code": "SOCA", "name": {"hu": "Produkciós iroda", "en": "Production office"}, "description": {"hu": "A Produkciós iroda mintázatában a csapat tagjai visszakereshetően rögzítik az információkat, a napi feladatokat pedig közvetlen egyeztetésekkel hangolják össze. A fő döntéseket egy kijelölt vezető hozza meg. A megvalósítás módját a csapat a helyzethez igazítja.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["kisebb tanácsadó cég", "kreatív szakértői csapat erős vezetővel", "vállalkozói környezet", "gyorsan reagáló szolgáltatócsapat"]},
  "0110": {"code": "SODP", "name": {"hu": "Céh", "en": "Guild"}, "description": {"hu": "A Céh mintázatában a csapat tagjai visszakereshetően rögzítik az információkat. A napi munkát közvetlen egyeztetésekkel és a közös szokásaikra támaszkodva hangolják össze. Több tagnak is van döntési jogköre, a feladatokkal pedig előre egyeztetett terv szerint haladnak.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["mérnöki projektcsapat", "szenior szakértői csapat", "kutatás-fejlesztési projekt", "komplex ügyfélprojekt"]},
  "0111": {"code": "SODA", "name": {"hu": "Műhely", "en": "Workshop"}, "description": {"hu": "A Műhely mintázatában a csapat tagjai visszakereshetően rögzítik az információkat, a napi munkát pedig közvetlen egyeztetésekkel hangolják össze. A tagok a saját hatáskörükben döntenek, és a megvalósítás módját is a helyzethez igazítják.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["agilis termékcsapat", "több szakterületet összefogó innovációs csapat", "digitális szolgáltatásfejlesztő csapat", "tapasztalt startupcsapat"]},
  "1000": {"code": "IECP", "name": {"hu": "Irányítók", "en": "Directors"}, "description": {"hu": "Az Irányítók mintázatában a csapat tagjai főként közvetlen beszélgetésekben osztják meg az információkat. Előre tisztázzák a feladatokat és a felelősségeket. A fő döntéseket egy kijelölt vezető hozza meg, a munka pedig előre egyeztetett terv szerint halad.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb termelőcsapat", "műhely vagy szakipari csapat", "rendezvényszervezés", "tulajdonosvezérelt szolgáltatócsapat"]},
  "1001": {"code": "IECA", "name": {"hu": "Helyzetmegoldók", "en": "Problem solvers"}, "description": {"hu": "A Helyzetmegoldók mintázatában a csapat tagjai főként közvetlen beszélgetésekben osztják meg az információkat. Előre tisztázzák, ki miért felel, a fő döntéseket pedig egy kijelölt vezető hozza meg. A megvalósítás menetét a csapat a helyzethez igazítja.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["rendezvényszervező csapat", "gyors reagálású szolgáltatási csapat", "ügynökségi projektcsapat", "értékesítési csapat erős vezetővel"]},
  "1010": {"code": "IEDP", "name": {"hu": "Összehangolók", "en": "Coordinators"}, "description": {"hu": "Az Összehangolók mintázatában a csapat tagjai főként közvetlen beszélgetésekben osztják meg az információkat. Előre tisztázzák a feladatokat és a felelősségeket, és több tagnak is van döntési jogköre. A munka az előre egyeztetett tervet követi.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["szenior szakértői projektcsapat", "építészeti vagy mérnöki tervezőcsapat", "tanácsadói projektcsapat", "összetett szakmai szolgáltatás"]},
  "1011": {"code": "IEDA", "name": {"hu": "Játékmesterek", "en": "Game masters"}, "description": {"hu": "A Játékmesterek mintázatában a csapat tagjai főként közvetlen beszélgetésekben osztják meg az információkat. Előre tisztázzák, ki miért felel, és a saját hatáskörükben döntenek. A munka menetét a tapasztalataikhoz igazítják.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["kreatív ügynökségi csapat", "tervezőcsapat", "gyors projektkörnyezet", "több szakterületet összefogó kampánycsapat"]},
  "1100": {"code": "IOCP", "name": {"hu": "Társulat", "en": "Ensemble"}, "description": {"hu": "A Társulat mintázatában a csapat tagjai közvetlen beszélgetésekben osztják meg az információkat és hangolják össze a napi feladatokat. A fő döntéseket egy kijelölt vezető hozza meg. A megvalósítás az előre egyeztetett tervet követi.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb szolgáltatóvállalkozás", "családi vállalkozás", "tulajdonos által vezetett szakértői csapat", "összeszokott operatív egység"]},
  "1101": {"code": "IOCA", "name": {"hu": "Stáb", "en": "Crew"}, "description": {"hu": "A Stáb mintázatában a csapat tagjai közvetlen beszélgetésekben osztják meg az információkat és hangolják össze a napi feladatokat. A fő döntéseket egy kijelölt vezető hozza meg, a megvalósítás módját pedig a csapat a helyzethez igazítja.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["induló startup alapítói csapata", "kis kreatív vállalkozás", "kis létszámú, szakosodott tanácsadócég", "vállalkozó által vezetett kis csapat"]},
  "1110": {"code": "IODP", "name": {"hu": "Alkotótársak", "en": "Co-creators"}, "description": {"hu": "Az Alkotótársak mintázatában a csapat tagjai közvetlen beszélgetésekben osztják meg az információkat és hangolják össze a napi feladatokat. Több tagnak is van döntési jogköre. A munka az előre egyeztetett tervet követi.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["szenior szakértőkből álló projektcsapat", "filmes vagy produkciós csapat", "kutatócsoport", "szakmai partnerhálózat"]},
  "1111": {"code": "IODA", "name": {"hu": "Rögtönzők", "en": "Improvisers"}, "description": {"hu": "A Rögtönzők mintázatában a csapat tagjai közvetlen beszélgetésekben osztják meg az információkat és hangolják össze a napi feladatokat. A saját hatáskörükben döntenek, és a megvalósítás módját is a helyzethez igazítják.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["korai fázisú startup", "kis innovációs csapat", "kreatív kollektíva", "magas bizalmi szinttel működő szenior csapat"]},
} as const satisfies Record<string, { code: string; name: Localized; description: Localized; examples: readonly string[] }>;
export type CatalogueKey = keyof typeof OPERATING_CATALOGUE;
export const OPERATING_FAMILIES = [
  { code: "SE", name: { hu: "Mérnökök", en: "Engineers" }, tone: "bg-bronze-soft" },
  { code: "SO", name: { hu: "Mesterek", en: "Masters" }, tone: "bg-sage-soft" },
  { code: "IE", name: { hu: "Szervezők", en: "Organizers" }, tone: "bg-[var(--color-layer-org-soft)]" },
  { code: "IO", name: { hu: "Alkotóközösségek", en: "Creative communities" }, tone: "bg-[var(--color-layer-team-soft)]" },
] as const;
export function cataloguePattern(key: string | null | undefined) {
  return key && Object.hasOwn(OPERATING_CATALOGUE, key) ? OPERATING_CATALOGUE[key as CatalogueKey] : null;
}
