import type { Localized } from "./questions";

/** Display catalogue only. Persisted binary codes and scoring rules are unchanged. */
export const OPERATING_CATALOGUE = {
  "0000": {"code": "SECP", "name": {"hu": "Kijelölt pálya", "en": "Defined path"}, "description": {"hu": "A működés erősen strukturált. Az információk rendezett módon mozognak, a szerepek és felelősségek egyértelműek, a döntések jellemzően egy központi ponton születnek, a megvalósítás pedig előre tervezetten halad. A rendszer jól követhető és kiszámítható. Ez önmagában nem azt jelenti, hogy a csapat tagjai ezt a működést kedvelik, csak azt, hogy a mindennapi működésük jelenleg ilyen.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["könyvelési csapat", "pénzügyi operáció", "compliance", "szabályozott adminisztratív működés"]},
  "0001": {"code": "SECA", "name": {"hu": "Rugalmas pálya", "en": "Flexible path"}, "description": {"hu": "A keretek, felelősségek és döntési pontok egyértelműek, az irány többnyire központilag meghatározott, de a megvalósításban jelentős alkalmazkodási lehetőség van. A csapat tudja, mit kell elérnie és kinél van a végső döntés, de nem feltétlenül előre kijelölt módon jut el az eredményhez.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["projektcsapat", "ügyfélszolgáltatási operáció", "szakértői csapat egy erős vezető mellett", "olyan termék- vagy szolgáltatásfejlesztés, ahol a cél kötött, de az út változhat"]},
  "0010": {"code": "SEDP", "name": {"hu": "Rendezett önállóság", "en": "Structured autonomy"}, "description": {"hu": "A működés strukturált és jól dokumentálható, a szerepek és felelősségek világosak, de a döntések nem egyetlen vezetői pontban összpontosulnak. A különböző területek vagy szerepek saját döntési jogkörrel rendelkeznek, miközben a megvalósítás tervezetten halad.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["nagyobb projektcsapat", "engineering vagy delivery csapat", "komplex szakértői csapat", "több önálló funkcióból álló operatív egység"]},
  "0011": {"code": "SEDA", "name": {"hu": "Önállóság keretek között", "en": "Autonomy within a framework"}, "description": {"hu": "A keretek, szerepek és alapfolyamatok egyértelműek, ugyanakkor a döntések több ponton születhetnek, és a megvalósítás is képes gyorsan alkalmazkodni. A rendszer rendezettséget ad, de jelentős helyi autonómiát hagy.", "en": "Information is documented and accessible. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["érett agilis csapat", "szolgáltatásfejlesztési csapat", "több szenior szakértőből álló csapat", "önálló döntési jogosultsággal működő projektcsapat"]},
  "0100": {"code": "SOCP", "name": {"hu": "Rendezett keret, központi irány", "en": "Organized framework, central direction"}, "description": {"hu": "Az információkezelés rendezett, a fő döntések egy központi ponton születnek, a megvalósítás pedig tervezetten történik. Ugyanakkor a napi koordináció kevésbé formalizált: a csapat sokszor közvetlen egyeztetésekkel, kapcsolatokon és megszokott együttműködési mintákon keresztül hangolja össze a munkát.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb KKV vezetői csapat", "tulajdonosvezérelt szakértői csapat", "családi vállalkozás", "stabil, összeszokott operatív csapat"]},
  "0101": {"code": "SOCA", "name": {"hu": "Egy irány, szabad mozgás", "en": "One direction, room to move"}, "description": {"hu": "Az információk és alapkeretek rendezettek, a végső döntési pont többnyire egyértelmű, de a napi koordináció organikus, a megvalósítás pedig rugalmas. A vezető kijelöli az irányt, a csapat pedig jelentős szabadsággal alakítja, hogyan jut el oda.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["kisebb tanácsadó cég", "kreatív szakértői csapat erős vezetővel", "vállalkozói környezet", "gyorsan reagáló szolgáltatócsapat"]},
  "0110": {"code": "SODP", "name": {"hu": "Tervezett önállóság", "en": "Planned autonomy"}, "description": {"hu": "Az információkezelés rendezett, de a napi koordináció jelentős részben a csapat természetes együttműködésén alapul. A döntések több ponton születnek, miközben a megvalósítás tervezett és kiszámítható.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["mérnöki projektcsapat", "szenior szakértői csapat", "kutatás-fejlesztési projekt", "komplex ügyfélprojekt"]},
  "0111": {"code": "SODA", "name": {"hu": "Önszervező keret", "en": "Self-organizing framework"}, "description": {"hu": "A működés rendelkezik stabil alapokkal és jól hozzáférhető információkkal, de a napi koordináció nagyrészt organikusan történik. A döntések elosztottak, a megvalósítás pedig alkalmazkodik a helyzethez. Ez egy olyan működés, ahol a keretek megtartják a csapatot, de azon belül jelentős önszerveződés történik.", "en": "Information is documented and accessible. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["agilis termékcsapat", "cross-functional innovation team", "digitális szolgáltatásfejlesztő csapat", "érett startup-team"]},
  "1000": {"code": "IECP", "name": {"hu": "Közvetlen csatorna, feszes irány", "en": "Direct channels, clear direction"}, "description": {"hu": "Az információk gyakran közvetlenül és kevésbé formalizált módon mozognak, miközben a koordináció, a szerepek és az elvárások egyértelműek. A fő döntések központilag születnek, és a megvalósítás tervszerűen halad.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb termelőcsapat", "műhely vagy szakipari csapat", "eseményszervezési operáció", "tulajdonosvezérelt szolgáltatócsapat"]},
  "1001": {"code": "IECA", "name": {"hu": "Központi irány, gyors reakció", "en": "Central direction, quick response"}, "description": {"hu": "A csapat közvetlenül és gyorsan oszt meg információt. A szerepek, elvárások és felelősségek egyértelműek, a végső döntés többnyire egy vezetői pontban koncentrálódik, de a megvalósítás nagy mozgásteret enged.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["rendezvényszervező csapat", "gyors reagálású szolgáltatási csapat", "ügynökségi projektteam", "értékesítési csapat erős vezetővel"]},
  "1010": {"code": "IEDP", "name": {"hu": "Helyi döntés, közös menetrend", "en": "Local decisions, shared schedule"}, "description": {"hu": "Az információk gyorsan és informálisan mozognak, miközben a koordináció és a felelősségek tiszták. A döntési jogkör több szerep között oszlik meg, a megvalósítás viszont előre meghatározott célok és ütemezés szerint halad.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["szenior szakértői projektcsapat", "építészeti vagy mérnöki tervezőcsapat", "tanácsadói projektteam", "összetett szakmai szolgáltatás"]},
  "1011": {"code": "IEDA", "name": {"hu": "Rugalmas háló", "en": "Flexible network"}, "description": {"hu": "Az információk jellemzően közvetlenül mozognak, miközben a szerepek és felelősségek világosak. A döntési jogkör megosztott, a megvalósítás pedig erősen alkalmazkodó. A csapat gyorsan képes reagálni, miközben a felelősségi viszonyok nem vesznek el.", "en": "Information moves through direct conversations. Explicit roles and processes coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["kreatív ügynökségi csapat", "design-team", "gyors projektkörnyezet", "cross-functional kampánycsapat"]},
  "1100": {"code": "IOCP", "name": {"hu": "Laza háló, feszes irány", "en": "Informal network, clear direction"}, "description": {"hu": "A napi információáramlás és koordináció nagyrészt informálisan és kapcsolati alapon működik. A fő döntések azonban egy központi pontban összpontosulnak, és amikor az irány megszületik, a megvalósítás tervezetten történik.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery follows agreed plans and milestones."}, "examples": ["kisebb szolgáltatóvállalkozás", "családi vállalkozás", "tulajdonos által vezetett szakértői csapat", "összeszokott operatív egység"]},
  "1101": {"code": "IOCA", "name": {"hu": "Központi irány, laza háló", "en": "Central direction, informal network"}, "description": {"hu": "A mindennapi működés sok személyes egyeztetésen, bizalmon és spontán koordináción alapul. A végső döntési pont ugyanakkor jellemzően egy vezető vagy tulajdonos. A megvalósításban nagy a rugalmasság: a csapat gyorsan alkalmazkodik a helyzethez.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Key decisions are concentrated at a central point. Delivery adapts to the situation."}, "examples": ["korai fázisú startup alapítói csapat", "kis kreatív vállalkozás", "butik tanácsadócég", "vállalkozó által vezetett kis csapat"]},
  "1110": {"code": "IODP", "name": {"hu": "Szabad áramlás, tervezett szállítás", "en": "Free flow, planned delivery"}, "description": {"hu": "A napi együttműködés kevéssé formalizált. Az információ és a koordináció természetesen, kapcsolatokon keresztül mozog, a döntések több ponton születnek, ugyanakkor a csapat képes előre vállalt terv vagy szállítási cél szerint haladni.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery follows agreed plans and milestones."}, "examples": ["szenior szakértőkből álló projektcsapat", "filmes vagy produkciós csapat", "kutatócsoport", "szakmai partnerhálózat"]},
  "1111": {"code": "IODA", "name": {"hu": "Önszervező áramlás", "en": "Self-organizing flow"}, "description": {"hu": "Kevés a formális keret. Az információk közvetlenül és gyorsan mozognak, a koordináció nagyrészt kapcsolati és helyzetfüggő, a döntések ott születnek, ahol éppen a legtöbb releváns információ van, a megvalósítás pedig folyamatosan alkalmazkodik. Ez az egyik legerősebben önszerveződő működési minta.", "en": "Information moves through direct conversations. Direct conversations and shared routines coordinate work. Decision authority is distributed across roles. Delivery adapts to the situation."}, "examples": ["korai fázisú startup", "kis innovációs csapat", "kreatív kollektíva", "magas bizalmi szinttel működő szenior csapat"]},
} as const satisfies Record<string, { code: string; name: Localized; description: Localized; examples: readonly string[] }>;
export type CatalogueKey = keyof typeof OPERATING_CATALOGUE;
export const OPERATING_FAMILIES = [
  { code: "SE", name: { hu: "Tiszta keretek", en: "Clear frameworks" }, tone: "bg-bronze-soft" },
  { code: "SO", name: { hu: "Rendezett háló", en: "Organized network" }, tone: "bg-sage-soft" },
  { code: "IE", name: { hu: "Közvetlen rend", en: "Direct coordination" }, tone: "bg-[var(--color-layer-org-soft)]" },
  { code: "IO", name: { hu: "Élő hálózat", en: "Living network" }, tone: "bg-[var(--color-layer-team-soft)]" },
] as const;
export function cataloguePattern(key: string | null | undefined) {
  return key && Object.hasOwn(OPERATING_CATALOGUE, key) ? OPERATING_CATALOGUE[key as CatalogueKey] : null;
}
