// A publikus Team Scan-ígéret egyetlen forrása. Ezeket a szövegeket a
// landing, pricing, pilot és about nézetek is ugyanebből a szerződésből
// kapják, így a kötelező rétegek és az opcionális modulok nem sodródhatnak
// szét oldalak között.
const TEAM_SCAN_CONTRACT = {
  layerCount: { hu: "Három alapréteg", en: "Three core layers" },
  summary: {
    hu: "A Team Scan v1 három alaprétege az önértékelés, a mért bizalmi háló és a pszichológiai biztonság névtelen pulse-a. Az eredményekből tanácsadó által ellenőrzött csapatkép és célmutatóhoz kötött akció készül, amit a következő körben visszamérünk.",
    en: "Team Scan v1 combines three core layers: self-assessment, a measured trust network, and an anonymous psychological safety pulse. A consultant reviews the evidence, creates the team picture, links an action to a target metric, and the next round measures the outcome again.",
  },
  layer1Title: { hu: "Önértékelés — hat személyiségdimenzió", en: "Self-assessment — six personality dimensions" },
  layer1Desc: {
    hu: "Egy nagyjából 10 perces kérdőív, szabadon felhasználható, kutatásban használt kérdésbankból. Ez adja az alapot: milyen tartós mintázatok mozgatnak valakit munkahelyi helyzetekben.",
    en: "An approximately 10-minute questionnaire drawn from a freely usable item pool used in research. This is the foundation: which stable patterns drive someone in work situations.",
  },
  layer1Tag: { hu: "~10 perc · egyéni", en: "~10 min · individual" },
  layer2Title: { hu: "Bizalmi háló — hogyan kapcsolódik a csapat", en: "Trust network — how the team connects" },
  layer2Desc: {
    hu: "Öt rövid kérdés csapattársanként arról, hogyan működik a tényleges együttműködés. A riport a lefedettséget, kapcsolódási központokat és beágyazatlan pontokat anonimitási kapukkal mutatja.",
    en: "Five short questions per teammate about how collaboration actually works. The report shows coverage, connectors, and unembedded points behind anonymity gates.",
  },
  layer2Tag: { hu: "mért reláció · csapatszint", en: "measured relation · team level" },
  layer3Title: { hu: "Pszichológiai biztonság — mennyire szabad hibázni", en: "Psychological safety — how safe it is to fail" },
  layer3Desc: {
    hu: "Nyolc állításos, névtelen pulzusmérés arról, mennyire biztonságos kérdezni, ellentmondani és hibát bevallani. Kizárólag összesített csapatképben jelenik meg.",
    en: "An anonymous eight-item pulse on how safe it feels to ask, disagree and admit a mistake. It is shown only as an aggregated team picture.",
  },
  layer3Tag: { hu: "8 állítás · névtelen pulse", en: "8 items · anonymous pulse" },
  optionalLabel: { hu: "Opcionális kiegészítők", en: "Optional add-ons" },
  optionalObserver: { hu: "Observer-visszajelzés", en: "Observer feedback" },
  optionalPeer: { hu: "Peer-kör", en: "Peer round" },
  optionalRoles: { hu: "Csapatszerepek", en: "Team roles" },
  outcomeDesc: {
    hu: "A három alaprétegből tanácsadó által ellenőrzött és értelmezett összkép készül — nem algoritmus dobja ki. A publikált kép mindig aggregált: egyéni értékek nem látszanak benne.",
    en: "The three core layers become an aggregate picture that a consultant reviews and interprets — it isn't generated by an algorithm. What gets published is always aggregated: individual values never appear.",
  },
} as const;

export const landingTranslations = {
  landing: {
    heroTitle: {
      hu: "Trita — személyiség- és csapatintelligencia platform",
      en: "Trita — personality and team intelligence platform",
    },

    // ─── New landing page (self/team) ────────────────────────────────
    // HeroSection — self
    selfEyebrow: { hu: "ÖNISMERET ÉS CSAPATMŰKÖDÉS", en: "SELF-AWARENESS AND TEAMWORK" },
    selfHeadlineBefore: { hu: "Értsd meg, hogyan működsz — és mit viszel a ", en: "Understand how you work — and what you bring to the " },
    selfHeadlineEm: { hu: "csapatba.", en: "team." },
    selfSub: { hu: "Megmutatjuk, milyen mintázatok mozgatnak, miben vagy erős, és hogyan jelenik meg mindez a közös munkában — érthetően, egy helyen.", en: "See which patterns drive you, where your strengths lie, and how they show up when you work with others — clearly, in one place." },
    selfCta: { hu: "Ingyenes teszt indítása", en: "Start free assessment" },
    selfCtaContinue: { hu: "Folytasd a tesztet", en: "Continue assessment" },
    selfCtaContinueShort: { hu: "Folytatom", en: "Continue" },
    selfMetaTime: { hu: "~10 perc", en: "~10 minutes" },
    selfMetaMethod: { hu: "Tudományos modell", en: "Scientific model" },
    selfMetaInstant: { hu: "Azonnali eredmény", en: "Instant results" },
    selfMetaFree: { hu: "Ingyenes indulás", en: "Free to start" },
    selfPanelEyebrow: { hu: "A te profilod", en: "Your profile" },
    sampleBadge: { hu: "Minta", en: "Sample" },
    selfPanelName: { hu: "Péter", en: "Peter" },
    selfPanelType: { hu: "Hídépítő", en: "Bridge-Builder" },
    // A domináns A-dimenzió A_high munkastílusához rendelt valós szerep.
    selfPanelRole: { hu: "Facilitátor", en: "Facilitator" },
    selfPanelInsight: { hu: "Emberek és álláspontok között teremtesz közös nevezőt — az elveid stabil alapot adnak hozzá.", en: "You create common ground between people and viewpoints — your principles give it a stable foundation." },
    // Dimenzió-sáv a valódi eredménynézet (DimensionStrip) mintájára — H E X A C O sorrend
    selfDim1: { hu: "Becsületesség-Alázat", en: "Honesty-Humility" },
    selfDim2: { hu: "Emocionalitás", en: "Emotionality" },
    selfDim3: { hu: "Extraverzió", en: "Extraversion" },
    selfDim4: { hu: "Barátságosság", en: "Agreeableness" },
    selfDim5: { hu: "Lelkiismeretesség", en: "Conscientiousness" },
    selfDim6: { hu: "Nyitottság", en: "Openness" },
    selfStrLabel: { hu: "Erősségeid", en: "Your strengths" },
    // Szerepkör-illeszkedés teaser — a valódi RoleFitSection "erős" sora
    selfRoleFitEyebrow: { hu: "Természetes csapatszerepeid", en: "Team roles that come naturally" },
    selfRole1: { hu: "Csapatépítés", en: "Team Building" },
    selfRole2: { hu: "Facilitáció", en: "Facilitation" },
    selfRole3: { hu: "Coaching", en: "Coaching" },
    selfFadeCta: { hu: "Ízelítő a profilodból", en: "A taste of your profile" },
    // HeroSection — team
    teamEyebrow: { hu: "CSAPATINTELLIGENCIA PLATFORM", en: "TEAM INTELLIGENCE PLATFORM" },
    teamHeadlineBefore: { hu: "Értsd meg jobban a ", en: "Better understand your " },
    teamHeadlineEm: { hu: "csapatod működését.", en: "team's dynamics." },
    teamSub: { hu: "A Trita megmutatja, ami eddig láthatatlan volt — a csapatod valódi dinamikáját. Még mielőtt a feszültségből konfliktus lenne.", en: "Trita reveals what was previously invisible — your team's true dynamics. Before tension turns into conflict." },
    teamCta: { hu: "Megnézem a pilotprogramot", en: "Explore the pilot program" },
    teamSecondaryCta: { hu: "Beszéljünk", en: "Talk to us" },
    teamMicrocopy: { hu: "Személyes onboarding · egyedi ajánlat · első kép néhány napon belül", en: "Personal onboarding · custom offer · first picture within days" },
    teamMetaOnboarding: { hu: "Személyes onboarding", en: "Personal onboarding" },
    teamMetaTiming: { hu: "Néhány nap az első képig", en: "First picture within days" },
    teamMetaOffer: { hu: "Egyedi ajánlat", en: "Custom offer" },
    teamFadeCta: { hu: "Ízelítő a csapatképből", en: "A taste of your team picture" },
    // Team hero panel — a valódi publikált riport (TeamReportView) kicsinyített mása
    teamPanelEyebrow: { hu: "jóváhagyott csapatkép", en: "reviewed team picture" },
    teamPanelTitle: { hu: "Értékesítés", en: "Sales" },
    teamPanelValidated: { hu: "Tanácsadó által jóváhagyva", en: "Reviewed by a consultant" },
    teamPanelPublished: { hu: "Publikált", en: "Published" },
    teamStatMembersLabel: { hu: "Tagok", en: "Members" },
    teamStatCompletionLabel: { hu: "Kitöltöttség", en: "Completion" },
    teamAxisDrive: { hu: "Hajtóerő", en: "Drive" },
    teamAxisCohesion: { hu: "Kohézió", en: "Cohesion" },
    teamAxisDiscipline: { hu: "Fegyelem", en: "Discipline" },
    teamAxisOpenness: { hu: "Nyitottság", en: "Openness" },
    teamPrivacyNote: { hu: "Csapatátlag — egyéni értékek nem jelennek meg.", en: "Team average — individual values are not shown." },
    teamPatternLabel: { hu: "Csapatmintázat", en: "Team pattern" },
    teamPatternName: { hu: "Családi Vállalkozás", en: "Family Business" },
    teamNarrativeLabel: { hu: "Tanácsadói értékelés", en: "Consultant assessment" },
    teamNarrativeText: { hu: "Aktív, lojális csapat, amely a bevált utakon halad, de rugalmasan alkalmazkodik. Az elkötelezettség az összetartó erő.", en: "An active, loyal team that follows proven paths while adapting flexibly. Commitment is what holds it together." },
    // HowItWorks
    howSelfTitleBefore: { hu: "Három lépésben kapsz használható képet ", en: "Three steps to a usable picture of " },
    howSelfTitleEm: { hu: "magadról", en: "yourself" },
    howTeamTitleBefore: { hu: "Három lépésben kapsz ", en: "Three steps to your " },
    howTeamTitleEm: { hu: "csapatképet", en: "team picture" },
    howSelf1Title: { hu: "Kitöltöd", en: "Fill it out" },
    howSelf1Desc: { hu: "Végigmész a kérdéseken ~10 perc alatt — készülni nem kell rá.", en: "Done in ~10 minutes. No preparation needed." },
    howSelf2Title: { hu: "Megkapod a profilodat", en: "Get your profile" },
    howSelf2Desc: { hu: "Azonnal látod a fő mintázataidat és az erősségeidet.", en: "See your key patterns and strengths right away." },
    howSelf3Title: { hu: "Látod, mit viszel a csapatba", en: "See what you bring to the team" },
    howSelf3Desc: { hu: "Kiderül, milyen csapatszerepek állnak közel hozzád, és milyen közegben működsz jól.", en: "Discover which team roles come naturally to you and what kind of environment helps you thrive." },
    howTeam1Title: { hu: "Meghívod a csapatot", en: "Invite your team" },
    howTeam1Desc: { hu: "Az első egyeztetés után egy linket küldesz, mindenki kitölti egyénileg.", en: "After the first conversation you send a link, and everyone fills it out individually." },
    howTeam2Title: { hu: "Tanácsadói ellenőrzés", en: "Consultant review" },
    howTeam2Desc: { hu: "Az összevetett profilokból néhány napon belül csapatkép készül — publikálás előtt tanácsadó ellenőrzi és értelmezi.", en: "Within days, the compared profiles become a team picture — reviewed and interpreted by a consultant before publishing." },
    howTeam3Title: { hu: "Közösen értelmezzük", en: "We interpret it together" },
    howTeam3Desc: { hu: "Feszültségpontok, erősségek, fejlesztési irányok — egy közös workshopon beszéljük át, mit kezdjetek velük.", en: "Friction points, strengths, development directions — in a joint workshop we discuss what to do with them." },
    // Features
    featuresTitleBefore: { hu: "Nem csak eredményt kapsz, hanem ", en: "You don't just get results — you get " },
    featuresTitleEm: { hu: "használható irányt", en: "actionable direction" },
    selfFeat1Badge: { hu: "Profil", en: "Profile" },
    selfFeat1Title: { hu: "Személyiségprofil", en: "Personality Profile" },
    selfFeat1Desc: { hu: "Látod, milyen mintázatok mozgatnak a munkahelyi helyzetekben.", en: "See which patterns drive you in workplace situations." },
    selfFeat2Badge: { hu: "Csapatszerep", en: "Team role" },
    selfFeat2Title: { hu: "Működésed a csapatban", en: "How you work in a team" },
    selfFeat2Desc: { hu: "Látod, milyen szerepet veszel fel természetesen, és hol tudsz a legtöbbet hozzátenni.", en: "See which role you naturally take on and where you can contribute the most." },
    selfFeat3Badge: { hu: "Fejlődés", en: "Growth" },
    selfFeat3Title: { hu: "Fejlődési fókusz", en: "Growth Focus" },
    selfFeat3Desc: { hu: "Kapaszkodót kapsz ahhoz, hogy min érdemes tovább dolgoznod.", en: "Get a starting point for what's worth working on." },
    teamFeat1Badge: { hu: "Dinamika", en: "Dynamics" },
    teamFeat1Title: { hu: "Mért bizalmi háló", en: "Measured trust network" },
    teamFeat1Desc: { hu: "Páronkénti kapcsolati adatokból látszik, hol erős a bizalom, hol szakad a háló, és hol kevés még az evidencia.", en: "Pairwise relationship data shows where trust is strong, where the network breaks, and where evidence is still limited." },
    teamFeat2Badge: { hu: "Biztonság", en: "Safety" },
    teamFeat2Title: { hu: "Pszichológiai biztonság", en: "Psychological Safety" },
    teamFeat2Desc: { hu: "Névtelen pulzusmérés arról, mennyire biztonságos hibázni, kérdezni, ellentmondani.", en: "An anonymous pulse on how safe it feels to fail, ask, and disagree." },
    teamFeat3Badge: { hu: "Csapatkép", en: "Team picture" },
    teamFeat3Title: { hu: "Jóváhagyott csapatkép", en: "Reviewed team picture" },
    teamFeat3Desc: { hu: "Vezetői összefoglaló: erősségek, kockázatok, javaslatok.", en: "Executive summary: strengths, risks, recommendations." },
    // ProofSection
    proofTitleBefore: { hu: "Miért más ez, mint egy ", en: "Why is this different from an " },
    proofTitleEm: { hu: "átlagos személyiségteszt?", en: "average personality test?" },
    proof1Title: { hu: "Tudományos alap", en: "Scientific foundation" },
    proof1Desc: { hu: "Tudományos személyiségmodellekre épül, nem egy internetes kvíz.", en: "Built on scientific personality models, not an internet quiz." },
    proof2Title: { hu: "Nem csak címkéz", en: "Not just labels" },
    proof2Desc: { hu: "Nem áll meg egy típusnévnél — megmutatja, hogyan jelennek meg a mintáid a közös munkában.", en: "It doesn't stop at a type name — it shows how your patterns shape the way you work with others." },
    proof3Title: { hu: "Gyakorlati nyelven", en: "Practical language" },
    proof3Desc: { hu: "Nem pszichológiai zsargonban beszél, hanem úgy, ahogy te gondolkodsz a munkádról.", en: "Speaks how you think about work, not psychological jargon." },
    proofTestimonial: { hu: "Most értettem meg először, miért vállalom mindig ugyanazt a szerepet a csapatban.", en: "For the first time, I understood why I keep taking on the same role in a team." },
    proofTestimonialAuthor: { hu: "— Korai felhasználó, 31 éves termékmenedzser", en: "— Early user, 31-year-old Product Manager" },
    // ProofSection — team mód ("Miért más?" megkülönböztető történet)
    proofTeamTitleBefore: { hu: "Miért más ez, mint egy ", en: "Why is this different from an " },
    proofTeamTitleEm: { hu: "átlagos csapatfelmérés?", en: "average team survey?" },
    proofTeam1Title: { hu: "Kapcsolatot is mér", en: "Measures relationships too" },
    proofTeam1Desc: { hu: "Az engagement-átlag mellé páronkénti bizalmi háló kerül: nemcsak azt látjuk, mit gondol a csapat, hanem azt is, hogyan kapcsolódik.", en: "Pairwise trust data sits next to survey averages: we see not only what the team thinks, but how it connects." },
    proofTeam2Title: { hu: "A változékony réteget méri vissza", en: "Remeasures what can change" },
    proofTeam2Desc: { hu: "A pszichológiai biztonságot és a bizalmi hálót az akció után újramérjük; a stabil személyiségprofil kontroll, nem fejlődési címke.", en: "We remeasure psychological safety and the trust network after action; stable personality profiles are a control, not an improvement label." },
    proofTeam3Title: { hu: "Tanácsadó ellenőrzi", en: "Consultant-reviewed" },
    proofTeam3Desc: { hu: "A csapatképet nem algoritmus dobja ki: publikálás előtt tanácsadó ellenőrzi és értelmezi, a becsült adat pedig mindig jelölve van.", en: "The team picture isn't spit out by an algorithm: a consultant reviews and interprets it before publishing, and estimated data is always labeled." },
    // StatsBar
    // Egységes kitöltési idő (design-akciólista #4): a hero chip, a
    // StatsBar és a marketing copy ugyanazt az értéket használja.
    statMinValue: { hu: "~10", en: "~10" },
    statMinSuffix: { hu: " perc", en: " min" },
    statMinLabel: { hu: "átlagos kitöltés", en: "average completion" },
    statDimLabel: { hu: "személyiség dimenzió", en: "personality dimensions" },
    statResultValue: { hu: "azonnali", en: "instant" },
    statResultLabel: { hu: "eredmény, várakozás nélkül", en: "result, no waiting" },
    statSelfValue: { hu: "önismerettől a csapatműködésig", en: "from self-awareness to teamwork" },
    statSelfLabel: { hu: "egy közös rendszerben", en: "in one connected system" },
    // StatsBar — team mód
    statTeamMinLabel: { hu: "tagonkénti kitöltés", en: "per-member completion" },
    statTeamPictureValue: { hu: "néhány nap", en: "days" },
    statTeamPictureLabel: { hu: "a jóváhagyott csapatképig", en: "to a reviewed team picture" },
    // A korábbi „16 felismerhető csapatmintázat" stat kivezetve: a /patterns
    // felület parkolt, és a playbook szerint a minta „értelmezési nyelv, nem
    // validált csapattípus" — a stat a Scan v1 tényleges rétegeit mondja.
    statTeamLayersLabel: { hu: "mérési réteg a Team Scan v1-ben", en: "measurement layers in Team Scan v1" },
    // CtaSection
    ctaSelfHeadlineBefore: { hu: "~10 perc, és jobban érted, ", en: "In ~10 minutes, understand " },
    ctaSelfHeadlineEm: { hu: "mit viszel a csapatba.", en: "what you bring to the team." },
    ctaSelfSub: { hu: "Indítsd el most a tesztet, és lásd, milyen mintázatok mozgatnak, és milyen szerepet veszel fel természetesen a közös munkában.", en: "Start the assessment and see which patterns drive you and which role you naturally take on when working with others." },
    ctaSelfCta: { hu: "Elindítom a tesztet", en: "Start the test" },
    ctaSelfSecondary: { hu: "Együttműködés részletei", en: "How we work" },
    ctaSelfMicrocopy: { hu: "Ingyenes indulás · azonnali első eredmény", en: "Free start · instant first result" },
    ctaTeamHeadlineBefore: { hu: "Készen álltok az első ", en: "Ready for your first " },
    ctaTeamHeadlineEm: { hu: "közös képre?", en: "shared picture?" },
    ctaTeamSub: { hu: "A pilotban személyes onboardinggal indulunk, és néhány napon belül megkapjátok az első tanácsadó által jóváhagyott csapatképet.", en: "The pilot starts with personal onboarding, and within days you'll receive your first consultant-reviewed team picture." },
    ctaTeamCta: { hu: "Jelentkezem a pilotprogramba", en: "Apply to the pilot program" },
    ctaTeamMicrocopy: { hu: "Személyes onboarding · néhány nap az első eredményig", en: "Personal onboarding · first result within days" },
  },
  pricing: {
    // SEO: a cím a KERESETT szolgáltatás-megnevezéssel kezdődik
    // („csapatfejlesztés", „csapatdiagnosztika"), nem a belső
    // „Együttműködés" fejezetcímmel — utóbbira nincs keresés. A description
    // kihasználja a snippet-hosszt (~155 kar.), és előre hozza a két
    // döntési tényt: az egyéni rész ingyenes, listaár nincs.
    metaTitle: {
      hu: "Csapatfejlesztés és csapatdiagnosztika | Trita",
      en: "Team development and diagnostics | Trita",
    },
    metaDescription: {
      hu: "Az egyéni személyiségfelmérés ingyenes; a csapat- és szervezeti programok ára a létszámtól és a program mélységétől függ — listaár helyett egyedi ajánlat.",
      en: "The individual personality assessment is free; team and organizational program pricing depends on headcount and depth — an individual quote instead of list prices.",
    },
    heroEyebrow: { hu: "Együttműködés", en: "How we work" },
    heroHeading: { hu: "Előbb értsük meg, ", en: "First, let's understand " },
    heroHeadingEm: { hu: "mire van szükségetek.", en: "what you need." },
    heroSub: {
      hu: "Nincs dobozos csomag és rejtett árlista. Egy rövid egyeztetés után pontosan látjátok, mit mérünk, mi készül el és mitől függ az ajánlat.",
      en: "There is no off-the-shelf package or hidden price list. After a short conversation, you will know exactly what we measure, what you receive, and what shapes the quote.",
    },
    workflowEyebrow: { hu: "Az együttműködés menete", en: "How the engagement works" },
    workflow1Title: { hu: "Rövid egyeztetés", en: "Short conversation" },
    workflow1Body: {
      hu: "Megismerjük a csapatot, a helyzetet és azt, milyen döntéshez kell tisztább kép.",
      en: "We learn about the team, the situation, and the decision that needs a clearer picture.",
    },
    workflow2Title: { hu: "Pilotkeret", en: "Pilot scope" },
    workflow2Body: {
      hu: "Közösen kijelöljük a résztvevőket, a mérési rétegeket és a közös értelmezés keretét.",
      en: "Together we define participants, measurement layers, and the scope of the joint debrief.",
    },
    workflow3Title: { hu: "Első csapatkép", en: "First team picture" },
    workflow3Body: {
      hu: "A kitöltésekből tanácsadó által validált összkép és következő lépés készül.",
      en: "The assessments become a consultant-validated team picture and a clear next step.",
    },
    offerEyebrow: { hu: "Egyedi ajánlat", en: "Individual quote" },
    offerTitle: { hu: "A keret mindig a helyzetetekhez igazodik.", en: "The scope always fits your situation." },
    offerBody: {
      hu: "Az első beszélgetés után konkrét, átlátható ajánlatot kaptok. Ezek alakítják:",
      en: "After the first conversation you receive a concrete, transparent quote. It is shaped by:",
    },
    offerFactor1: { hu: "Csapatok és résztvevők", en: "Teams and participants" },
    offerFactor2: { hu: "Kiválasztott mérési rétegek", en: "Selected measurement layers" },
    offerFactor3: { hu: "Közös értelmezés", en: "Joint debrief" },
    offerCta: { hu: "Beszéljünk", en: "Let's talk" },
    offerPilotCta: { hu: "Megnézem a pilotprogramot", en: "Explore the pilot program" },
    selfEyebrow: { hu: "egyéni · ingyenes", en: "individual · free" },
    selfTitle: { hu: "Ismerd meg magad — ingyen", en: "Get to know yourself — for free" },
    selfBody: {
      hu: "Teljes személyiségfelmérés (~10 perc), dimenziószintű riport, munkastílus- és csapatszerep-elemzés, observer-visszajelzések. Nincs rejtett fizetős szint — az egyéni út ingyenes.",
      en: "Full personality assessment (~10 minutes), dimension-level report, work style and team-role analysis, plus observer feedback. No hidden paid tier — the individual path is free.",
    },
    selfCta: { hu: "Kipróbálom most — regisztráció nélkül", en: "Try it now — no sign-up needed" },
    teamEyebrow: { hu: "csapat és szervezet · program", en: "team & organization · program" },
    teamTitle: { hu: "Csapatprogram tanácsadói kísérettel", en: "Team program with consultant guidance" },
    teamBody: TEAM_SCAN_CONTRACT.summary,
    teamHow1: { hu: "Mérések — self, bizalmi háló, pszichológiai biztonság pulse", en: "Measurements — self, trust network, psychological safety pulse" },
    teamHow2: { hu: "Forrásjelölt, tanácsadó által ellenőrzött csapatkép", en: "Source-labelled, consultant-reviewed team picture" },
    teamHow3: { hu: "Akció és kapuzott visszamérés", en: "Action and gated remeasurement" },
    teamPriceNote: {
      hu: "Az árról őszintén: a csapat méretétől és a program mélységétől függ, ezért nem találsz itt ártáblát. Az első beszélgetés után konkrét ajánlatot kapsz — meglepetések nélkül. Az aktiválást mi intézzük, a számlázás átutalással megy.",
      en: "Honestly about pricing: it depends on team size and program depth, which is why there is no price table here. After the first conversation you get a concrete quote — no surprises. We handle activation; invoicing is by bank transfer.",
    },
    teamCta: { hu: "Mesélj a csapatodról — mi meséljük a többit", en: "Tell us about your team — we'll take it from there" },
    pilotEyebrow: { hu: "pilotprogram", en: "pilot program" },
    pilotTitle: { hu: "Pilotprogram — az első partnercsapatainknak", en: "Pilot program — for our first partner teams" },
    pilotBody: {
      hu: "90 nap teljes hozzáférés, személyes bevezetés és kiemelt figyelem — cserébe őszinte visszajelzést kérünk. Mindegy, mióta dolgoztok együtt: az számít, hogy elsőként formálnátok velünk a terméket. Korlátozott számú csapattal indulunk.",
      en: "90 days of full access, personal onboarding and close attention — in return we ask for honest feedback. It doesn't matter how long you've worked together — what matters is shaping the product with us first. We start with a limited number of teams.",
    },
    pilotCta: { hu: "Részletek", en: "Details" },
    faqHeading: { hu: "Gyakori kérdések", en: "Frequently asked questions" },
    faqQ1: { hu: "Mennyibe kerül?", en: "How much does it cost?" },
    faqA1: {
      hu: "Az egyéni felmérés ingyenes. A csapat- és szervezeti programok ára a létszámtól és a program terjedelmétől függ — az első egyeztetés után egyedi ajánlatot kapsz.",
      en: "The individual assessment is free. Team and organizational program pricing depends on headcount and scope — you get an individual quote after the first conversation.",
    },
    faqQ2: { hu: "Miért nincsenek listaárak?", en: "Why are there no list prices?" },
    faqA2: {
      hu: "Mert nem dobozos terméket adunk: minden program tanácsadói munkával — validálással, értelmezéssel, workshoppal — jár, és ennek terjedelme csapatonként más. Listaár helyett azt mondjuk meg pontosan, mit kapsz, és mitől függ az ár.",
      en: "Because this is not an off-the-shelf product: every program includes consultant work — validation, interpretation, workshops — and its scope differs by team. Instead of list prices, we tell you exactly what you get and what the price depends on.",
    },
    faqQ3: { hu: "Hogyan indul az együttműködés?", en: "How does the engagement start?" },
    faqA3: {
      hu: "Írsz nekünk a kapcsolat oldalon, átbeszéljük, mire van szükségetek, és ajánlatot kapsz. Elfogadás után mi aktiváljuk a szervezetet és kísérjük a bevezetést.",
      en: "You write to us on the contact page, we discuss what you need, and you receive a quote. After acceptance we activate your organization and guide the rollout.",
    },
    faqQ4: { hu: "Mi ingyenes, és mi tartozik a programhoz?", en: "What's free and what's part of the program?" },
    faqA4: {
      hu: "Minden egyéni funkció ingyenes: felmérés, riport, observer-visszajelzés. A csapatszintű mérések — csapatkép, csapatszerep-térkép, pszichológiai biztonság —, a tanácsadói validálás és a workshopok a fizetős program részei.",
      en: "All individual features are free: assessment, report, observer feedback. Team-level measurements — team picture, team role map, psychological safety —, consultant validation and workshops are part of the paid program.",
    },
    bottomHeading: { hu: "Kezdjük egy beszélgetéssel.", en: "Let's start with a conversation." },
    bottomSub: { hu: "Mesélj a csapatodról — egy munkanapon belül válaszolunk.", en: "Tell us about your team — we reply within one business day." },
    bottomCta: { hu: "Kapcsolatfelvétel", en: "Contact us" },
    ctaTrust: {
      hu: "Fordulj hozzánk bizalommal — egy munkanapon belül válaszolunk.",
      en: "Reach out anytime — we reply within one business day.",
    },
    quickAskEyebrow: { hu: "kérdésed van?", en: "got a question?" },
    quickAskTitle: { hu: "Kérdezz bátran — egy mondat is elég.", en: "Just ask — one sentence is enough." },
    quickAskBody: {
      hu: "Nem kell összeszedett brief. Írd le, mi jár a fejedben — a csapatod, egy helyzet, egy kétely —, és személyesen válaszolunk.",
      en: "No polished brief needed. Tell us what's on your mind — your team, a situation, a doubt — and you'll get a personal reply.",
    },
    quickAskName: { hu: "Neved", en: "Your name" },
    quickAskEmail: { hu: "Email címed", en: "Your email" },
    quickAskPlaceholder: {
      hu: "pl. 12 fős csapatunk van, két új vezetővel — mit tudnátok ezzel kezdeni?",
      en: "e.g. we're a team of 12 with two new leads — what could you do with that?",
    },
    quickAskMinHint: { hu: "Írj még pár szót, hogy érdemben tudjunk válaszolni.", en: "Add a few more words so we can give a useful answer." },
    quickAskSend: { hu: "Elküldöm", en: "Send it" },
    quickAskSending: { hu: "Küldés…", en: "Sending…" },
    quickAskSuccessTitle: { hu: "Megvan — köszönjük!", en: "Got it — thank you!" },
    quickAskSuccessBody: {
      hu: "Egy munkanapon belül személyesen válaszolunk a megadott címre. Addig is: az egyéni felmérést bármikor kipróbálhatod ingyen.",
      en: "You'll get a personal reply within one business day. Meanwhile, feel free to try the individual assessment for free.",
    },
    quickAskError: {
      hu: "Nem sikerült elküldeni — próbáld újra, vagy írj az info@trita.io címre.",
      en: "Couldn't send — try again, or email info@trita.io.",
    },
  },
  // ── Hírlevél / blog-feliratkozás (2026-08-21) ───────────────────────────
  // Saját névtér, mert négy különböző felületen jelenik meg ugyanaz az
  // űrlap (blog-lista, cikk vége, lábléc, vendég-teszt záróoldal), plusz a
  // két visszajelző oldal. A hangnem szándékosan halk: nem „iratkozz fel
  // most!", hanem egy ajánlat, aminek az ára látszik (mit és milyen gyakran).
  newsletter: {
    eyebrow: { hu: "Értesítő", en: "Updates" },
    title: {
      hu: "Új cikkek és ritka, válogatott összefoglalók",
      en: "New articles and occasional curated digests",
    },
    sub: {
      hu: "Minden új blogbejegyzésről értesítünk, és időnként több cikkből álló szerkesztett hírlevelet küldünk. Bármikor leiratkozhatsz.",
      en: "We notify you about each new article and occasionally send a curated multi-article newsletter. Unsubscribe any time.",
    },
    // Rövid változat a lábléchez és az oldalsávhoz — ott nincs hely a fentire.
    compactTitle: { hu: "Cikkek és Trita-hírlevél", en: "Articles and the Trita newsletter" },
    emailLabel: { hu: "Email cím", en: "Email address" },
    emailPlaceholder: { hu: "te@pelda.hu", en: "you@example.com" },
    submit: { hu: "Feliratkozom", en: "Subscribe" },
    submitting: { hu: "Küldés...", en: "Sending..." },
    // A hozzájárulás szövege — a beküldés GOMBJÁNÁL kell állnia, hogy a
    // hozzájárulás tájékozott legyen (nem elég az adatkezelési tájékoztatóban).
    consent: {
      hu: "A feliratkozással hozzájárulsz az új cikkekről szóló értesítésekhez és az időszaki Trita-hírlevélhez. A kézbesítést és az első linkkérést mérjük, megnyitást nem. Bármikor leiratkozhatsz.",
      en: "By subscribing you agree to new-article notifications and the occasional Trita newsletter. We measure delivery and the first link request, but not opens. You can unsubscribe any time.",
    },
    privacyLink: { hu: "Adatkezelés", en: "Privacy" },
    // A siker-üzenet SZÁNDÉKOSAN nem árulja el, hogy a cím már fent volt-e a
    // listán — a végpont sem teszi (ld. api/newsletter/subscribe/route.ts).
    successTitle: { hu: "Nézd meg a postafiókod", en: "Check your inbox" },
    successBody: {
      hu: "Küldtünk egy megerősítő levelet. Amíg rá nem kattintasz, nem küldünk semmit.",
      en: "We sent you a confirmation email. Until you click it, we won't send anything.",
    },
    confirmActionTitle: {
      hu: "Erősítsd meg a feliratkozásod",
      en: "Confirm your subscription",
    },
    confirmActionBody: {
      hu: "A feliratkozás csak az alábbi gomb megnyomásával válik aktívvá; a levélben lévő link puszta megnyitása nem elég.",
      en: "Your subscription only becomes active after pressing the button below; merely opening the link in the email is not enough.",
    },
    confirmActionCta: { hu: "Igen, feliratkozom", en: "Yes, subscribe me" },
    unsubscribeActionTitle: {
      hu: "Leiratkozol a Trita leveleiről?",
      en: "Unsubscribe from Trita emails?",
    },
    unsubscribeActionBody: {
      hu: "A gomb megnyomása után nem küldünk több blogértesítőt vagy szerkesztett hírlevelet erre a címre.",
      en: "After pressing the button, we will stop sending article notifications and curated newsletters to this address.",
    },
    unsubscribeActionCta: { hu: "Igen, leiratkozom", en: "Yes, unsubscribe" },
    errorInvalid: {
      hu: "Ez az email cím nem tűnik érvényesnek.",
      en: "That email address doesn't look valid.",
    },
    errorRateLimited: {
      hu: "Túl sok próbálkozás. Várj egy percet, és próbáld újra.",
      en: "Too many attempts. Wait a minute and try again.",
    },
    errorGeneric: {
      hu: "Nem sikerült a feliratkozás. Kérlek próbáld újra.",
      en: "Subscription failed. Please try again.",
    },
    // ── Megerősítő oldal (/newsletter/confirmed) ──
    confirmedTitle: { hu: "Kész, feliratkoztál", en: "You're subscribed" },
    confirmedBody: {
      hu: "Szólunk, amint új cikk jelenik meg. Minden levél alján találsz egyetlen kattintásos leiratkozó linket.",
      en: "We'll write when a new article goes live. Every email has a one-click unsubscribe link at the bottom.",
    },
    confirmExpiredTitle: { hu: "A link lejárt", en: "This link has expired" },
    confirmExpiredBody: {
      hu: "A megerősítő link 7 napig él. Iratkozz fel újra — küldünk egy friss levelet.",
      en: "Confirmation links live for 7 days. Subscribe again and we'll send a fresh one.",
    },
    confirmInvalidTitle: { hu: "Ezt a linket nem ismerjük", en: "We don't recognise this link" },
    confirmInvalidBody: {
      hu: "Lehet, hogy a leveleződ megtörte a linket. Próbáld meg újra a feliratkozást.",
      en: "Your email client may have broken the link. Try subscribing again.",
    },
    // ── Leiratkozó oldal (/newsletter/unsubscribed) ──
    unsubscribedTitle: { hu: "Leiratkoztál", en: "You're unsubscribed" },
    unsubscribedBody: {
      hu: "Nem küldünk több értesítőt erre a címre. Ha meggondolod magad, bármikor visszajöhetsz.",
      en: "We won't send any more updates to this address. If you change your mind, you're welcome back.",
    },
    unsubscribeInvalidTitle: { hu: "Ezt a linket nem ismerjük", en: "We don't recognise this link" },
    unsubscribeInvalidBody: {
      hu: "Lehet, hogy már leiratkoztál. Ha továbbra is kapsz leveleket, írj nekünk a Kapcsolat oldalról.",
      en: "You may already be unsubscribed. If emails keep arriving, reach us via the Contact page.",
    },
    backToBlog: { hu: "Vissza a blogra", en: "Back to the blog" },
  },

  blog: {
    heroTitle: {
      hu: "Csapatintelligencia. Pszichológia. ",
      en: "Team intelligence. Psychology. ",
    },
    heroTitleEm: { hu: "Döntések.", en: "Decisions." },
    heroSub: {
      hu: "Gyakorlati cikkek arról, hogyan tehető láthatóvá a csapatdinamika — és hogyan lehet jobb döntéseket hozni emberekről.",
      en: "Practical articles on how to make team dynamics visible — and how to make better decisions about people.",
    },
    empty: { hu: "Hamarosan...", en: "Coming soon..." },
    featured: { hu: "Kiemelt cikk", en: "Featured" },
    minRead: { hu: "perc olvasás", en: "min read" },
    readCta: { hu: "Olvasom", en: "Read" },
    backToBlog: { hu: "Vissza a blogra", en: "Back to blog" },
    readNext: { hu: "Ezt olvasd tovább", en: "Read next" },
    tryEyebrow: { hu: "Próbáld ki", en: "Try it" },
    tryTitle: {
      hu: "Nézd meg, milyen eredményt kapsz.",
      en: "See what your results look like.",
    },
    trySub: {
      hu: "~10 perc, és használható képet kapsz arról, mit viszel a csapatba — ingyenesen.",
      en: "In ~10 minutes, get a useful picture of what you bring to a team — for free.",
    },
    tryCta: { hu: "Teszt indítása", en: "Start assessment" },
    returnEyebrow: { hu: "Saját felületed", en: "Your space" },
    returnTitle: {
      hu: "Folytasd ott, ahol tartasz.",
      en: "Continue where you left off.",
    },
    returnSub: {
      hu: "Megmutatjuk a profilodhoz illő következő lépést.",
      en: "We’ll show the next step that fits your profile.",
    },
    returnCta: { hu: "Saját felület megnyitása", en: "Open my space" },
    // ── Blog UX 2. kör (2026-07-24) ──
    filterLabel: { hu: "Téma szerint", en: "Filter by topic" },
    filterAll: { hu: "Összes", en: "All" },
    clearFilter: { hu: "Szűrés törlése", en: "Clear filter" },
    resultOne: { hu: "cikk", en: "article" },
    resultMany: { hu: "cikk", en: "articles" },
    newBadge: { hu: "Új", en: "New" },
    startHere: { hu: "Új itt? Kezdd ezzel a hárommal", en: "New here? Start with these three" },
    inThisArticle: { hu: "Ebben a cikkben", en: "In this article" },
    minutesLeft: { hu: "még ~{m} perc olvasás", en: "~{m} min left" },
    authorTeam: { hu: "a Trita módszertani csapata", en: "the Trita methodology team" },
    share: { hu: "Megosztás", en: "Share" },
    copyLink: { hu: "Link másolása", en: "Copy link" },
    linkCopied: { hu: "Másolva", en: "Copied" },
    prevArticle: { hu: "Előző cikk", en: "Previous article" },
    nextArticle: { hu: "Következő cikk", en: "Next article" },
    articleNavigation: { hu: "További cikkek", en: "More articles" },
  },
  pilot: {
    // Hero
    eyebrow: { hu: "Pilotprogram", en: "Pilot program" },
    badge: { hu: "Az első partnercsapatoknak", en: "For our first partner teams" },
    heroTitle: { hu: "Tedd láthatóvá, hogyan ", en: "Make visible how your " },
    heroTitleEm: { hu: "működik a csapatod.", en: "team really works." },
    heroBody: {
      hu: "A 90 napos pilotban közös, mérhető képet készítünk a csapat működéséről. Megnézzük, mire lehet építeni, hol érdemes változtatni, majd kijelölünk és visszamérünk egy konkrét vezetői lépést. Végig személyesen dolgozunk veletek.",
      en: "During the 90-day pilot, we build a shared, measurable picture of how your team works. We identify what to build on, where change would help, then choose and remeasure one concrete leadership action. We work with you personally throughout.",
    },
    heroCta: { hu: "Jelentkezem a pilotprogramba", en: "Apply to the pilot program" },
    heroCtaSecondary: { hu: "Mit kapsz pontosan?", en: "What do you get exactly?" },
    metaChip1: { hu: "90 nap teljes hozzáférés", en: "90 days full access" },
    metaChip2: { hu: "Közös értelmező workshop", en: "Joint interpretation workshop" },
    metaChip3: { hu: "Konkrét akció és visszamérés", en: "Concrete action and follow-up" },

    // Aside — "Miért most"
    asideEyebrow: { hu: "Kinek szól", en: "Who it is for" },
    asideTitle: {
      hu: "Közös munka, nem még egy kérdőív.",
      en: "A shared process, not just another survey.",
    },
    asideBody: {
      hu: "Olyan csapatokat keresünk, amelyek szeretnék jobban érteni a saját működésüket, és készek egy konkrét változtatást is kipróbálni.",
      en: "We are looking for teams that want to understand how they work and are ready to try one concrete change.",
    },

    // Signals
    signal1Value: { hu: "90", en: "90" },
    signal1Label: { hu: "nap közös munka", en: "days of collaboration" },
    signal2Value: { hu: "60′", en: "60′" },
    signal2Label: { hu: "közös értelmező workshop", en: "joint interpretation workshop" },
    signal3Value: { hu: "1", en: "1" },
    signal3Label: { hu: "munkanap válaszidő", en: "business day to reply" },

    // Aside — "Mire jó ez a 90 nap"
    aside90Eyebrow: { hu: "Mire jó ez a 90 nap", en: "What the 90 days are for" },
    aside90Body: {
      hu: "Feltérképezzük a csapat kapcsolatait és azt, mennyire biztonságos kérdezni, hibázni vagy ellentmondani. Ezután választunk egy vezetői lépést, amelynek hatását a program végén újra megmérjük.",
      en: "We map the team's relationships and how safe it feels to ask, make mistakes, or disagree. We then choose one leadership action and measure its effect again at the end of the program.",
    },

    // Benefits section
    benefitsEyebrow: { hu: "Mit kapsz", en: "What you get" },
    benefitsTitle: { hu: "Mérés, közös értelmezés és egy követhető következő lépés.", en: "Measurement, shared interpretation, and a next step you can follow." },
    benefit1Title: { hu: "Egységes induló mérés", en: "A consistent baseline" },
    benefit1Desc: {
      hu: "Minden csapat ugyanazzal a három alapréteggel indul: önértékeléssel, mért bizalmi hálóval és névtelen pszichológiai biztonság-felméréssel. Az observer-, peer- és csapatszerep-kör külön kiegészítő.",
      en: "Every team starts with the same three core layers: self-assessment, a measured trust network, and an anonymous psychological safety survey. Observer, peer, and team-role rounds are separate add-ons.",
    },
    benefit2Title: { hu: "Közös értelmező workshop", en: "Joint interpretation workshop" },
    benefit2Desc: {
      hu: "Egy 60 perces alkalmon együtt olvassuk a csapatképet. Megnevezzük a legfontosabb erősséget és feszültségpontot, majd kiválasztjuk, min érdemes először változtatni.",
      en: "In a 60-minute session, we read the team picture together. We identify the most important strength and point of tension, then choose what to change first.",
    },
    benefit5Title: { hu: "Visszamérési kör", en: "Follow-up measurement round" },
    benefit5Desc: {
      hu: "A vállalt akció után újra megmérjük a változtatható mutatókat. Csak olyan elmozdulást nevezünk fejlődésnek, amelyet az adatok valóban alátámasztanak.",
      en: "After the agreed action, we measure the changeable outcomes again. We only call it progress when the data genuinely supports that conclusion.",
    },
    benefit6Title: { hu: "Korai partner státusz", en: "Early partner status" },
    benefit6Desc: {
      hu: "Közvetlenül alakíthatjátok, hogyan fejlődjön a program. A pilotban kialakított egyedi feltételeket a későbbi együttműködésben is megőrizzük.",
      en: "You can directly shape how the program develops. We preserve the individual terms agreed during the pilot in our future work together.",
    },

    // Steps section
    stepsEyebrow: { hu: "Hogyan működik", en: "How it works" },
    stepsTitle: { hu: "Három jól követhető szakasz 90 nap alatt.", en: "Three clear stages over 90 days." },
    step1Title: { hu: "Felmérés", en: "Assessment" },
    step1Desc: {
      hu: "A csapattagok kitöltik az önértékelést és a rövid, névtelen csapatfelméréseket. Mi közben figyeljük a részvételt, és segítünk, ha valaki elakad.",
      en: "Team members complete the self-assessment and the short, anonymous team surveys. We monitor participation and help if anyone gets stuck.",
    },
    step2Title: { hu: "Közös kép", en: "Shared picture" },
    step2Desc: {
      hu: "Elkészítjük és közösen értelmezzük a csapatképet. A riport egyértelműen jelzi, mi mért adat, mi becslés, és hol nincs még elég információ.",
      en: "We prepare and interpret the team picture together. The report clearly distinguishes measured data, estimates, and areas where there is not yet enough information.",
    },
    step3Title: { hu: "Akció és visszamérés", en: "Action and follow-up" },
    step3Desc: {
      hu: "Kiválasztunk egy konkrét vezetői lépést, amelyet a mindennapi munkában is ki lehet próbálni. A program végén megnézzük, hozott-e mérhető változást.",
      en: "We choose one concrete leadership action that can be tried in day-to-day work. At the end of the program, we check whether it produced measurable change.",
    },

    // Commitments section
    commitmentsEyebrow: { hu: "Mit kérünk cserébe", en: "What we ask in return" },
    commitmentsTitle: { hu: "Valódi használatot és őszinte visszajelzést.", en: "Genuine use and honest feedback." },
    commitmentLabel: { hu: "Amit vállaltok", en: "Your commitment" },
    commitment1Title: { hu: "Aktív használat", en: "Active usage" },
    commitment1Desc: {
      hu: "A csapat kitölti a felméréseket, a kijelölt vezető pedig kipróbálja a közösen választott akciót a mindennapi munkában.",
      en: "The team completes the surveys, and the designated leader tries the jointly selected action in day-to-day work.",
    },
    commitment2Title: { hu: "Két visszajelző beszélgetés", en: "Two feedback conversations" },
    commitment2Desc: {
      hu: "A 30. és 60. nap környékén 20–30 percben átbeszéljük, mi működik, hol akadtatok el, és min érdemes változtatnunk.",
      en: "Around days 30 and 60, we spend 20–30 minutes discussing what works, where you got stuck, and what we should change.",
    },
    commitment3Title: { hu: "Tapasztalatmegosztás", en: "Sharing your experience" },
    commitment3Desc: {
      hu: "Ha a program valódi értéket adott, engedélyt kérünk egy rövid, egyeztetett visszajelzés vagy anonimizált tapasztalat megosztására.",
      en: "If the program delivered real value, we ask permission to share a short, agreed testimonial or anonymized account of your experience.",
    },

    // Application form section
    formEyebrow: { hu: "Jelentkezés", en: "Apply" },
    formTitle: { hu: "Beszéljünk a csapatodról.", en: "Let's talk about your team." },
    formBody: {
      hu: "Töltsd ki a rövid űrlapot, és egy munkanapon belül jelentkezünk. Először kötelezettség nélkül átbeszéljük, mire van szükségetek.",
      en: "Complete the short form and we will get back to you within one business day. We begin with a no-obligation conversation about what your team needs.",
    },
    fitEyebrow: { hu: "Nektek való, ha", en: "Good fit if" },
    fitBody: {
      hu: "van egy együtt dolgozó csapatotok, szeretnétek tisztábban látni a működését, és készek vagytok egy közösen választott változtatást kipróbálni.",
      en: "you have a team that works together, want a clearer picture of how it operates, and are ready to try one jointly selected change.",
    },

    // Form fields
    formHeading: { hu: "Rövid jelentkezés", en: "Quick application" },
    formSubheading: {
      hu: "Két perc alatt kitölthető. A csapatról szóló kérdéshez egy mondat is elég.",
      en: "It takes two minutes. One sentence about your team is enough.",
    },
    formSpotsLabel: { hu: "Első kör", en: "Early cohort" },
    labelName: { hu: "Név", en: "Name" },
    placeholderName: { hu: "Teljes neved", en: "Full name" },
    labelEmail: { hu: "Email", en: "Email" },
    placeholderEmail: { hu: "nev@ceg.hu", en: "name@company.com" },
    labelCompany: { hu: "Cég neve", en: "Company name" },
    placeholderCompany: { hu: "Pl. Innovate Kft.", en: "e.g. Innovate Ltd." },
    labelSize: { hu: "Csapatméret", en: "Team size" },
    sizeOption0: { hu: "Válassz...", en: "Select..." },
    sizeOption1: { hu: "5–10 fő", en: "5–10 people" },
    sizeOption2: { hu: "11–25 fő", en: "11–25 people" },
    sizeOption3: { hu: "26–50 fő", en: "26–50 people" },
    sizeOption4: { hu: "51–80 fő", en: "51–80 people" },
    sizeOption5: { hu: "80+ fő", en: "80+ people" },
    labelQuestion: {
      hu: "Mi a legfontosabb kérdésed a csapatoddal kapcsolatban?",
      en: "What's the most important question about your team?",
    },
    placeholderQuestion: {
      hu: "Opcionális, de sokat segít az első beszélgetéshez.",
      en: "Optional, but it helps a lot for the first conversation.",
    },
    submitSending: { hu: "Küldés...", en: "Sending..." },
    submitDefault: { hu: "Jelentkezem a pilotprogramba", en: "Apply to the pilot program" },
    preferEmail: { hu: "Inkább emailben?", en: "Prefer email?" },
    errorMessage: {
      hu: "Nem sikerült elküldeni. Próbáld újra, vagy írj a hello@trita.io címre.",
      en: "We could not send your application. Try again, or email hello@trita.io.",
    },

    // Success state
    successTitle: { hu: "Köszönjük a jelentkezést.", en: "Thank you for applying." },
    successBody: {
      hu: "Egy munkanapon belül személyesen jelentkezünk a megadott email-címen.",
      en: "We will contact you personally at the provided email address within one business day.",
    },
  },
  // ── /about — „Mi az a Trita" ────────────────────────────────────────
  // A gondolat-oldal: mire épül a termék, milyen rétegekből áll össze a
  // kép, és mi a célunk vele. A többi marketing-laptól az különbözteti
  // meg, hogy NEM árazó ajánlat-lap — magyaráz és irányba tesz; a
  // részletes ajánlat a /how-we-work és a /pilot dolga.
  //
  // Brand-kör (2026-08-09, 2. kör): a versenytárs-összevetés („miért más,
  // mint egy átlagos teszt/felmérés") NEM ennek a lapnak a dolga — az a
  // landing ProofSection-jében él, itt ismételte volna. Helyette: kinek
  // szól (egyéni kitöltő ÉS csapat), miért építjük (motiváció), és a
  // catch phrase — „Ami mérhető, az megbeszélhető." — ami a szokásos
  // „amit mérünk, azt kezeljük" menedzsment-közhely emberi fordulata:
  // nem kezelni akarjuk az embereket, hanem beszélgetni róluk.
  //
  // Szóhasználat (CLAUDE.md): „hat személyiségdimenzió" (a modellnév nem
  // megy ki a felületre), „csapatszerep-kérdőív" (nem Belbin), a
  // kérdésbank „szabadon felhasználható, kutatásban használt".
  about: {
    // ── Hero ──
    heroEyebrow: { hu: "A trita gondolat", en: "The idea behind trita" },
    heroTitleBefore: { hu: "Ami mérhető, az ", en: "What you can measure, you can " },
    heroTitleEm: { hu: "megbeszélhető.", en: "talk about." },
    heroBody: {
      hu: "A munkahelyi önismeret és a csapatról alkotott kép ma többnyire benyomásokra épül — két ember ugyanarról a helyzetről két külön történetet mesél, és nincs mihez viszonyítani. A Trita ezt az alapot cseréli le mérhető, közösen olvasható képre: előbb rólad, aztán — ha csapatban dolgoztok — rólatok.",
      en: "Self-knowledge at work, and the picture we hold of a team, are mostly built on impressions — two people tell two different stories about the same situation, with nothing to compare them against. Trita replaces that footing with a measurable picture everyone can read: first about you, then — if you work as a team — about all of you.",
    },
    heroLead: {
      hu: "Ez az oldal arról szól, hogyan áll össze ez a kép, és mi a célunk vele.",
      en: "This page is about how that picture comes together — and what we're aiming at with it.",
    },
    heroCtaPrimary: { hu: "Beszéljünk a csapatotokról", en: "Let's talk about your team" },
    heroCtaSecondary: { hu: "Kipróbálom magamon", en: "Try it on myself" },
    heroChip1: TEAM_SCAN_CONTRACT.layerCount,
    heroChip2: { hu: "Tanácsadói validálás", en: "Consultant validation" },
    heroChip3: { hu: "Becsült és mért mindig jelölve", en: "Estimated vs. measured always labeled" },
    // Az aside a MOTIVÁCIÓ — az egyetlen hely a publikus felületen, ahol
    // első szám többesben kimondjuk, miért építjük ezt az egészet.
    asideEyebrow: { hu: "Miért építjük", en: "Why we're building it" },
    asideTitle: {
      hu: "Mert a legfontosabb beszélgetések ma elmaradnak.",
      en: "Because the conversations that matter most don't happen.",
    },
    asideBody: {
      hu: "Túl sok jó csapat működik vakon: a szerepekről, a súrlódásokról, az egymás közti különbségekről akkor esik szó először, amikor már baj van. Azt akarjuk, hogy ezekhez a beszélgetésekhez legyen közös nyelv — és hogy időben történjenek meg, ne utólag.",
      en: "Too many good teams run blind: roles, friction and the differences between people first come up when something is already wrong. We want these conversations to have a shared language — and to happen in time, not in hindsight.",
    },

    // ── Kinek szól ──
    audienceEyebrow: { hu: "Kinek szól", en: "Who it's for" },
    audienceTitle: {
      hu: "Magadnak ingyenes. A csapatnak közös munka.",
      en: "Free for yourself. A joint program for the team.",
    },
    audienceSelfTitle: { hu: "Egyéni kitöltőknek", en: "For individuals" },
    audienceSelfDesc: {
      hu: "Teljes egyéni felmérés nagyjából 10 perc alatt, dimenziószintű riport, munkastílus, csapatszerepek és külső visszajelzés — ingyen, rejtett fizetős szint nélkül. Az eredményed a tiéd: ha egy szervezet hívott meg, a csapatképben akkor is csak összesítve jelensz meg.",
      en: "The full individual assessment in about 10 minutes, with a dimension-level report, work style, team roles and external feedback — free, with no hidden paid tier. Your result is yours: even if an organization invited you, you only ever appear in the team picture in aggregate.",
    },
    audienceSelfCta: { hu: "Kipróbálom ingyen", en: "Try it for free" },
    audienceTeamTitle: { hu: "Csapatoknak és vezetőknek", en: "For teams and leaders" },
    audienceTeamDesc: {
      hu: "Tanácsadó vezette program: a három alaprétegből jóváhagyott csapatkép készül, amit közös workshopon értelmezünk — a vállalt akció hatását pedig a következő körben visszamérjük. Az ár a létszámtól és a program mélységétől függ.",
      en: "A consultant-led program: the three core layers become an approved team picture we interpret together in a workshop — then the next round measures the effect of the agreed action. Pricing depends on headcount and depth.",
    },
    audienceTeamCta: { hu: "Beszéljünk a csapatotokról", en: "Let's talk about your team" },

    // ── Hogyan épül fel (rétegábra) ──
    buildEyebrow: { hu: "Hogyan épül fel", en: "How it's built" },
    buildTitle: { hu: "Három alapréteg, ami egyetlen képpé áll össze.", en: "Three core layers that become a single picture." },
    buildLead: {
      hu: "Minden alapréteg önmagában is olvasható, de az igazi érték az összeolvasásukban van. Az observer-visszajelzés, a peer-kör és a csapatszerepek igény szerint kapcsolhatók hozzájuk.",
      en: "Each core layer stands on its own, but the value is in reading them together. Observer feedback, peer rounds, and team roles can be added when they serve the team's goal.",
    },
    buildDiagramAlt: {
      hu: "Ábra: a három alapréteg egyetlen, tanácsadó által jóváhagyott csapatképpé fut össze.",
      en: "Diagram: the three core layers converge into a single, consultant-approved team picture.",
    },
    layer1Title: TEAM_SCAN_CONTRACT.layer1Title,
    layer1Desc: TEAM_SCAN_CONTRACT.layer1Desc,
    layer1Tag: TEAM_SCAN_CONTRACT.layer1Tag,
    layer2Title: TEAM_SCAN_CONTRACT.layer2Title,
    layer2Desc: TEAM_SCAN_CONTRACT.layer2Desc,
    layer2Tag: TEAM_SCAN_CONTRACT.layer2Tag,
    layer3Title: TEAM_SCAN_CONTRACT.layer3Title,
    layer3Desc: TEAM_SCAN_CONTRACT.layer3Desc,
    layer3Tag: TEAM_SCAN_CONTRACT.layer3Tag,
    optionalLabel: TEAM_SCAN_CONTRACT.optionalLabel,
    optionalObserver: TEAM_SCAN_CONTRACT.optionalObserver,
    optionalPeer: TEAM_SCAN_CONTRACT.optionalPeer,
    optionalRoles: TEAM_SCAN_CONTRACT.optionalRoles,
    buildOutcomeLabel: { hu: "Ebből lesz", en: "Which becomes" },
    buildOutcomeTitle: { hu: "Jóváhagyott csapatkép", en: "An approved team picture" },
    buildOutcomeDesc: TEAM_SCAN_CONTRACT.outcomeDesc,

    // ── Az út ──
    pathEyebrow: { hu: "Az út", en: "The path" },
    pathTitle: { hu: "Magadtól a csapaton át a szervezetig.", en: "From yourself through the team to the organization." },
    pathLead: {
      hu: "Ugyanaz a mérés más-más felbontásban válik hasznossá. Mindenki a saját eredményénél kezd, és csak az látja a következő szintet, akinek szerepe van benne.",
      en: "The same measurement becomes useful at different resolutions. Everyone starts with their own result, and only those with a role at the next level get to see it.",
    },
    pathDiagramAlt: {
      hu: "Ábra: a mérés köre az egyéntől a külső visszajelzésen és a csapaton át a szervezetig tágul.",
      en: "Diagram: the circle of measurement widens from the individual through external feedback and the team to the organization.",
    },
    path1Title: { hu: "Magad", en: "Yourself" },
    path1Desc: {
      hu: "A saját profilod, munkastílusod, csapatszerepeid és fejlődési fókuszod. Ez a réteg ingyenes, és önmagában is teljes.",
      en: "Your own profile, work style, team roles and growth focus. This layer is free, and complete in itself.",
    },
    path2Title: { hu: "Ahogy mások látnak", en: "How others see you" },
    path2Desc: {
      hu: "A külső visszajelzések a saját eredményed mellé kerülnek — nem helyette. A kettő eltérése a beszélgetés kiindulópontja.",
      en: "External feedback sits next to your own result — not instead of it. The gap between them is where the conversation starts.",
    },
    path3Title: { hu: "A csapat", en: "The team" },
    path3Desc: {
      hu: "Az egyéni profilok mellé mért bizalmi háló és pszichológiai biztonság kerül. A 16-as minta ezt értelmező nyelvként, nem bizonyítékként foglalja keretbe.",
      en: "Measured trust network and psychological safety sit next to individual profiles. The 16-pattern model frames this as interpretive language, not as evidence itself.",
    },
    path4Title: { hu: "A szervezet", en: "The organization" },
    path4Desc: {
      hu: "Több csapat egymás mellett: hol ismétlődik ugyanaz a minta, és hol egyedi a helyzet.",
      en: "Several teams side by side: where the same pattern repeats, and where a situation is genuinely unique.",
    },

    // ── Alapelvek ──
    valuesEyebrow: { hu: "Amit betartunk", en: "What we hold to" },
    valuesTitle: {
      hu: "Hitelesség nélkül a mérés csak vélemény, drágábban.",
      en: "Without credibility, a measurement is just an opinion — at a higher price.",
    },
    value1Title: { hu: "Becsült és mért soha nem mosódik össze", en: "Estimated and measured never blur" },
    value1Desc: {
      hu: "Ahol becslésből dolgozunk, ott az oda van írva. Minden elemzési kimeneten látszik a forrás és a megbízhatóság — ez alapszabály, nem beállítás.",
      en: "Where we work from an estimate, it says so. Every analytical output carries its source and confidence — this is a ground rule, not a setting.",
    },
    value2Title: { hu: "A csapatkép aggregált", en: "The team picture is aggregated" },
    value2Desc: {
      hu: "A vezető nem látja senkinek az egyéni pontszámát. Csapatátlagot és szórást igen — a mögötte lévő embereket nem.",
      en: "A manager never sees anyone's individual score. Team average and spread, yes — the people behind them, no.",
    },
    value3Title: { hu: "Ember olvassa el, mielőtt kimegy", en: "A human reads it before it ships" },
    value3Desc: {
      hu: "A csapatképet publikálás előtt tanácsadó ellenőrzi és értelmezi. A számokból így nem lesz félreolvasható ítélet.",
      en: "A consultant reviews and interprets the team picture before it's published, so the numbers don't turn into a verdict that can be misread.",
    },
    value4Title: { hu: "Nincs jó és rossz profil", en: "There is no good or bad profile" },
    value4Desc: {
      hu: "Ami az egyik helyzetben erősség, a másikban kockázat. A riport ezt mondja ki — nem rangsorol embereket.",
      en: "What is a strength in one situation is a risk in another. The report says exactly that — it doesn't rank people.",
    },

    // ── A cél ──
    goalEyebrow: { hu: "Mi a célunk", en: "What we're aiming at" },
    goalTitle: {
      hu: "Hogy az emberekről szóló beszélgetések végre ugyanarról szóljanak.",
      en: "So that conversations about people are finally about the same thing.",
    },
    goalDiagramAlt: {
      hu: "Ábra: az össze nem vethető benyomásokból rendezett, közösen olvasható kép lesz.",
      en: "Diagram: incomparable impressions become an ordered picture everyone can read.",
    },
    goalBody1: {
      hu: "Az a célunk, hogy az önismeret munkaeszköz legyen, ne poszterbölcsesség — és hogy egy csapatban ne kelljen évekig együtt dolgozni ahhoz, hogy kiderüljön, ki mihez ért és mi miért csúszik. Amit ma három év közös tapasztalata ad meg, azt szeretnénk pár hét alatt megbeszélhetővé tenni.",
      en: "Our aim is for self-knowledge to be a working tool, not poster wisdom — and for a team not to need years together before it becomes clear who's good at what and why things slip. What three years of shared experience gives you today, we want to make discussable in a few weeks.",
    },
    goalBody2: {
      hu: "És hogy ne egy riport legyen, amit senki nem nyit ki. A Trita a tanácsadói munka eszköze: a mérés adja a képet, a közös értelmezés a jelentését, a platform pedig azt, hogy fél év múlva is visszanézhető legyen, mi változott.",
      en: "And that it shouldn't be a report nobody opens. Trita is a tool for consulting work: the measurement provides the picture, the joint debrief provides its meaning, and the platform makes it possible to look back six months later and see what changed.",
    },
    goalBeforeLabel: { hu: "Enélkül", en: "Without it" },
    goalBeforeText: { hu: "Benyomások, amiket nem lehet egymás mellé tenni.", en: "Impressions that can't be placed side by side." },
    goalAfterLabel: { hu: "Ezzel", en: "With it" },
    goalAfterText: { hu: "Egy kép, amiről ugyanazon a nyelven lehet beszélni.", en: "A picture you can discuss in the same language." },

    // ── Záró CTA ──
    ctaTitle: { hu: "Kezdjük egy beszélgetéssel.", en: "Let's start with a conversation." },
    ctaBody: {
      hu: "Mesélj a csapatodról — egy munkanapon belül válaszolunk. Ha előbb magadon néznéd meg, az egyéni felmérés ingyenes.",
      en: "Tell us about your team — we reply within one business day. If you'd rather try it on yourself first, the individual assessment is free.",
    },
    ctaPrimary: { hu: "Kapcsolatfelvétel", en: "Get in touch" },
    ctaSecondary: { hu: "Kipróbálom magamon", en: "Try it on myself" },

    // Híd a /rolunk felé — a motiváció-aside teaserré vált, a teljes
    // történet ott él.
    asideLink: { hu: "Ismerd meg, ki áll mögötte", en: "Meet who's behind it" },
  },
  // ── /rolunk — „Kik vagyunk" ─────────────────────────────────────────
  // Az /about a gondolaté (mi ez, hogyan épül fel) — ez az oldal az
  // embereké (ki építi, miért, hogyan dolgozik). Szándékosan külön lap:
  // összemosva mindkettő fókusza hígulna.
  //
  // Hang: T/1 műhely-„mi" — 2026-08-10-től ez az egységes brand-hang
  // MINDENHOL (a korábbi pilot-oldali E/1 „én" is erre váltott). Név és
  // fotó SZÁNDÉKOSAN nincs még — amint lesz publikus bemutatkozó, ide
  // kerül; addig nem tákolunk arctalan „csapatunk" rácsot.
  aboutUs: {
    heroEyebrow: { hu: "Rólunk", en: "About us" },
    heroTitleBefore: { hu: "A Trita mögött nem szoftvercég áll, hanem egy ", en: "Behind Trita you won't find a software company — you'll find a " },
    heroTitleEm: { hu: "tanácsadói műhely.", en: "consulting practice." },
    heroLead: {
      hu: "Csapatokkal dolgozunk, és a platformot eredetileg a saját munkánkhoz építettük. Ez az oldal arról szól, kik vagyunk, miért csináljuk — és hogyan dolgozunk azokkal, akik minket választanak.",
      en: "We work with teams, and we originally built the platform for our own consulting work. This page is about who we are, why we do this — and how we work with the teams who choose us.",
    },

    // ── Miért építjük ──
    storyEyebrow: { hu: "Miért építjük", en: "Why we're building it" },
    storyTitle: {
      hu: "Abból a pillanatból született, amikor valami láthatóvá válik.",
      en: "Born from the moment when something becomes visible.",
    },
    storyP1: {
      hu: "Tanácsadóként újra és újra ugyanazt a pillanatot kerestük a csapatoknál: amikor egy mintázat, amit addig mindenki csak sejtett, egyszer csak kimondhatóvá válik. A workshopok legértékesebb percei mindig ezek voltak — és túl sok múlt azon, hogy aznap sikerül-e eljutni idáig.",
      en: "As consultants we kept looking for the same moment in every team: when a pattern everyone had only sensed suddenly becomes something you can say out loud. Those were always the most valuable minutes of a workshop — and too much depended on whether we got there that day.",
    },
    storyP2: {
      hu: "A Trita azért készült, hogy ezt a pillanatot ne a szerencsére bízzuk, hanem mérésre. Először a saját munkánkhoz építettünk eszközt; aztán kiderült, hogy a csapatok maguk is vissza akarják nézni, mi változott — így lett az eszközből platform.",
      en: "Trita exists so that this moment isn't left to luck, but to measurement. We first built a tool for our own work; then it turned out teams wanted to come back and see what had changed — and the tool became a platform.",
    },
    storyP3: {
      hu: "A nevünk mögött ma egy kis műhely áll: tanácsadói munka és az azt kiszolgáló módszertani fejlesztés. Nem akarunk mindenkinek mindent — kevés csapattal dolgozunk, azokkal viszont közel.",
      en: "Behind the name today is a small workshop: consulting work and the methodology that serves it. We don't want to be everything to everyone — we work with few teams, but closely.",
    },

    // ── Így dolgozunk ──
    howEyebrow: { hu: "Így dolgozunk", en: "How we work" },
    howTitle: {
      hu: "Három dolog, ami nálunk nem alku tárgya.",
      en: "Three things we don't negotiate on.",
    },
    how1Title: { hu: "A tanácsadás az első", en: "Consulting comes first" },
    how1Desc: {
      hu: "A platform a közös munka eszköze, nem a helyettesítője. A mérés képet ad — az értelmezés beszélgetésben történik, nem PDF-ben.",
      en: "The platform is a tool for the joint work, not a replacement for it. Measurement gives you the picture — interpretation happens in conversation, not in a PDF.",
    },
    how2Title: { hu: "Kicsik vagyunk — szándékosan", en: "Small on purpose" },
    how2Desc: {
      hu: "Egyszerre korlátozott számú csapattal dolgozunk. Cserébe nem ticketrendszert kapsz, hanem embert — az első beszélgetéstől a workshopig ugyanazt.",
      en: "We work with a limited number of teams at a time. In return you don't get a ticketing system, you get a person — the same one from the first conversation to the workshop.",
    },
    how3Title: { hu: "A módszertan nyitott könyv", en: "The methodology is an open book" },
    how3Desc: {
      hu: "Szabadon felhasználható, kutatásban használt kérdésbankból dolgozunk, és minden kimeneten jelöljük, mi mért és mi becsült. Amit állítunk, arról meg tudjuk mutatni, honnan tudjuk.",
      en: "We work from a freely usable item pool used in research, and every output labels what is measured and what is estimated. Whatever we claim, we can show you where it comes from.",
    },

    // ── Záró CTA ──
    ctaTitle: { hu: "Beszélgessünk — ahogy dolgozni is fogunk.", en: "Let's talk — the same way we'll work." },
    ctaBody: {
      hu: "Írj pár mondatot a csapatodról, és egy munkanapon belül személyesen válaszolunk. Ha előbb a felépítés érdekel, nézd meg, hogyan áll össze a kép.",
      en: "Write a few lines about your team and you'll get a personal reply within one business day. If you'd rather see the mechanics first, have a look at how the picture comes together.",
    },
    ctaPrimary: { hu: "Kapcsolatfelvétel", en: "Get in touch" },
    ctaSecondary: { hu: "Hogyan épül fel a Trita?", en: "How is Trita built?" },
  },
} as const;
